// Oitava leva — séries B de detetive/mistério em domínio público
// (Sherlock Holmes da Universal e da era Wontner, Charlie Chan da Monogram,
// Dick Tracy da RKO, Boston Blackie e The Whistler da Columbia, e as
// comédias de gangue Bowery Boys/East Side Kids da Monogram), encontradas
// via publicdomainmovie.net, archivewatch.org e emol.org. Toda essa leva de
// estúdios "poverty row" tem domínio público bem documentado por falha de
// renovação de copyright. source.id verificado manualmente na API do
// archive.org (busca por título + checagem de duração real do arquivo de
// vídeo contra a duração conhecida do filme, não só o nome do item) antes de
// entrar aqui. A sinopse foi escrita em português a partir dos fatos do
// filme (enredo, gênero, ano, diretor), sem reproduzir texto de terceiros.
module.exports = [
  {
    title: 'Sherlock Holmes and the Voice of Terror',
    slug: 'sherlock-holmes-and-the-voice-of-terror-1942',
    synopsis:
      'Primeiro dos Sherlock Holmes produzidos pela Universal com a história transposta para a Segunda Guerra: o detetive é chamado pela inteligência britânica para descobrir quem está por trás de transmissões de rádio nazistas que antecipam ataques alemães.',
    year: 1942,
    director: 'John Rawlins',
    cast: ['Basil Rathbone', 'Nigel Bruce'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 65,
    backdropUrl: 'https://archive.org/services/img/sherlock-holmes-and-the-voice-of-terror-1942',
    source: { provider: 'archive', id: 'sherlock-holmes-and-the-voice-of-terror-1942' },
    featured: false,
  },
  {
    title: 'Sherlock Holmes in Washington',
    slug: 'sherlock-holmes-in-washington-1943',
    synopsis:
      'Holmes e Watson viajam aos Estados Unidos para recuperar um microfilme escondido por um agente britânico antes que ele caia nas mãos de espiões nazistas infiltrados em Washington.',
    year: 1943,
    director: 'Roy William Neill',
    cast: ['Basil Rathbone', 'Nigel Bruce'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 71,
    backdropUrl: 'https://archive.org/services/img/shiw5344434',
    source: { provider: 'archive', id: 'shiw5344434' },
    featured: false,
  },
  {
    title: 'Sherlock Holmes Faces Death',
    slug: 'sherlock-holmes-faces-death-1943',
    synopsis:
      'Baseado em "O Ritual dos Musgrave": Holmes é chamado a uma velha propriedade de campo transformada em hospital militar, onde uma série de mortes está ligada a um antigo enigma de família.',
    year: 1943,
    director: 'Roy William Neill',
    cast: ['Basil Rathbone', 'Nigel Bruce'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 65,
    backdropUrl: 'https://archive.org/services/img/sherlock-holmes-faces-death',
    source: { provider: 'archive', id: 'sherlock-holmes-faces-death' },
    featured: false,
  },
  {
    title: 'The Triumph of Sherlock Holmes',
    slug: 'the-triumph-of-sherlock-holmes-1935',
    synopsis:
      'Adaptação britânica de "O Vale do Terror": Holmes investiga o assassinato de um homem numa mansão isolada e aos poucos revela a mão do Professor Moriarty por trás do crime.',
    year: 1935,
    director: 'Leslie S. Hiscott',
    cast: ['Arthur Wontner', 'Ian Fleming'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 84,
    backdropUrl: 'https://archive.org/services/img/The_Triumph_of_Sherlock_Holmes',
    source: { provider: 'archive', id: 'The_Triumph_of_Sherlock_Holmes' },
    featured: false,
  },
  {
    title: 'Sherlock Holmes: The Sign of Four',
    slug: 'sherlock-holmes-the-sign-of-four-1932',
    synopsis:
      'Uma mulher recebe pérolas anônimas todo ano desde a morte do pai e agora é convocada a um encontro misterioso: Holmes descobre que o caso remonta a um tesouro roubado na Índia e um pacto de sangue entre quatro homens.',
    year: 1932,
    director: 'Graham Cutts',
    cast: ['Arthur Wontner', 'Ian Hunter'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 73,
    backdropUrl: 'https://archive.org/services/img/The_Sign_OF_Four',
    source: { provider: 'archive', id: 'The_Sign_OF_Four' },
    featured: false,
  },
  {
    title: "Sherlock Holmes' Fatal Hour",
    slug: 'sherlock-holmes-fatal-hour-1931',
    synopsis:
      'Também conhecido como "The Sleeping Cardinal": um jovem oficial é acusado de desviar dinheiro do exército, e Holmes descobre que o verdadeiro autor do esquema é seu velho inimigo, o Professor Moriarty.',
    year: 1931,
    director: 'Leslie S. Hiscott',
    cast: ['Arthur Wontner'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 81,
    backdropUrl: 'https://archive.org/services/img/sherlock-holmes-fatal-hour-with-arthur-wontner-1931-1080p-hd-film',
    source: { provider: 'archive', id: 'sherlock-holmes-fatal-hour-with-arthur-wontner-1931-1080p-hd-film' },
    featured: false,
  },
  {
    title: 'The Spider Woman',
    slug: 'the-spider-woman-1943',
    synopsis:
      'Uma onda de "suicídios" misteriosos, todos de homens picados por uma aranha venenosa rara, leva Holmes a uma vilã que usa o veneno para forjar mortes e herdar fortunas de apostadores.',
    year: 1943,
    director: 'Roy William Neill',
    cast: ['Basil Rathbone', 'Nigel Bruce', 'Gale Sondergaard'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 60,
    backdropUrl: 'https://archive.org/services/img/the-spider-woman',
    source: { provider: 'archive', id: 'the-spider-woman' },
    featured: false,
  },
  {
    title: 'The Scarlet Claw',
    slug: 'the-scarlet-claw-1944',
    synopsis:
      'Holmes viaja a um vilarejo canadense onde moradores supersticiosos atribuem uma série de assassinatos brutais a um monstro do pântano, mas o detetive suspeita de um culpado bem humano.',
    year: 1944,
    director: 'Roy William Neill',
    cast: ['Basil Rathbone', 'Nigel Bruce'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 71,
    backdropUrl: 'https://archive.org/services/img/the-scarlet-claw',
    source: { provider: 'archive', id: 'the-scarlet-claw' },
    featured: false,
  },
  {
    title: 'The House of Fear',
    slug: 'the-house-of-fear-1945',
    synopsis:
      'Os membros de um clube reunido numa mansão escocesa começam a morrer, um a um, sempre precedidos pelo envio de um envelope com sementes de laranja — e cabe a Holmes decifrar o padrão antes que a lista se esgote.',
    year: 1945,
    director: 'Roy William Neill',
    cast: ['Basil Rathbone', 'Nigel Bruce'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 66,
    backdropUrl: 'https://archive.org/services/img/the-house-of-fear',
    source: { provider: 'archive', id: 'the-house-of-fear' },
    featured: false,
  },
  {
    title: 'Pursuit to Algiers',
    slug: 'pursuit-to-algiers-1945',
    synopsis:
      'Holmes e Watson são contratados para escoltar por navio o jovem herdeiro de um trono europeu até seu país, enquanto assassinos a bordo tentam impedir a viagem a qualquer custo.',
    year: 1945,
    director: 'Roy William Neill',
    cast: ['Basil Rathbone', 'Nigel Bruce'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 63,
    backdropUrl: 'https://archive.org/services/img/pursuit-to-algiers',
    source: { provider: 'archive', id: 'pursuit-to-algiers' },
    featured: false,
  },
  {
    title: 'Charlie Chan in Shanghai',
    slug: 'charlie-chan-in-shanghai-1935',
    synopsis:
      'A caminho de um jantar diplomático em Xangai, o detetive Charlie Chan recebe um aviso anônimo de que sofrerá um atentado e descobre uma rede de contrabando de ópio disfarçada de negócio legítimo.',
    year: 1935,
    director: 'James Tinling',
    cast: ['Warner Oland'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 71,
    backdropUrl: 'https://archive.org/services/img/charlie-chan-in-shanghai-1935',
    source: { provider: 'archive', id: 'charlie-chan-in-shanghai-1935' },
    featured: false,
  },
  {
    title: 'Charlie Chan in the Secret Service',
    slug: 'charlie-chan-in-the-secret-service-1944',
    synopsis:
      'Já trabalhando para os serviços de inteligência dos EUA na Segunda Guerra, Charlie Chan investiga o assassinato de um cientista que desenvolvia um aparelho militar secreto, em meio a uma casa cheia de suspeitos e espiões.',
    year: 1944,
    director: 'Phil Rosen',
    cast: ['Sidney Toler'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 64,
    backdropUrl: 'https://archive.org/services/img/charlie-chan-in-the-secret-service-restored-colorized-1944-mystery-imdb-score-6.2',
    source: { provider: 'archive', id: 'charlie-chan-in-the-secret-service-restored-colorized-1944-mystery-imdb-score-6.2' },
    featured: false,
  },
  {
    title: 'The Chinese Ring',
    slug: 'the-chinese-ring-1947',
    synopsis:
      'Uma princesa chinesa procura Charlie Chan em sua própria casa para pedir ajuda na compra de aviões de guerra para o país dela, mas é assassinada antes de revelar tudo, deixando Chan com uma lista de suspeitos dentro do próprio círculo social.',
    year: 1947,
    director: 'William Beaudine',
    cast: ['Roland Winters'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 68,
    backdropUrl: 'https://archive.org/services/img/the-chinese-ring-1947-dvd-mkv',
    source: { provider: 'archive', id: 'the-chinese-ring-1947-dvd-mkv' },
    featured: false,
  },
  {
    title: 'Dick Tracy',
    slug: 'dick-tracy-1945',
    synopsis:
      'Primeiro dos filmes B da RKO sobre o detetive dos quadrinhos: Tracy persegue um assassino desfigurado, apelidado de "Splitface", que está matando um a um os jurados que o condenaram.',
    year: 1945,
    director: 'William Berke',
    cast: ['Morgan Conway'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 61,
    backdropUrl: 'https://archive.org/services/img/DickTracy720p1937',
    source: { provider: 'archive', id: 'DickTracy720p1937' },
    featured: false,
  },
  {
    title: 'Dick Tracy vs. Cueball',
    slug: 'dick-tracy-vs-cueball-1946',
    synopsis:
      'Dick Tracy caça um estrangulador careca conhecido como "Cueball", que matou um contrabandista de diamantes e agora se esconde no submundo do crime enquanto tenta escoar a pedraria roubada.',
    year: 1946,
    director: 'Gordon M. Douglas',
    cast: ['Morgan Conway'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 62,
    backdropUrl: 'https://archive.org/services/img/DickTracyvsCueball',
    source: { provider: 'archive', id: 'DickTracyvsCueball' },
    featured: false,
  },
  {
    title: "Dick Tracy's Dilemma",
    slug: 'dick-tracys-dilemma-1947',
    synopsis:
      'Um assalto a um depósito de peles termina em assassinato, e Dick Tracy parte no encalço de um criminoso violento apelidado de "Steve, o Gancho" por causa da prótese que usa como arma.',
    year: 1947,
    director: 'John Rawlins',
    cast: ['Ralph Byrd'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 60,
    backdropUrl: 'https://archive.org/services/img/dick_tracys_dilemma',
    source: { provider: 'archive', id: 'dick_tracys_dilemma' },
    featured: false,
  },
  {
    title: 'Dick Tracy Meets Gruesome',
    slug: 'dick-tracy-meets-gruesome-1947',
    synopsis:
      'Um criminoso apelidado de "Gruesome" usa um gás experimental que paralisa temporariamente qualquer pessoa para assaltar um banco em plena luz do dia, forçando Tracy a correr contra o tempo antes do próximo golpe.',
    year: 1947,
    director: 'John Rawlins',
    cast: ['Ralph Byrd', 'Boris Karloff'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 65,
    backdropUrl: 'https://archive.org/services/img/Dick_Tracy_Meets_Gruesome_1947',
    source: { provider: 'archive', id: 'Dick_Tracy_Meets_Gruesome_1947' },
    featured: false,
  },
  {
    title: 'Alias Boston Blackie',
    slug: 'alias-boston-blackie-1942',
    synopsis:
      'Boston Blackie, o ex-ladrão que virou detetive amador, ajuda um presidiário fugitivo injustamente condenado a provar sua inocência antes que a polícia o alcance primeiro.',
    year: 1942,
    director: 'Lew Landers',
    cast: ['Chester Morris'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 67,
    backdropUrl: 'https://archive.org/services/img/alias-boston-blackie',
    source: { provider: 'archive', id: 'alias-boston-blackie' },
    featured: false,
  },
  {
    title: 'After Midnight with Boston Blackie',
    slug: 'after-midnight-with-boston-blackie-1943',
    synopsis:
      'Boston Blackie é confundido com um assassino de verdade depois que um golpe de rua dá errado, e precisa desvendar um esquema de falsificação de dinheiro para limpar seu nome.',
    year: 1943,
    director: 'Lew Landers',
    cast: ['Chester Morris'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 65,
    backdropUrl: 'https://archive.org/services/img/after-midnight-with-boston-blackie-1943',
    source: { provider: 'archive', id: 'after-midnight-with-boston-blackie-1943' },
    featured: false,
  },
  {
    title: 'The Return of the Whistler',
    slug: 'the-return-of-the-whistler-1948',
    synopsis:
      'Um noivo tem a noiva sequestrada às vésperas do casamento e passa a investigar sozinho seu desaparecimento, guiado — como em toda a série "The Whistler" — por um narrador onisciente que comenta o destino dos personagens.',
    year: 1948,
    director: 'D. Ross Lederman',
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 63,
    backdropUrl: 'https://archive.org/services/img/the-return-of-the-whistler-1948',
    source: { provider: 'archive', id: 'the-return-of-the-whistler-1948' },
    featured: false,
  },
  {
    title: 'The Mark of the Whistler',
    slug: 'the-mark-of-the-whistler-1944',
    synopsis:
      'Um homem sem dinheiro assume a identidade de outra pessoa para sacar uma conta bancária esquecida, sem imaginar que isso o coloca no meio de uma vingança planejada há anos.',
    year: 1944,
    director: 'William Castle',
    cast: ['Richard Dix'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 62,
    backdropUrl: 'https://archive.org/services/img/the-mark-of-the-whistler-1944_202507',
    source: { provider: 'archive', id: 'the-mark-of-the-whistler-1944_202507' },
    featured: false,
  },
  {
    title: 'Voice of the Whistler',
    slug: 'voice-of-the-whistler-1945',
    synopsis:
      'Um magnata solitário e doente contrata uma enfermeira para cuidar dele e acaba se casando com ela, mas o arranjo esconde segredos que ameaçam a vida de ambos.',
    year: 1945,
    director: 'William Castle',
    cast: ['Richard Dix'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 60,
    backdropUrl: 'https://archive.org/services/img/voice-of-the-whistler-1945',
    source: { provider: 'archive', id: 'voice-of-the-whistler-1945' },
    featured: false,
  },
  {
    title: 'The Power of the Whistler',
    slug: 'the-power-of-the-whistler-1945',
    synopsis:
      'Uma cartomante prevê que um homem amnésico encontrado na rua é perigoso, e a mulher que decide ajudá-lo a recuperar a memória corre contra o tempo para descobrir se a previsão vai se confirmar.',
    year: 1945,
    director: 'Lew Landers',
    cast: ['Richard Dix'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 67,
    backdropUrl: 'https://archive.org/services/img/the-power-of-the-whistler-1945',
    source: { provider: 'archive', id: 'the-power-of-the-whistler-1945' },
    featured: false,
  },
  {
    title: 'The Secret of the Whistler',
    slug: 'the-secret-of-the-whistler-1946',
    synopsis:
      'Um pintor endividado e casado com uma esposa rica e doente se apaixona por outra mulher, e quando a esposa morre em circunstâncias suspeitas, ele se torna o principal suspeito.',
    year: 1946,
    director: 'George Sherman',
    cast: ['Richard Dix'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 64,
    backdropUrl: 'https://archive.org/services/img/the-secret-of-the-whistle-.-1946',
    source: { provider: 'archive', id: 'the-secret-of-the-whistle-.-1946' },
    featured: false,
  },
  {
    title: 'The Bowery Boys Meet the Monsters',
    slug: 'the-bowery-boys-meet-the-monsters-1954',
    synopsis:
      'A turma da Bowery Boys herda uma mansão sinistra e descobre tarde demais que o porão esconde o laboratório de um cientista louco fazendo experiências para reanimar um cadáver.',
    year: 1954,
    director: 'Edward Bernds',
    cast: ['Leo Gorcey', 'Huntz Hall'],
    genres: ['Comédia', 'Terror', 'Clássico'],
    runtimeMinutes: 65,
    backdropUrl: 'https://archive.org/services/img/the-bowery-boys-meet-the-monsters-1954',
    source: { provider: 'archive', id: 'the-bowery-boys-meet-the-monsters-1954' },
    featured: false,
  },
  {
    title: 'East Side Kids',
    slug: 'east-side-kids-1940',
    synopsis:
      'O primeiro filme da série que deu origem aos Bowery Boys: um garoto da gangue de rua é usado como bode expiatório por um advogado corrupto, e o grupo precisa provar sua inocência antes que ele vá parar na cadeia.',
    year: 1940,
    director: 'Bob Hill',
    genres: ['Comédia', 'Drama', 'Clássico'],
    runtimeMinutes: 60,
    backdropUrl: 'https://archive.org/services/img/EastSideKids1940',
    source: { provider: 'archive', id: 'EastSideKids1940' },
    featured: false,
  },
  {
    title: 'Bowery Blitzkrieg',
    slug: 'bowery-blitzkrieg-1941',
    synopsis:
      'Um dos East Side Kids se envolve com um antigo comparsa que virou apostador ilegal e acaba levando a culpa por um crime que não cometeu, até o resto da gangue entrar em ação para limpar seu nome.',
    year: 1941,
    director: 'Wallace Fox',
    genres: ['Comédia', 'Drama', 'Clássico'],
    runtimeMinutes: 63,
    backdropUrl: 'https://archive.org/services/img/bowery_blitzkrieg',
    source: { provider: 'archive', id: 'bowery_blitzkrieg' },
    featured: false,
  },
  {
    title: "Neath Brooklyn Bridge",
    slug: 'neath-brooklyn-bridge-1942',
    synopsis:
      'A turma dos East Side Kids se mete com contrabandistas de imigrantes que operam sob a ponte do Brooklyn, misturando comédia pastelão com uma trama de crime organizado.',
    year: 1942,
    director: 'Wallace Fox',
    genres: ['Comédia', 'Clássico'],
    runtimeMinutes: 61,
    backdropUrl: 'https://archive.org/services/img/neath_brooklyn_bridge',
    source: { provider: 'archive', id: 'neath_brooklyn_bridge' },
    featured: false,
  },
  {
    title: 'Boys of the City',
    slug: 'boys-of-the-city-1940',
    synopsis:
      'Enviados ao campo para escapar da má influência da cidade, os East Side Kids passam a noite numa mansão isolada que esconde um assassinato, misturando comédia de sustos com investigação policial.',
    year: 1940,
    director: 'Joseph H. Lewis',
    genres: ['Comédia', 'Terror', 'Clássico'],
    runtimeMinutes: 62,
    backdropUrl: 'https://archive.org/services/img/boys_of_the_city',
    source: { provider: 'archive', id: 'boys_of_the_city' },
    featured: false,
  },
  {
    title: 'Misbehaving Husbands',
    slug: 'misbehaving-husbands-1940',
    synopsis:
      'Um marido enganado finge sua própria morte para flagrar a esposa e o amante, numa comédia de erros que rapidamente sai do controle.',
    year: 1940,
    director: 'William Beaudine',
    genres: ['Comédia', 'Clássico'],
    runtimeMinutes: 59,
    backdropUrl: 'https://archive.org/services/img/misbehaving_husbands',
    source: { provider: 'archive', id: 'misbehaving_husbands' },
    featured: false,
  },
];
