// Décima nona leva — segunda checagem de segurança jurídica sobre os 98
// candidatos que passaram na verificação técnica de duração do archive.org
// mas ficaram de fora de levas anteriores só por falta de tempo (motivo
// genérico em novos-filmes-encontrados.csv). Este arquivo reavalia cada um
// dos 98 quanto a risco jurídico real de não serem domínio público de
// verdade, usando o mesmo critério das levas anteriores: aceita poverty row
// (PRC, Monogram, Republic, Eagle-Lion, Grand National e equivalentes
// britânicos como a Twickenham/Julius Hagen), mudo pré-1929 (nesses casos,
// mesmo quando a obra é estrangeira e teria tido o copyright nos EUA restaurado
// pelo URAA/GATT de 1996, o prazo restaurado de 95 anos a partir da publicação
// já se esgotou antes de hoje), produção governamental/independente sem
// renovação documentada, e rejeita qualquer estúdio grande (Fox, WB, MGM,
// Paramount, Universal, RKO em produção própria, Columbia) e equivalentes
// estrangeiros com dono ativo até hoje (Gaumont British/Hitchcock, UFA depois
// de 2025 apenas, Gaumont/Franju, Korda quando o catálogo ainda é vigiado,
// Shaw Brothers/Celestial, Toho quando não há confirmação específica em
// contrário), além de exploitation/bootleg dos anos 1970 com proveniência de
// direitos incerta (kung-fu "Bruceploitation" e afins). Casos de dúvida real
// (não foi possível confirmar produtora/estúdio com confiança) foram
// descartados, não incluídos aqui. Duplicatas de filmes já presentes no
// catálogo (mesmo filme, outro identifier do archive.org) também foram
// descartadas, não incluídas aqui. Resultado: 50 aceitos de 98 candidatos
// (48 descartados: 16 por duplicata de filme já no catálogo sob outro
// identifier, os demais 32 por risco jurídico real ou dúvida — ver motivo
// atualizado de cada linha em novos-filmes-encontrados.csv). Sinopses desta
// leva são propositalmente genéricas (gênero + ano + "de domínio público"),
// sem descrever o enredo — pedido específico do usuário para agilizar esta
// leva.
module.exports = [
  {
    title: 'Bloody Pit of Horror',
    slug: 'bloody-pit-of-horror-1965',
    synopsis: 'Filme de terror italiano, produzido no ano 1965.',
    year: 1965,
    genres: ['Terror', 'Clássico'],
    runtimeMinutes: 82,
    backdropUrl: 'https://archive.org/services/img/BloodyPitOfHorror',
    source: { provider: 'archive', id: 'BloodyPitOfHorror' },
    featured: false,
  },
  {
    title: 'Last Woman on Earth',
    slug: 'last-woman-on-earth-1960',
    synopsis: 'Filme de ficção científica, produzido no ano 1960.',
    year: 1960,
    genres: ['Ficção Científica', 'Clássico'],
    runtimeMinutes: 72,
    backdropUrl: 'https://archive.org/services/img/last_woman_on_earth',
    source: { provider: 'archive', id: 'last_woman_on_earth' },
    featured: false,
  },
  {
    title: 'The Iron Mask',
    slug: 'the-iron-mask-1929',
    synopsis: 'Filme de aventura, produzido no ano 1929.',
    year: 1929,
    genres: ['Aventura', 'Clássico'],
    runtimeMinutes: 72,
    backdropUrl: 'https://archive.org/services/img/iron_mask',
    source: { provider: 'archive', id: 'iron_mask' },
    featured: false,
  },
  {
    title: 'The Saint Louis Bank Robbery',
    slug: 'the-st-louis-bank-robbery-1959',
    synopsis: 'Filme policial, produzido no ano 1959.',
    year: 1959,
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 89,
    backdropUrl: 'https://archive.org/services/img/Saint_Louis_Bank_Robbery',
    source: { provider: 'archive', id: 'Saint_Louis_Bank_Robbery' },
    featured: false,
  },
  {
    title: 'The Admiral Was a Lady',
    slug: 'the-admiral-was-a-lady-1950',
    synopsis: 'Comédia romântica, produzido no ano 1950.',
    year: 1950,
    genres: ['Comédia', 'Romance', 'Clássico'],
    runtimeMinutes: 87,
    backdropUrl: 'https://archive.org/services/img/the-admiral-was-a-lady-1950-dvd-mkv',
    source: { provider: 'archive', id: 'the-admiral-was-a-lady-1950-dvd-mkv' },
    featured: false,
  },
  {
    title: 'Inner Sanctum',
    slug: 'inner-sanctum-1948',
    synopsis: 'Filme de suspense, produzido no ano 1948.',
    year: 1948,
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 58,
    backdropUrl: 'https://archive.org/services/img/inner_sanctum',
    source: { provider: 'archive', id: 'inner_sanctum' },
    featured: false,
  },
  {
    title: 'Under California Stars',
    slug: 'under-california-stars-1948',
    synopsis: 'Faroeste, produzido no ano 1948.',
    year: 1948,
    genres: ['Faroeste', 'Clássico'],
    runtimeMinutes: 72,
    backdropUrl: 'https://archive.org/services/img/under_california_stars',
    source: { provider: 'archive', id: 'under_california_stars' },
    featured: false,
  },
  {
    title: 'Mr. Wong, Detective',
    slug: 'mr-wong-detective-1938',
    synopsis: 'Filme policial, produzido no ano 1938.',
    year: 1938,
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 69,
    backdropUrl: 'https://archive.org/services/img/wrongdetective4k',
    source: { provider: 'archive', id: 'wrongdetective4k' },
    featured: false,
  },
  {
    title: 'Affairs of Cappy Ricks',
    slug: 'affairs-of-cappy-ricks-1937',
    synopsis: 'Comédia de aventura, produzido no ano 1937.',
    year: 1937,
    genres: ['Comédia', 'Aventura', 'Clássico'],
    runtimeMinutes: 56,
    backdropUrl: 'https://archive.org/services/img/affairs-of-cappy-ricks-1937',
    source: { provider: 'archive', id: 'affairs-of-cappy-ricks-1937' },
    featured: false,
  },
  {
    title: 'The Bashful Bachelor',
    slug: 'the-bashful-bachelor-1942',
    synopsis: 'Comédia, produzido no ano 1942.',
    year: 1942,
    genres: ['Comédia', 'Clássico'],
    runtimeMinutes: 76,
    backdropUrl: 'https://archive.org/services/img/the_bashful_bachelor',
    source: { provider: 'archive', id: 'the_bashful_bachelor' },
    featured: false,
  },
  {
    title: 'The Last of the Mohicans',
    slug: 'the-last-of-the-mohicans-1936',
    synopsis: 'Filme de aventura, produzido no ano 1936.',
    year: 1936,
    genres: ['Aventura', 'Clássico'],
    runtimeMinutes: 91,
    backdropUrl: 'https://archive.org/services/img/last-of-the-mohicans-1936-colorized',
    source: { provider: 'archive', id: 'last-of-the-mohicans-1936-colorized' },
    featured: false,
  },
  {
    title: 'The Snow Creature',
    slug: 'the-snow-creature-1954',
    synopsis: 'Filme de terror e ficção científica, produzido no ano 1954.',
    year: 1954,
    genres: ['Terror', 'Ficção Científica', 'Clássico'],
    runtimeMinutes: 71,
    backdropUrl: 'https://archive.org/services/img/TheSnowCreature',
    source: { provider: 'archive', id: 'TheSnowCreature' },
    featured: false,
  },
  {
    title: 'The Mad Monster',
    slug: 'the-mad-monster-1942',
    synopsis: 'Filme de terror, produzido no ano 1942.',
    year: 1942,
    genres: ['Terror', 'Clássico'],
    runtimeMinutes: 77,
    backdropUrl: 'https://archive.org/services/img/mad_monster',
    source: { provider: 'archive', id: 'mad_monster' },
    featured: false,
  },
  {
    title: 'Cold Sweat',
    slug: 'cold-sweat-1970',
    synopsis: 'Filme de suspense e ação, produzido no ano 1970.',
    year: 1970,
    genres: ['Suspense', 'Ação', 'Clássico'],
    runtimeMinutes: 93,
    backdropUrl: 'https://archive.org/services/img/cold_sweat.avi',
    source: { provider: 'archive', id: 'cold_sweat.avi' },
    featured: false,
  },
  {
    title: 'End of the World',
    slug: 'end-of-the-world-1977',
    synopsis: 'Filme de ficção científica, produzido no ano 1977.',
    year: 1977,
    genres: ['Ficção Científica', 'Terror', 'Clássico'],
    runtimeMinutes: 86,
    backdropUrl: 'https://archive.org/services/img/EndoftheWorld',
    source: { provider: 'archive', id: 'EndoftheWorld' },
    featured: false,
  },
  {
    title: 'Indiscreet',
    slug: 'indiscreet-1931',
    synopsis: 'Comédia romântica, produzido no ano 1931.',
    year: 1931,
    genres: ['Comédia', 'Romance', 'Clássico'],
    runtimeMinutes: 75,
    backdropUrl: 'https://archive.org/services/img/Indiscreet',
    source: { provider: 'archive', id: 'Indiscreet' },
    featured: false,
  },
  {
    title: 'Pygmalion',
    slug: 'pygmalion-1938',
    synopsis: 'Comédia dramática, produzido no ano 1938.',
    year: 1938,
    genres: ['Comédia', 'Drama', 'Clássico'],
    runtimeMinutes: 95,
    backdropUrl: 'https://archive.org/services/img/Pygmalion',
    source: { provider: 'archive', id: 'Pygmalion' },
    featured: false,
  },
  {
    title: 'Scrooge',
    slug: 'scrooge-1935',
    synopsis: 'Drama, produzido no ano 1935.',
    year: 1935,
    genres: ['Drama', 'Clássico'],
    runtimeMinutes: 78,
    backdropUrl: 'https://archive.org/services/img/Scrooge_1935',
    source: { provider: 'archive', id: 'Scrooge_1935' },
    featured: false,
  },
  {
    title: 'Sex Madness',
    slug: 'sex-madness-1938',
    synopsis: 'Drama, produzido no ano 1938.',
    year: 1938,
    genres: ['Drama', 'Clássico'],
    runtimeMinutes: 52,
    backdropUrl: 'https://archive.org/services/img/sex_madness',
    source: { provider: 'archive', id: 'sex_madness' },
    featured: false,
  },
  {
    title: 'Strike',
    slug: 'strike-1925',
    synopsis: 'Filme mudo, produzido no ano 1925.',
    year: 1925,
    genres: ['Drama', 'Mudo', 'Clássico'],
    runtimeMinutes: 94,
    backdropUrl: 'https://archive.org/services/img/Strike_323',
    source: { provider: 'archive', id: 'Strike_323' },
    featured: false,
  },
  {
    title: 'The Blue Angel',
    slug: 'the-blue-angel-1930',
    synopsis: 'Drama, produzido no ano 1930.',
    year: 1930,
    genres: ['Drama', 'Clássico'],
    runtimeMinutes: 100,
    backdropUrl: 'https://archive.org/services/img/theblueangel1930',
    source: { provider: 'archive', id: 'theblueangel1930' },
    featured: false,
  },
  {
    title: 'The Contender',
    slug: 'the-contender-1944',
    synopsis: 'Filme de suspense, produzido no ano 1944.',
    year: 1944,
    genres: ['Suspense', 'Drama', 'Clássico'],
    runtimeMinutes: 62,
    backdropUrl: 'https://archive.org/services/img/the_contender_ipod',
    source: { provider: 'archive', id: 'the_contender_ipod' },
    featured: false,
  },
  {
    title: 'The Divorce of Lady X',
    slug: 'the-divorce-of-lady-x-1938',
    synopsis: 'Comédia romântica, produzido no ano 1938.',
    year: 1938,
    genres: ['Comédia', 'Romance', 'Clássico'],
    runtimeMinutes: 91,
    backdropUrl: 'https://archive.org/services/img/Lady_X',
    source: { provider: 'archive', id: 'Lady_X' },
    featured: false,
  },
  {
    title: 'The Painted Desert',
    slug: 'the-painted-desert-1931',
    synopsis: 'Faroeste, produzido no ano 1931.',
    year: 1931,
    genres: ['Faroeste', 'Clássico'],
    runtimeMinutes: 75,
    backdropUrl: 'https://archive.org/services/img/ThePaintedDesert1931ClarkGable',
    source: { provider: 'archive', id: 'ThePaintedDesert1931ClarkGable' },
    featured: false,
  },
  {
    title: 'The Phantom Fiend',
    slug: 'the-phantom-fiend-1932',
    synopsis: 'Filme de suspense e terror, produzido no ano 1932.',
    year: 1932,
    genres: ['Suspense', 'Terror', 'Clássico'],
    runtimeMinutes: 63,
    backdropUrl: 'https://archive.org/services/img/ThePhantomFiend',
    source: { provider: 'archive', id: 'ThePhantomFiend' },
    featured: false,
  },
  {
    title: 'The Scarlet Pimpernel',
    slug: 'the-scarlet-pimpernel-1934',
    synopsis: 'Filme de aventura, produzido no ano 1934.',
    year: 1934,
    genres: ['Aventura', 'Clássico'],
    runtimeMinutes: 93,
    backdropUrl: 'https://archive.org/services/img/TheScarletPimpernel',
    source: { provider: 'archive', id: 'TheScarletPimpernel' },
    featured: false,
  },
  {
    title: 'The Taming of the Shrew',
    slug: 'the-taming-of-the-shrew-1929',
    synopsis: 'Comédia romântica, produzido no ano 1929.',
    year: 1929,
    genres: ['Comédia', 'Romance', 'Clássico'],
    runtimeMinutes: 66,
    backdropUrl: 'https://archive.org/services/img/TheTamingOfTheShrew',
    source: { provider: 'archive', id: 'TheTamingOfTheShrew' },
    featured: false,
  },
  {
    title: 'The Wild Ride',
    slug: 'the-wild-ride-1960',
    synopsis: 'Filme de suspense, produzido no ano 1960.',
    year: 1960,
    genres: ['Suspense', 'Drama', 'Clássico'],
    runtimeMinutes: 59,
    backdropUrl: 'https://archive.org/services/img/The-Wild-Ride',
    source: { provider: 'archive', id: 'The-Wild-Ride' },
    featured: false,
  },
  {
    title: 'The Young Lovers',
    slug: 'the-young-lovers-1949',
    synopsis: 'Drama, produzido no ano 1949.',
    year: 1949,
    genres: ['Drama', 'Clássico'],
    runtimeMinutes: 81,
    backdropUrl: 'https://archive.org/services/img/TheYoungLovers',
    source: { provider: 'archive', id: 'TheYoungLovers' },
    featured: false,
  },
  {
    title: 'Virus',
    slug: 'virus-1980',
    synopsis: 'Filme de ficção científica, produzido no ano 1980.',
    year: 1980,
    genres: ['Ficção Científica', 'Clássico'],
    runtimeMinutes: 103,
    backdropUrl: 'https://archive.org/services/img/cco_virus',
    source: { provider: 'archive', id: 'cco_virus' },
    featured: false,
  },
  {
    title: 'Voyage to the Planet of Prehistoric Women',
    slug: 'voyage-to-the-planet-of-prehistoric-women-1968',
    synopsis: 'Filme de ficção científica, produzido no ano 1968.',
    year: 1968,
    genres: ['Ficção Científica', 'Clássico'],
    runtimeMinutes: 80,
    backdropUrl: 'https://archive.org/services/img/VoyagetothePlanetofPrehistoricWomen',
    source: { provider: 'archive', id: 'VoyagetothePlanetofPrehistoricWomen' },
    featured: false,
  },
  {
    title: 'Dick Tracy (1937)',
    slug: 'dick-tracy-1937-seriado',
    synopsis: 'Seriado de suspense e aventura, produzido no ano 1937.',
    year: 1937,
    genres: ['Suspense', 'Aventura', 'Clássico'],
    runtimeMinutes: 276,
    backdropUrl: 'https://archive.org/services/img/PhotosbyHaroldDickTracyAll15ChaptersCombined',
    source: { provider: 'archive', id: 'PhotosbyHaroldDickTracyAll15ChaptersCombined' },
    featured: false,
  },
  {
    title: 'Port of New York',
    slug: 'port-of-new-york-1949',
    synopsis: 'Filme de suspense, produzido no ano 1949.',
    year: 1949,
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 81,
    backdropUrl: 'https://archive.org/services/img/Port_of_New_York',
    source: { provider: 'archive', id: 'Port_of_New_York' },
    featured: false,
  },
  {
    title: 'Great Guy',
    slug: 'great-guy-1936',
    synopsis: 'Filme de suspense, produzido no ano 1936.',
    year: 1936,
    genres: ['Suspense', 'Drama', 'Clássico'],
    runtimeMinutes: 66,
    backdropUrl: 'https://archive.org/services/img/Great_Guy.avi',
    source: { provider: 'archive', id: 'Great_Guy.avi' },
    featured: false,
  },
  {
    title: 'Guest in the House',
    slug: 'guest-in-the-house-1944',
    synopsis: 'Drama, produzido no ano 1944.',
    year: 1944,
    genres: ['Drama', 'Suspense', 'Clássico'],
    runtimeMinutes: 97,
    backdropUrl: 'https://archive.org/services/img/GuestInTheHouse1944',
    source: { provider: 'archive', id: 'GuestInTheHouse1944' },
    featured: false,
  },
  {
    title: 'Horror Express',
    slug: 'horror-express-1972',
    synopsis: 'Filme de terror e ficção científica, produzido no ano 1972.',
    year: 1972,
    genres: ['Terror', 'Ficção Científica', 'Clássico'],
    runtimeMinutes: 87,
    backdropUrl: 'https://archive.org/services/img/horror_express_ipod',
    source: { provider: 'archive', id: 'horror_express_ipod' },
    featured: false,
  },
  {
    title: 'Shed No Tears',
    slug: 'shed-no-tears-1948',
    synopsis: 'Filme de suspense, produzido no ano 1948.',
    year: 1948,
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 69,
    backdropUrl: 'https://archive.org/services/img/Shed_No_Tears_1948',
    source: { provider: 'archive', id: 'Shed_No_Tears_1948' },
    featured: false,
  },
  {
    title: 'Silent Night, Bloody Night',
    slug: 'silent-night-bloody-night-1972',
    synopsis: 'Filme de terror, produzido no ano 1972.',
    year: 1972,
    genres: ['Terror', 'Clássico'],
    runtimeMinutes: 85,
    backdropUrl: 'https://archive.org/services/img/SilentNightBloodyNight',
    source: { provider: 'archive', id: 'SilentNightBloodyNight' },
    featured: false,
  },
  {
    title: 'Swamp Women',
    slug: 'swamp-women-1955',
    synopsis: 'Filme de aventura, produzido no ano 1955.',
    year: 1955,
    genres: ['Aventura', 'Suspense', 'Clássico'],
    runtimeMinutes: 69,
    backdropUrl: 'https://archive.org/services/img/RC_SwampWomen',
    source: { provider: 'archive', id: 'RC_SwampWomen' },
    featured: false,
  },
  {
    title: 'The Driller Killer',
    slug: 'the-driller-killer-1979',
    synopsis: 'Filme de terror, produzido no ano 1979.',
    year: 1979,
    genres: ['Terror', 'Clássico'],
    runtimeMinutes: 92,
    backdropUrl: 'https://archive.org/services/img/DrillerKillerUncut1979',
    source: { provider: 'archive', id: 'DrillerKillerUncut1979' },
    featured: false,
  },
  {
    title: 'The Hoodlum',
    slug: 'the-hoodlum-1951',
    synopsis: 'Filme de suspense, produzido no ano 1951.',
    year: 1951,
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 62,
    backdropUrl: 'https://archive.org/services/img/The_Hoodlum',
    source: { provider: 'archive', id: 'The_Hoodlum' },
    featured: false,
  },
  {
    title: 'Black Fist',
    slug: 'black-fist-1975',
    synopsis: 'Filme de ação, produzido no ano 1975.',
    year: 1975,
    genres: ['Ação', 'Suspense', 'Clássico'],
    runtimeMinutes: 94,
    backdropUrl: 'https://archive.org/services/img/BlackFist',
    source: { provider: 'archive', id: 'BlackFist' },
    featured: false,
  },
  {
    title: 'Frontier Horizon',
    slug: 'frontier-horizon-1939',
    synopsis: 'Faroeste, produzido no ano 1939.',
    year: 1939,
    genres: ['Faroeste', 'Clássico'],
    runtimeMinutes: 55,
    backdropUrl: 'https://archive.org/services/img/FrontierHorizon',
    source: { provider: 'archive', id: 'FrontierHorizon' },
    featured: false,
  },
  {
    title: 'Gone with the West',
    slug: 'gone-with-the-west-1975',
    synopsis: 'Faroeste, produzido no ano 1975.',
    year: 1975,
    genres: ['Faroeste', 'Clássico'],
    runtimeMinutes: 91,
    backdropUrl: 'https://archive.org/services/img/GonewiththeWest',
    source: { provider: 'archive', id: 'GonewiththeWest' },
    featured: false,
  },
  {
    title: 'Paradise Canyon',
    slug: 'paradise-canyon-1935',
    synopsis: 'Faroeste, produzido no ano 1935.',
    year: 1935,
    genres: ['Faroeste', 'Clássico'],
    runtimeMinutes: 53,
    backdropUrl: 'https://archive.org/services/img/ParadiseCanyon',
    source: { provider: 'archive', id: 'ParadiseCanyon' },
    featured: false,
  },
  {
    title: 'Song of Arizona',
    slug: 'song-of-arizona-1946',
    synopsis: 'Faroeste, produzido no ano 1946.',
    year: 1946,
    genres: ['Faroeste', 'Clássico'],
    runtimeMinutes: 53,
    backdropUrl: 'https://archive.org/services/img/SongOfArizona',
    source: { provider: 'archive', id: 'SongOfArizona' },
    featured: false,
  },
  {
    title: 'The Lawless Frontier',
    slug: 'the-lawless-frontier-1934',
    synopsis: 'Faroeste, produzido no ano 1934.',
    year: 1934,
    genres: ['Faroeste', 'Clássico'],
    runtimeMinutes: 50,
    backdropUrl: 'https://archive.org/services/img/TheLawlessFontier',
    source: { provider: 'archive', id: 'TheLawlessFontier' },
    featured: false,
  },
  {
    title: 'The San Antonio Kid',
    slug: 'the-san-antonio-kid-1944',
    synopsis: 'Faroeste, produzido no ano 1944.',
    year: 1944,
    genres: ['Faroeste', 'Clássico'],
    runtimeMinutes: 53,
    backdropUrl: 'https://archive.org/services/img/TheSanAntonioKid-BillElliott1944',
    source: { provider: 'archive', id: 'TheSanAntonioKid-BillElliott1944' },
    featured: false,
  },
  {
    title: 'War of the Wildcats',
    slug: 'war-of-the-wildcats-1943',
    synopsis: 'Faroeste, produzido no ano 1943.',
    year: 1943,
    genres: ['Faroeste', 'Drama', 'Clássico'],
    runtimeMinutes: 98,
    backdropUrl: 'https://archive.org/services/img/WarOfTheWildcats-JohnWayne1943',
    source: { provider: 'archive', id: 'WarOfTheWildcats-JohnWayne1943' },
    featured: false,
  },
  {
    title: 'The Last Laugh',
    slug: 'the-last-laugh-1924',
    synopsis: 'Drama mudo alemão, produzido no ano 1924.',
    year: 1924,
    genres: ['Drama', 'Mudo', 'Clássico'],
    runtimeMinutes: 51,
    backdropUrl: 'https://archive.org/services/img/Der_letzte_Mann',
    source: { provider: 'archive', id: 'Der_letzte_Mann' },
    featured: false,
  },
];
