// Décima sétima leva — curtas de animação em domínio público (Betty Boop e
// Superman da Fleischer/Famous Studios para a Paramount, Felix the Cat,
// Popeye, Little Lulu, além de um punhado de Looney Tunes especificamente
// documentados como domínio público por falha no aviso de copyright, e
// alguns curtas avulsos de outros estúdios pequenos). Complementa
// bulkAnimations.js e bulkMovies12.js. Encontrados via archivewatch.org.
// Categoria já usada extensivamente nas levas anteriores: cartoons da
// Fleischer/Famous Studios pré-1950 são um caso muito bem documentado de
// não-renovação de copyright pela Paramount. source.id verificado
// manualmente na API do archive.org (duração real do curta). Sinopse
// escrita em português a partir dos fatos de cada curta, sem reproduzir
// texto de terceiros.
module.exports = [
  {
    title: 'Poor Cinderella',
    slug: 'poor-cinderella-1934',
    synopsis:
      'Versão musical do conto clássico estrelada por Betty Boop, a única curta-metragem da Fleischer feita em cores nos anos 1930: a garota maltratada pela madrasta ganha um vestido mágico de sua fada madrinha para ir ao baile do príncipe.',
    year: 1934,
    genres: ['Animação', 'Comédia', 'Clássico'],
    runtimeMinutes: 11,
    backdropUrl: 'https://archive.org/services/img/Betty_Boop_Poor_Cinderella_1934',
    source: { provider: 'archive', id: 'Betty_Boop_Poor_Cinderella_1934' },
    featured: false,
  },
  {
    title: 'A Language All My Own',
    slug: 'a-language-all-my-own-1935',
    synopsis:
      'Betty Boop parte para o Japão em turnê e precisa se virar apesar da barreira do idioma, numa curta-metragem cheia de números musicais e piadas visuais sobre o choque cultural.',
    year: 1935,
    genres: ['Animação', 'Comédia', 'Clássico'],
    runtimeMinutes: 6,
    backdropUrl: 'https://archive.org/services/img/Betty_Boop_a_Language_All_My_Own_1935',
    source: { provider: 'archive', id: 'Betty_Boop_a_Language_All_My_Own_1935' },
    featured: false,
  },
  {
    title: 'Judge for a Day',
    slug: 'judge-for-a-day-1935',
    synopsis:
      'Betty Boop sonha em ser juíza por um dia e precisa lidar com uma série de casos cada vez mais absurdos no tribunal, distribuindo sentenças tão estranhas quanto os crimes julgados.',
    year: 1935,
    genres: ['Animação', 'Comédia', 'Clássico'],
    runtimeMinutes: 8,
    backdropUrl: 'https://archive.org/services/img/Betty_Boop_Judge_For_a_Day_1935',
    source: { provider: 'archive', id: 'Betty_Boop_Judge_For_a_Day_1935' },
    featured: false,
  },
  {
    title: 'Betty Boop and Little Jimmy',
    slug: 'betty-boop-and-little-jimmy-1936',
    synopsis:
      'Baseada na tira de jornal "Little Jimmy", a curta acompanha o garoto travesso e sua turma numa aventura cheia de confusão, com Betty Boop numa participação especial ao lado do protagonista.',
    year: 1936,
    genres: ['Animação', 'Comédia', 'Clássico'],
    runtimeMinutes: 6,
    backdropUrl: 'https://archive.org/services/img/Betty_Boop_and_Little_Jimmy_1936',
    source: { provider: 'archive', id: 'Betty_Boop_and_Little_Jimmy_1936' },
    featured: false,
  },
  {
    title: 'The Impractical Joker',
    slug: 'the-impractical-joker-1937',
    synopsis:
      'Um pretendente de Betty Boop, obcecado por pregar peças, tenta impressioná-la com uma série de brincadeiras que dão terrivelmente errado, colocando o próprio romance em risco.',
    year: 1937,
    genres: ['Animação', 'Comédia', 'Clássico'],
    runtimeMinutes: 6,
    backdropUrl: 'https://archive.org/services/img/bb_the_impractical_joker',
    source: { provider: 'archive', id: 'bb_the_impractical_joker' },
    featured: false,
  },
  {
    title: 'Whoops! I\'m a Cowboy',
    slug: 'whoops-im-a-cowboy-1937',
    synopsis:
      'Betty Boop se aventura por um rancho do velho oeste, entre gado arisco, um cavalo teimoso e pretendentes caubóis, numa sátira musical dos clichês do gênero faroeste.',
    year: 1937,
    genres: ['Animação', 'Comédia', 'Clássico'],
    runtimeMinutes: 6,
    backdropUrl: 'https://archive.org/services/img/Betty_Boop_Whoops_Im_a_Cowboy_1937',
    source: { provider: 'archive', id: 'Betty_Boop_Whoops_Im_a_Cowboy_1937' },
    featured: false,
  },
  {
    title: 'Baby Be Good',
    slug: 'baby-be-good-1935',
    synopsis:
      'Betty Boop cuida de um bebê travesso que se recusa a dormir, numa perseguição noturna cheia de gags físicos pela casa enquanto ela tenta, sem sucesso, colocá-lo no berço.',
    year: 1935,
    genres: ['Animação', 'Comédia', 'Clássico'],
    runtimeMinutes: 8,
    backdropUrl: 'https://archive.org/services/img/Betty_Boop_Baby_Be_Good_1935',
    source: { provider: 'archive', id: 'Betty_Boop_Baby_Be_Good_1935' },
    featured: false,
  },
  {
    title: 'More Pep',
    slug: 'more-pep-1936',
    synopsis:
      'Betty Boop tenta se manter em forma seguindo um regime de exercícios cada vez mais elaborado, numa curta que zomba da moda dos programas de ginástica da época.',
    year: 1936,
    genres: ['Animação', 'Comédia', 'Clássico'],
    runtimeMinutes: 6,
    backdropUrl: 'https://archive.org/services/img/Betty_Boop_More_Pep_1936',
    source: { provider: 'archive', id: 'Betty_Boop_More_Pep_1936' },
    featured: false,
  },
  {
    title: 'The Candid Candidate',
    slug: 'the-candid-candidate-1937',
    synopsis:
      'Betty Boop concorre a um cargo público e precisa lidar com adversários políticos desonestos, numa sátira animada sobre promessas de campanha e manipulação eleitoral.',
    year: 1937,
    genres: ['Animação', 'Comédia', 'Clássico'],
    runtimeMinutes: 6,
    backdropUrl: 'https://archive.org/services/img/Betty_Boop_The_Candid_Candidate_1937_944',
    source: { provider: 'archive', id: 'Betty_Boop_The_Candid_Candidate_1937_944' },
    featured: false,
  },
  {
    title: 'Parade of the Wooden Soldiers',
    slug: 'parade-of-the-wooden-soldiers-1933',
    synopsis:
      'Numa loja de brinquedos que ganha vida à noite, soldadinhos de madeira desfilam e enfrentam um vilão que ameaça sequestrar Betty Boop, numa das curtas mais lembradas da série pelo visual natalino.',
    year: 1933,
    genres: ['Animação', 'Comédia', 'Clássico'],
    runtimeMinutes: 8,
    backdropUrl: 'https://archive.org/services/img/bb_parade_of_the_wooden_soldiers',
    source: { provider: 'archive', id: 'bb_parade_of_the_wooden_soldiers' },
    featured: false,
  },
  {
    title: 'The Mechanical Monsters',
    slug: 'the-mechanical-monsters-1941',
    synopsis:
      'Um cientista louco constrói um exército de robôs gigantes para roubar ouro e joias pela cidade, e cabe a Superman detê-los antes que Lois Lane, presa dentro do covil secreto, seja descoberta e eliminada.',
    year: 1941,
    genres: ['Animação', 'Ficção Científica', 'Clássico'],
    runtimeMinutes: 10,
    backdropUrl: 'https://archive.org/services/img/superman_the_mechanical_monsters',
    source: { provider: 'archive', id: 'superman_the_mechanical_monsters' },
    featured: false,
  },
  {
    title: 'The Arctic Giant',
    slug: 'the-arctic-giant-1942',
    synopsis:
      'Um dinossauro pré-histórico congelado no gelo ártico é descongelado por acidente durante o transporte para um museu e passa a aterrorizar a cidade — só Superman é capaz de conter a criatura.',
    year: 1942,
    genres: ['Animação', 'Ficção Científica', 'Clássico'],
    runtimeMinutes: 9,
    backdropUrl: 'https://archive.org/services/img/superman_arctic_giant',
    source: { provider: 'archive', id: 'superman_arctic_giant' },
    featured: false,
  },
  {
    title: 'Billion Dollar Limited',
    slug: 'billion-dollar-limited-1942',
    synopsis:
      'Uma quadrilha de assaltantes sequestra um trem carregado com um bilhão de dólares em ouro, e Superman precisa impedir o roubo antes que o comboio descarrile propositalmente.',
    year: 1942,
    genres: ['Animação', 'Ficção Científica', 'Clássico'],
    runtimeMinutes: 8,
    backdropUrl: 'https://archive.org/services/img/superman_billion_dollar_limited',
    source: { provider: 'archive', id: 'superman_billion_dollar_limited' },
    featured: false,
  },
  {
    title: 'The Magnetic Telescope',
    slug: 'the-magnetic-telescope-1942',
    synopsis:
      'Um astrônomo obcecado constrói um telescópio magnético gigante capaz de atrair meteoros à Terra, ignorando os riscos de destruição em massa — e cabe a Superman impedir a catástrofe.',
    year: 1942,
    genres: ['Animação', 'Ficção Científica', 'Clássico'],
    runtimeMinutes: 8,
    backdropUrl: 'https://archive.org/services/img/magnetic_telescope',
    source: { provider: 'archive', id: 'magnetic_telescope' },
    featured: false,
  },
  {
    title: 'Terror on the Midway',
    slug: 'terror-on-the-midway-1942',
    synopsis:
      'Um circo itinerante liberta acidentalmente um gorila gigante que cresce fora de controle após ser exposto a um soro experimental, deixando um rastro de destruição até Superman intervir.',
    year: 1942,
    genres: ['Animação', 'Ficção Científica', 'Clássico'],
    runtimeMinutes: 8,
    backdropUrl: 'https://archive.org/services/img/superman_terror_on_the_midway',
    source: { provider: 'archive', id: 'superman_terror_on_the_midway' },
    featured: false,
  },
  {
    title: 'Jungle Drums',
    slug: 'jungle-drums-1943',
    synopsis:
      'Durante a Segunda Guerra, agentes do Eixo tentam usar uma emissora de rádio escondida na selva para transmitir propaganda e coordenar sabotagens — um alvo que Superman precisa neutralizar.',
    year: 1943,
    genres: ['Animação', 'Ficção Científica', 'Clássico'],
    runtimeMinutes: 8,
    backdropUrl: 'https://archive.org/services/img/superman_jungle_drums',
    source: { provider: 'archive', id: 'superman_jungle_drums' },
    featured: false,
  },
  {
    title: 'The Underground World',
    slug: 'the-underground-world-1943',
    synopsis:
      'Uma expedição arqueológica desperta uma civilização subterrânea perdida que planeja invadir a superfície, e Superman precisa impedir a guerra entre os dois mundos.',
    year: 1943,
    genres: ['Animação', 'Ficção Científica', 'Clássico'],
    runtimeMinutes: 8,
    backdropUrl: 'https://archive.org/services/img/superman_underground_world',
    source: { provider: 'archive', id: 'superman_underground_world' },
    featured: false,
  },
  {
    title: 'The Volcano',
    slug: 'the-volcano-1942',
    synopsis:
      'A erupção repentina de um vulcão numa ilha do Pacífico ameaça soterrar uma vila inteira, e Superman precisa correr contra o tempo para evacuar os moradores e conter a lava.',
    year: 1942,
    genres: ['Animação', 'Ficção Científica', 'Clássico'],
    runtimeMinutes: 8,
    backdropUrl: 'https://archive.org/services/img/superman_the_volcano',
    source: { provider: 'archive', id: 'superman_the_volcano' },
    featured: false,
  },
  {
    title: 'Stamp Day for Superman',
    slug: 'stamp-day-for-superman-1954',
    synopsis:
      'Curta de ação real (não animado) produzido para incentivar crianças americanas a comprar selos de poupança escolar: Superman ajuda a impedir um bando de assaltantes de banco enquanto reforça a mensagem sobre o hábito de poupar.',
    year: 1954,
    cast: ['George Reeves'],
    genres: ['Ficção Científica', 'Clássico'],
    runtimeMinutes: 18,
    backdropUrl: 'https://archive.org/services/img/StampDayForSUPERMAN',
    source: { provider: 'archive', id: 'StampDayForSUPERMAN' },
    featured: false,
  },
  {
    title: 'Felix the Cat in Neptune Nonsense',
    slug: 'felix-the-cat-in-neptune-nonsense-1936',
    synopsis:
      'Felix cai no oceano e vai parar no reino submarino do Rei Netuno, onde precisa escapar de criaturas marinhas hostis usando sua costumeira criatividade com o próprio rabo.',
    year: 1936,
    genres: ['Animação', 'Comédia', 'Clássico'],
    runtimeMinutes: 7,
    backdropUrl: 'https://archive.org/services/img/Felix_NeptuneNonsense',
    source: { provider: 'archive', id: 'Felix_NeptuneNonsense' },
    featured: false,
  },
  {
    title: 'Felix the Cat in Two-Lip Time',
    slug: 'felix-the-cat-in-two-lip-time-1926',
    synopsis:
      'Felix viaja até a Holanda dos moinhos de vento e das tulipas, onde se envolve numa disputa cômica ao tentar ajudar um casal de apaixonados separado por um pai rabugento.',
    year: 1926,
    genres: ['Animação', 'Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 10,
    backdropUrl: 'https://archive.org/services/img/Felix_TwoLipTime_NoAudio',
    source: { provider: 'archive', id: 'Felix_TwoLipTime_NoAudio' },
    featured: false,
  },
  {
    title: 'Felix the Cat in April Maze',
    slug: 'felix-the-cat-in-april-maze-1930',
    synopsis:
      'Numa sucessão de trapalhadas de Dia da Mentira, Felix se torna alvo e autor de pegadinhas cada vez mais elaboradas pela vizinhança, com seu característico humor visual de transformações improvisadas.',
    year: 1930,
    genres: ['Animação', 'Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 10,
    backdropUrl: 'https://archive.org/services/img/Felix_AprilMaze_NoAudio',
    source: { provider: 'archive', id: 'Felix_AprilMaze_NoAudio' },
    featured: false,
  },
  {
    title: 'Felix: All Puzzled',
    slug: 'felix-all-puzzled-1924',
    synopsis:
      'Felix se vê às voltas com um quebra-cabeça literal que ganha vida própria, transformando a resolução do jogo numa perseguição cheia de peças fugitivas e soluções inusitadas.',
    year: 1924,
    genres: ['Animação', 'Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 3,
    backdropUrl: 'https://archive.org/services/img/Felix_AllPuzzled_NoAudio',
    source: { provider: 'archive', id: 'Felix_AllPuzzled_NoAudio' },
    featured: false,
  },
  {
    title: 'Felix Finds Out',
    slug: 'felix-finds-out-1924',
    synopsis:
      'Curioso demais para o próprio bem, Felix investiga um mistério da vizinhança e acaba se metendo numa série de armadilhas cômicas antes de finalmente descobrir a verdade.',
    year: 1924,
    genres: ['Animação', 'Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 11,
    backdropUrl: 'https://archive.org/services/img/Felix_FindsOut_NoAudio',
    source: { provider: 'archive', id: 'Felix_FindsOut_NoAudio' },
    featured: false,
  },
  {
    title: 'Felix Gets the Can',
    slug: 'felix-gets-the-can-1924',
    synopsis:
      'Felix é despedido do emprego e precisa usar toda sua esperteza característica pra conseguir comida e abrigo, numa sequência de gags sobre sobrevivência nas ruas.',
    year: 1924,
    genres: ['Animação', 'Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 10,
    backdropUrl: 'https://archive.org/services/img/Felix_GetstheCan_NoAudio',
    source: { provider: 'archive', id: 'Felix_GetstheCan_NoAudio' },
    featured: false,
  },
  {
    title: 'Popeye: Out to Punch',
    slug: 'popeye-out-to-punch-1956',
    synopsis:
      'Bluto arma um esquema para afastar Popeye do ringue de boxe e ficar com a bolsa do combate, mas subestima o efeito de uma lata de espinafre no adversário.',
    year: 1956,
    genres: ['Animação', 'Comédia', 'Clássico'],
    runtimeMinutes: 6,
    backdropUrl: 'https://archive.org/services/img/Popeye_Out_of_the_Punch_1956',
    source: { provider: 'archive', id: 'Popeye_Out_of_the_Punch_1956' },
    featured: false,
  },
  {
    title: 'Gabby Goes Fishing',
    slug: 'gabby-goes-fishing-1941',
    synopsis:
      'O pequeno e barbudo Gabby, personagem derivado de "As Viagens de Gulliver" da Fleischer, tenta pescar em paz, mas é atrapalhado por um peixe teimoso que se recusa a fisgar do jeito esperado.',
    year: 1941,
    genres: ['Animação', 'Comédia', 'Clássico'],
    runtimeMinutes: 7,
    backdropUrl: 'https://archive.org/services/img/Gabby_Goes_Fishing_1941',
    source: { provider: 'archive', id: 'Gabby_Goes_Fishing_1941' },
    featured: false,
  },
  {
    title: 'Little Lulu: Bargain Counter Attack',
    slug: 'little-lulu-bargain-counter-attack-1946',
    synopsis:
      'A pequena Lulu enfrenta o caos de uma liquidação de loja de departamentos, onde a multidão de compradoras é tão implacável quanto qualquer vilão de desenho animado.',
    year: 1946,
    genres: ['Animação', 'Comédia', 'Clássico'],
    runtimeMinutes: 7,
    backdropUrl: 'https://archive.org/services/img/little_lulu_bargain_counter_attack',
    source: { provider: 'archive', id: 'little_lulu_bargain_counter_attack' },
    featured: false,
  },
  {
    title: 'Little Lulu: Bored of Education',
    slug: 'little-lulu-bored-of-education-1946',
    synopsis:
      'Entediada nas aulas, Lulu deixa a imaginação viajar para fantasias cada vez mais elaboradas, transformando a rotina escolar chata numa sucessão de aventuras absurdas.',
    year: 1946,
    genres: ['Animação', 'Comédia', 'Clássico'],
    runtimeMinutes: 7,
    backdropUrl: 'https://archive.org/services/img/LLBoredOfEducation',
    source: { provider: 'archive', id: 'LLBoredOfEducation' },
    featured: false,
  },
  {
    title: 'Little Lulu: Cad and Caddy',
    slug: 'little-lulu-cad-and-caddy-1947',
    synopsis:
      'Lulu trabalha como caddie num campo de golfe e precisa lidar com um jogador arrogante e de mau perder, cujas tacadas desastradas colocam todo mundo em perigo.',
    year: 1947,
    genres: ['Animação', 'Comédia', 'Clássico'],
    runtimeMinutes: 8,
    backdropUrl: 'https://archive.org/services/img/Little_Lulu_Cad_And_Caddy_1947',
    source: { provider: 'archive', id: 'Little_Lulu_Cad_And_Caddy_1947' },
    featured: false,
  },
  {
    title: 'Tom and Jerry: The Tuba Tooter',
    slug: 'tom-and-jerry-the-tuba-tooter-1932',
    synopsis:
      'A dupla desajeitada Tom e Jerry (os personagens humanos da Van Beuren, anteriores ao gato e rato da MGM) tenta ganhar dinheiro tocando tuba na rua, com resultados sonoramente catastróficos.',
    year: 1932,
    genres: ['Animação', 'Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 7,
    backdropUrl: 'https://archive.org/services/img/The_Tuba_Tooter_1932',
    source: { provider: 'archive', id: 'The_Tuba_Tooter_1932' },
    featured: false,
  },
  {
    title: 'Tom and Jerry: Redskin Blues',
    slug: 'tom-and-jerry-redskin-blues-1932',
    synopsis:
      'A dupla Tom e Jerry da Van Beuren embarca numa aventura pelo velho oeste, cruzando caminho com uma tribo nativa numa sequência de mal-entendidos e perseguições típicas do estúdio.',
    year: 1932,
    genres: ['Animação', 'Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 6,
    backdropUrl: 'https://archive.org/services/img/Redskin_Blues_1932',
    source: { provider: 'archive', id: 'Redskin_Blues_1932' },
    featured: false,
  },
  {
    title: 'The Cobweb Hotel',
    slug: 'the-cobweb-hotel-1936',
    synopsis:
      'Uma aranha disfarça sua teia de uma hospedaria acolhedora para atrair moscas incautas, até que uma delas percebe a armadilha e organiza a fuga de todos os "hóspedes" capturados.',
    year: 1936,
    genres: ['Animação', 'Clássico'],
    runtimeMinutes: 8,
    backdropUrl: 'https://archive.org/services/img/the_cobweb_hotel',
    source: { provider: 'archive', id: 'the_cobweb_hotel' },
    featured: false,
  },
  {
    title: 'Somewhere in Dreamland',
    slug: 'somewhere-in-dreamland-1935',
    synopsis:
      'Duas crianças pobres adormecem sonhando com fartura e brinquedos, e o sonho as transporta para um mundo mágico de doces e maravilhas — um contraste comovente com a realidade que as espera ao acordar.',
    year: 1935,
    genres: ['Animação', 'Clássico'],
    runtimeMinutes: 9,
    backdropUrl: 'https://archive.org/services/img/somewhere-in-dreamland-1935',
    source: { provider: 'archive', id: 'somewhere-in-dreamland-1935' },
    featured: false,
  },
  {
    title: 'Rudolph the Red-Nosed Reindeer',
    slug: 'rudolph-the-red-nosed-reindeer-1948',
    synopsis:
      'Curta-metragem animado que trouxe ao cinema a canção natalina sobre a rena de nariz vermelho zombada pelas outras, até que Papai Noel reconhece seu valor numa noite de neblina — anterior ao especial de TV que popularizou o personagem décadas depois.',
    year: 1948,
    director: 'Max Fleischer',
    genres: ['Animação', 'Clássico'],
    runtimeMinutes: 8,
    backdropUrl: 'https://archive.org/services/img/RudolphTheRed-nosedReindeer1948',
    source: { provider: 'archive', id: 'RudolphTheRed-nosedReindeer1948' },
    featured: false,
  },
  {
    title: 'The Dover Boys at Pimento University',
    slug: 'the-dover-boys-at-pimento-university-1942',
    synopsis:
      'Paródia dos seriados de aventura juvenil dos anos 1900: três irmãos exemplares precisam resgatar a namorada de um deles das garras de um vilão de bigode retorcido, num estilo de animação estilizado e influente para a época.',
    year: 1942,
    genres: ['Animação', 'Comédia', 'Clássico'],
    runtimeMinutes: 9,
    backdropUrl: 'https://archive.org/services/img/the-dover-boys-at-pimento-university-or-the-rivals-of-roquefort-hall',
    source: { provider: 'archive', id: 'the-dover-boys-at-pimento-university-or-the-rivals-of-roquefort-hall' },
    featured: false,
  },
];
