// Décima quarta leva — filmes B de crime/suspense (poverty row: PRC,
// Monogram, Eagle-Lion, Republic, Screen Guild, Chesterfield, Realart,
// Puritan e produções independentes) encontrados via archivewatch.org e
// publicdomainmovie.net. IMPORTANTE: nesta leva descartamos deliberadamente
// vários títulos "famosos" que apareceram nas prateleiras mais amplas do
// archivewatch.org (community-favorites, most-discussed, wikidata-pd,
// video-cellar) — coisas como "Dracula" (1931, Universal), "Gaslight"
// (1944, MGM), "Sabrina" (1954, Paramount), "The Manchurian Candidate"
// (1962, MGM), obras de Kurosawa/Ozu/Bergman etc. Esses títulos passam na
// checagem técnica de duração (são vídeos reais, não trailers), mas isso não
// significa domínio público: continuam sob direitos autorais ativos de
// grandes estúdios, ou são filmes estrangeiros do pós-guerra cujo copyright
// nos EUA foi restaurado pela URAA em 1996 mesmo que tenham circulado como
// "PD" em compilações de baixa qualidade. Preferimos manter o critério
// conservador das levas anteriores: só entram aqui produções de estúdios
// pequenos/poverty row com padrão bem documentado de não-renovação de
// copyright, e produções Filmgroup de Roger Corman (também um caso
// clássico de não-renovação). source.id verificado manualmente na API do
// archive.org (duração real do vídeo). Sinopse escrita em português a
// partir dos fatos de cada filme, sem reproduzir texto de terceiros.
module.exports = [
  {
    title: 'They Made Me a Criminal',
    slug: 'they-made-me-a-criminal-1939',
    synopsis:
      'Um boxeador campeão foge de Nova York depois de ser injustamente acusado de matar um repórter num acidente que ele nem lembra bem. Escondido sob identidade falsa numa fazenda no deserto que reabilita jovens delinquentes, ele precisa decidir entre continuar fugindo ou provar sua inocência.',
    year: 1939,
    director: 'Busby Berkeley',
    cast: ['John Garfield', 'Claude Rains'],
    genres: ['Drama', 'Suspense', 'Clássico'],
    runtimeMinutes: 91,
    backdropUrl: 'https://archive.org/services/img/They_Made_Me_A_Criminal_1939',
    source: { provider: 'archive', id: 'They_Made_Me_A_Criminal_1939' },
    featured: false,
  },
  {
    title: 'The Lady Confesses',
    slug: 'the-lady-confesses-1945',
    synopsis:
      'Às vésperas de se casar, uma mulher vê o ex-noivo reaparecer depois de anos desaparecido — e quando ele é encontrado morto, ela se torna a principal suspeita, obrigada a investigar por conta própria pra provar sua inocência.',
    year: 1945,
    director: 'Sam Newfield',
    cast: ['Mary Beth Hughes', 'Hugh Beaumont'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 64,
    backdropUrl: 'https://archive.org/services/img/Lady_Confesses',
    source: { provider: 'archive', id: 'Lady_Confesses' },
    featured: false,
  },
  {
    title: "Convict's Code",
    slug: 'convicts-code-1939',
    synopsis:
      'Recém-saído da prisão, um ex-boxeador tenta recomeçar a vida honestamente, mas é perseguido tanto pela suspeita da polícia quanto pelos antigos comparsas que quer deixar para trás.',
    year: 1939,
    director: 'Lambert Hillyer',
    cast: ['Robert Kent', 'Anne Nagel'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 63,
    backdropUrl: 'https://archive.org/services/img/convicts_code',
    source: { provider: 'archive', id: 'convicts_code' },
    featured: false,
  },
  {
    title: 'Shoot to Kill',
    slug: 'shoot-to-kill-1947',
    synopsis:
      'Narrado em flashback por um promotor moribundo, o filme reconstrói o caso que o levou a se casar com uma repórter enquanto perseguia um esquema de corrupção ligado a um gângster — só pra descobrir que os dois lados da lei nem sempre são tão diferentes.',
    year: 1947,
    director: 'William Berke',
    cast: ['Russell Wade', 'Luana Walters'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 64,
    backdropUrl: 'https://archive.org/services/img/Shoot_to_Kill',
    source: { provider: 'archive', id: 'Shoot_to_Kill' },
    featured: false,
  },
  {
    title: 'Wrong Road',
    slug: 'wrong-road-1937',
    synopsis:
      'Um casal jovem foge com o dinheiro de um assalto a banco que planejam devolver depois de curtir a vida boa por um tempo — mas o plano desanda quando a polícia e os cúmplices originais entram no encalço dos dois.',
    year: 1937,
    director: 'James Cruze',
    cast: ['Richard Cromwell', 'Helen Mack'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 53,
    backdropUrl: 'https://archive.org/services/img/wrong_road',
    source: { provider: 'archive', id: 'wrong_road' },
    featured: false,
  },
  {
    title: 'Parole, Inc.',
    slug: 'parole-inc-1948',
    synopsis:
      'Um agente federal se infiltra numa quadrilha que suborna autoridades para conseguir a soltura antecipada de criminosos perigosos, arriscando a própria vida pra desmontar o esquema por dentro.',
    year: 1948,
    director: 'Alfred Zeisler',
    cast: ['Michael O\'Shea', 'Turhan Bey'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 71,
    backdropUrl: 'https://archive.org/services/img/parole_inc',
    source: { provider: 'archive', id: 'parole_inc' },
    featured: false,
  },
  {
    title: 'For You I Die',
    slug: 'for-you-i-die-1947',
    synopsis:
      'Um presidiário planeja fugir da penitenciária com a ajuda de um comparsa do lado de fora, mas se apaixona pela sobrinha do dono do restaurante que serve de fachada para o esquema — complicando tudo quando ele precisa escolher entre a fuga e o amor.',
    year: 1947,
    director: 'John Reinhardt',
    cast: ['Cathy Downs', 'Paul Langton'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 75,
    backdropUrl: 'https://archive.org/services/img/ForYouIDie',
    source: { provider: 'archive', id: 'ForYouIDie' },
    featured: false,
  },
  {
    title: 'The Ghost Walks',
    slug: 'the-ghost-walks-1934',
    synopsis:
      'Um produtor de teatro leva um grupo de investidores a uma mansão isolada numa noite de tempestade para testar uma peça de mistério — só que os assassinatos "encenados" começam a parecer reais demais.',
    year: 1934,
    director: 'Frank R. Strayer',
    cast: ['John Miljan', 'June Collyer'],
    genres: ['Suspense', 'Terror', 'Clássico'],
    runtimeMinutes: 63,
    backdropUrl: 'https://archive.org/services/img/The.Ghost.Walks',
    source: { provider: 'archive', id: 'The.Ghost.Walks' },
    featured: false,
  },
  {
    title: 'Whispering City',
    slug: 'whispering-city-1947',
    synopsis:
      'Uma jornalista investigando um assassinato antigo em Quebec descobre que a trilha leva a um respeitado advogado da alta sociedade — e quanto mais ela se aproxima da verdade, mais perigo corre.',
    year: 1947,
    director: 'Fyodor Otsep',
    cast: ['Mary Anderson', 'Paul Lukas'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 91,
    backdropUrl: 'https://archive.org/services/img/WhisperingCity',
    source: { provider: 'archive', id: 'WhisperingCity' },
    featured: false,
  },
  {
    title: 'St. Benny the Dip',
    slug: 'st-benny-the-dip-1951',
    synopsis:
      'Três vigaristas se disfarçam de padres para escapar da polícia e acabam presos na própria mentira quando a comunidade local passa a depender deles como se fossem religiosos de verdade.',
    year: 1951,
    director: 'Edgar G. Ulmer',
    cast: ['Dick Haymes', 'Nina Foch', 'Roland Young'],
    genres: ['Comédia', 'Clássico'],
    runtimeMinutes: 81,
    backdropUrl: 'https://archive.org/services/img/St.BennyTheDip',
    source: { provider: 'archive', id: 'St.BennyTheDip' },
    featured: false,
  },
  {
    title: 'Two Dollar Bettor',
    slug: 'two-dollar-bettor-1951',
    synopsis:
      'Um contador respeitável desenvolve um vício secreto em apostas de corrida que ameaça destruir o casamento e a reputação que levou a vida inteira para construir.',
    year: 1951,
    director: 'Edward L. Cahn',
    cast: ['Steve Brodie', 'Marie Windsor'],
    genres: ['Drama', 'Clássico'],
    runtimeMinutes: 72,
    backdropUrl: 'https://archive.org/services/img/Two_Dollar_Bettor_movie',
    source: { provider: 'archive', id: 'Two_Dollar_Bettor_movie' },
    featured: false,
  },
  {
    title: 'The Basketball Fix',
    slug: 'the-basketball-fix-1951',
    synopsis:
      'Um jornalista esportivo se envolve pessoalmente ao descobrir que apostadores estão pressionando jogadores universitários a perder partidas de propósito, e precisa escolher entre a matéria e a amizade.',
    year: 1951,
    director: 'Felix E. Feist',
    cast: ['John Ireland', 'Marshall Thompson'],
    genres: ['Drama', 'Clássico'],
    runtimeMinutes: 68,
    backdropUrl: 'https://archive.org/services/img/TheBasketballFix1951',
    source: { provider: 'archive', id: 'TheBasketballFix1951' },
    featured: false,
  },
  {
    title: "Rogue's Tavern",
    slug: 'rogues-tavern-1936',
    synopsis:
      'Um grupo de hóspedes fica isolado numa estalagem à beira da estrada durante uma tempestade, enquanto um assassino misterioso mata as vítimas uma a uma ao ritmo de um relógio que soa a cada crime.',
    year: 1936,
    director: 'Robert F. Hill',
    cast: ['Wallace Ford', 'Barbara Pepper'],
    genres: ['Suspense', 'Terror', 'Clássico'],
    runtimeMinutes: 69,
    backdropUrl: 'https://archive.org/services/img/rogues_tavern',
    source: { provider: 'archive', id: 'rogues_tavern' },
    featured: false,
  },
  {
    title: 'Phantom of Chinatown',
    slug: 'phantom-of-chinatown-1940',
    synopsis:
      'A morte de um arqueólogo logo após uma expedição à China esconde um segredo valioso, e um detetive precisa desvendar quem no círculo próximo da vítima está disposto a matar para ficar com ele.',
    year: 1940,
    director: 'Phil Rosen',
    cast: ['Keye Luke', 'Lotus Long'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 61,
    backdropUrl: 'https://archive.org/services/img/Phantom_of_Chinatown_1940',
    source: { provider: 'archive', id: 'Phantom_of_Chinatown_1940' },
    featured: false,
  },
  {
    title: 'The Fatal Hour',
    slug: 'the-fatal-hour-1940',
    synopsis:
      'Quando um policial amigo é assassinado, o detetive James Lee Wong assume a investigação de um esquema de contrabando que aponta para dentro do próprio departamento de polícia.',
    year: 1940,
    director: 'William Nigh',
    cast: ['Boris Karloff', 'Grant Withers'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 66,
    backdropUrl: 'https://archive.org/services/img/The_Fatal_Hour',
    source: { provider: 'archive', id: 'The_Fatal_Hour' },
    featured: false,
  },
  {
    title: 'Private Snuffy Smith',
    slug: 'private-snuffy-smith-1942',
    synopsis:
      'Baseado na tira de jornal, o caipira preguiçoso Snuffy Smith é convocado para o Exército e, no meio de confusões e desfiles, acaba tropeçando numa trama de espionagem nazista dentro do próprio quartel.',
    year: 1942,
    director: 'Edward F. Cline',
    cast: ['Bud Duncan', 'Edgar Kennedy'],
    genres: ['Comédia', 'Clássico'],
    runtimeMinutes: 66,
    backdropUrl: 'https://archive.org/services/img/private_snuffy_smith',
    source: { provider: 'archive', id: 'private_snuffy_smith' },
    featured: false,
  },
  {
    title: 'Killer Dill',
    slug: 'killer-dill-1947',
    synopsis:
      'Um vendedor pacato e desastrado é confundido com um assassino de aluguel do mesmo nome, e passa a ser perseguido tanto por gângsteres de verdade quanto pela polícia, sem entender bem o que está acontecendo.',
    year: 1947,
    director: 'Lewis D. Collins',
    cast: ['Stuart Erwin', 'Anne Gwynne'],
    genres: ['Comédia', 'Suspense', 'Clássico'],
    runtimeMinutes: 72,
    backdropUrl: 'https://archive.org/services/img/killer_dill',
    source: { provider: 'archive', id: 'killer_dill' },
    featured: false,
  },
  {
    title: "It's a Joke, Son!",
    slug: 'its-a-joke-son-1947',
    synopsis:
      'Um senador sulista conhecido por discursos floreados e nenhuma ação concreta se vê pressionado a defender de verdade os interesses do eleitorado quando um rival ambicioso ameaça expor sua inércia.',
    year: 1947,
    director: 'Ben Stoloff',
    cast: ['Kenny Delmar', 'Una Merkel'],
    genres: ['Comédia', 'Clássico'],
    runtimeMinutes: 63,
    backdropUrl: 'https://archive.org/services/img/its_a_joke_son',
    source: { provider: 'archive', id: 'its_a_joke_son' },
    featured: false,
  },
  {
    title: 'Uncle Joe',
    slug: 'uncle-joe-1941',
    synopsis:
      'Um tio abastado ameaça deserdar os sobrinhos gananciosos se eles não conseguirem uma namorada de "boa índole" em tempo recorde, dando início a uma corrida cômica por um casamento de conveniência.',
    year: 1941,
    director: 'Raymond K. Johnson',
    genres: ['Comédia', 'Clássico'],
    runtimeMinutes: 51,
    backdropUrl: 'https://archive.org/services/img/UncleJoe',
    source: { provider: 'archive', id: 'UncleJoe' },
    featured: false,
  },
  {
    title: 'Kid Dynamite',
    slug: 'kid-dynamite-1943',
    synopsis:
      'A turma da East Side Kids se envolve numa disputa de boxe amador que vira sério demais quando apostadores tentam manipular o resultado da luta em favor do adversário.',
    year: 1943,
    director: 'Wallace Fox',
    cast: ['Leo Gorcey', 'Huntz Hall'],
    genres: ['Comédia', 'Clássico'],
    runtimeMinutes: 66,
    backdropUrl: 'https://archive.org/services/img/kid_dynamite',
    source: { provider: 'archive', id: 'kid_dynamite' },
    featured: false,
  },
  {
    title: 'Club Paradise',
    slug: 'club-paradise-1945',
    synopsis:
      'Uma jovem cantora de clube noturno se vê no meio de uma trama de chantagem quando descobre segredos incômodos sobre os frequentadores ricos do estabelecimento onde trabalha.',
    year: 1945,
    director: 'Leon Barsha',
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 62,
    backdropUrl: 'https://archive.org/services/img/club_paradise',
    source: { provider: 'archive', id: 'club_paradise' },
    featured: false,
  },
  {
    title: 'The City of the Dead',
    slug: 'the-city-of-the-dead-1960',
    synopsis:
      'Uma estudante de história vai a uma cidadela de Nova Inglaterra pesquisar antigos julgamentos de bruxaria e descobre, tarde demais, que o culto que ela estuda nunca deixou de existir por ali.',
    year: 1960,
    director: 'John Llewellyn Moxey',
    cast: ['Christopher Lee', 'Venetia Stevenson'],
    genres: ['Terror', 'Clássico'],
    runtimeMinutes: 76,
    backdropUrl: 'https://archive.org/services/img/Horror_Hotel',
    source: { provider: 'archive', id: 'Horror_Hotel' },
    featured: false,
  },
  {
    title: 'Sweeney Todd: The Demon Barber of Fleet Street',
    slug: 'sweeney-todd-the-demon-barber-of-fleet-street-1936',
    synopsis:
      'Adaptação britânica da lenda vitoriana: um barbeiro de Fleet Street assassina clientes selecionados e os transforma em recheio para as tortas de carne vendidas pela vizinha, num esquema macabro que finalmente começa a desmoronar.',
    year: 1936,
    director: 'George King',
    cast: ['Tod Slaughter'],
    genres: ['Terror', 'Clássico'],
    runtimeMinutes: 68,
    backdropUrl: 'https://archive.org/services/img/sweeney.todd',
    source: { provider: 'archive', id: 'sweeney.todd' },
    featured: false,
  },
  {
    title: 'Nightmare Castle',
    slug: 'nightmare-castle-1965',
    synopsis:
      'Um cientista atormentado tortura e mata a esposa infiel e o amante dela num castelo isolado, mas o crime volta a assombrá-lo anos depois quando ele se casa novamente com uma mulher estranhamente parecida com a vítima.',
    year: 1965,
    director: 'Mario Caiano',
    cast: ['Barbara Steele'],
    genres: ['Terror', 'Clássico'],
    runtimeMinutes: 80,
    backdropUrl: 'https://archive.org/services/img/nightmare_castle',
    source: { provider: 'archive', id: 'nightmare_castle' },
    featured: false,
  },
  {
    title: 'The Sadist',
    slug: 'the-sadist-1963',
    synopsis:
      'Três professores em viagem param num posto de gasolina isolado e caem nas mãos de um jovem criminoso instável e seus reféns, numa tensa disputa de sobrevivência baseada vagamente no caso real de Charles Starkweather.',
    year: 1963,
    director: 'James Landis',
    cast: ['Arch Hall Jr.'],
    genres: ['Suspense', 'Terror', 'Clássico'],
    runtimeMinutes: 92,
    backdropUrl: 'https://archive.org/services/img/The_Sadist',
    source: { provider: 'archive', id: 'The_Sadist' },
    featured: false,
  },
  {
    title: 'Fog Island',
    slug: 'fog-island-1945',
    synopsis:
      'Um milionário recém-saído da prisão convida os antigos sócios que o traíram para uma reunião em sua mansão isolada numa ilha enevoada — supostamente para dividir uma fortuna escondida, mas na verdade para se vingar.',
    year: 1945,
    director: 'Terry O. Morse',
    cast: ['George Zucco', 'Lionel Atwill'],
    genres: ['Terror', 'Suspense', 'Clássico'],
    runtimeMinutes: 69,
    backdropUrl: 'https://archive.org/services/img/Fog_island_1945',
    source: { provider: 'archive', id: 'Fog_island_1945' },
    featured: false,
  },
  {
    title: "Werewolf in a Girls' Dormitory",
    slug: 'werewolf-in-a-girls-dormitory-1962',
    synopsis:
      'Alunas de um internato feminino europeu começam a ser atacadas por uma criatura selvagem durante a noite, e as suspeitas recaem sobre o misterioso diretor da escola, que esconde um segredo antigo.',
    year: 1962,
    director: 'Paolo Heusch',
    cast: ['Carl Schell'],
    genres: ['Terror', 'Clássico'],
    runtimeMinutes: 83,
    backdropUrl: 'https://archive.org/services/img/Werewolf_In_A_Girls_Dormitory',
    source: { provider: 'archive', id: 'Werewolf_In_A_Girls_Dormitory' },
    featured: false,
  },
  {
    title: 'The She Beast',
    slug: 'the-she-beast-1966',
    synopsis:
      'Um casal em lua de mel pelos Alpes transilvanos sofre um acidente de carro num lago amaldiçoado, e a alma de uma bruxa executada séculos antes toma posse do corpo da noiva para se vingar dos descendentes de seus algozes.',
    year: 1966,
    director: 'Michael Reeves',
    cast: ['Barbara Steele'],
    genres: ['Terror', 'Clássico'],
    runtimeMinutes: 79,
    backdropUrl: 'https://archive.org/services/img/TheSheBeast',
    source: { provider: 'archive', id: 'TheSheBeast' },
    featured: false,
  },
  {
    title: 'The Beach Girls and the Monster',
    slug: 'the-beach-girls-and-the-monster-1965',
    synopsis:
      'Enquanto um grupo de surfistas curte a praia, uma criatura marinha começa a atacar os jovens um a um — e o cientista obcecado com estudos do fundo do mar vira o principal suspeito por trás dos ataques.',
    year: 1965,
    director: 'Jon Hall',
    genres: ['Terror', 'Clássico'],
    runtimeMinutes: 66,
    backdropUrl: 'https://archive.org/services/img/TheBeachGirlsAndTheMonster',
    source: { provider: 'archive', id: 'TheBeachGirlsAndTheMonster' },
    featured: false,
  },
  {
    title: 'The Atomic Brain',
    slug: 'the-atomic-brain-1964',
    synopsis:
      'Uma milionária idosa financia experiências ilegais de transplante cerebral na esperança de transferir sua mente para o corpo jovem de uma de suas empregadas — um plano que só piora à medida que mais vítimas são recrutadas.',
    year: 1964,
    director: 'Joseph V. Mascelli',
    genres: ['Terror', 'Ficção Científica', 'Clássico'],
    runtimeMinutes: 65,
    backdropUrl: 'https://archive.org/services/img/TheAtomicBrain',
    source: { provider: 'archive', id: 'TheAtomicBrain' },
    featured: false,
  },
  {
    title: 'The World Gone Mad',
    slug: 'the-world-gone-mad-1933',
    synopsis:
      'A morte de um promotor público prestes a expor um esquema de fraude corporativa leva um repórter e um detetive a investigar até onde a corrupção se estende dentro da própria empresa investigada.',
    year: 1933,
    director: 'Christy Cabanne',
    cast: ['Pat O\'Brien', 'Evelyn Brent'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 71,
    backdropUrl: 'https://archive.org/services/img/WorldGoneMad',
    source: { provider: 'archive', id: 'WorldGoneMad' },
    featured: false,
  },
  {
    title: 'Doomsday Machine',
    slug: 'doomsday-machine-1972',
    synopsis:
      'Com a Terra ameaçada por um ataque nuclear iminente, uma tripulação mista de astronautas americanos e chineses embarca às pressas rumo a Vênus na primeira nave tripulada disponível, na esperança de garantir a sobrevivência da espécie.',
    year: 1972,
    director: 'Harry Hope',
    genres: ['Ficção Científica', 'Clássico'],
    runtimeMinutes: 82,
    backdropUrl: 'https://archive.org/services/img/DoomsdayMachine1972',
    source: { provider: 'archive', id: 'DoomsdayMachine1972' },
    featured: false,
  },
  {
    title: 'Creature from the Haunted Sea',
    slug: 'creature-from-the-haunted-sea-1961',
    synopsis:
      'Um bando de contrabandistas usa a agitação de uma revolução caribenha como fachada para roubar um tesouro em ouro, mas um monstro marinho de aparência ridícula começa a eliminar a quadrilha um por um.',
    year: 1961,
    director: 'Roger Corman',
    genres: ['Terror', 'Comédia', 'Clássico'],
    runtimeMinutes: 75,
    backdropUrl: 'https://archive.org/services/img/CreatureFromTheHauntedSea',
    source: { provider: 'archive', id: 'CreatureFromTheHauntedSea' },
    featured: false,
  },
  {
    title: 'Daughter of Horror',
    slug: 'daughter-of-horror-1955',
    synopsis:
      'Narrado sem diálogos, apenas com uma voz em off, o filme acompanha uma jovem perturbada vagando por uma noite urbana repleta de figuras ameaçadoras, num pesadelo experimental de baixíssimo orçamento que se tornou item de culto.',
    year: 1955,
    director: 'John Parker',
    cast: ['Adrienne Barrett'],
    genres: ['Terror', 'Clássico'],
    runtimeMinutes: 55,
    backdropUrl: 'https://archive.org/services/img/daughter_of_horror',
    source: { provider: 'archive', id: 'daughter_of_horror' },
    featured: false,
  },
  {
    title: 'The Naked Witch',
    slug: 'the-naked-witch-1961',
    synopsis:
      'Um estudante de folclore numa pequena cidade alemão-americana do Texas desperta sem querer o espírito vingativo de uma mulher executada séculos antes sob acusação de bruxaria.',
    year: 1961,
    director: 'Larry Buchanan',
    genres: ['Terror', 'Clássico'],
    runtimeMinutes: 59,
    backdropUrl: 'https://archive.org/services/img/TheNakedWitch',
    source: { provider: 'archive', id: 'TheNakedWitch' },
    featured: false,
  },
  {
    title: 'Last Man on Earth',
    slug: 'last-man-on-earth-1964',
    synopsis:
      'O único sobrevivente de uma pandemia que transformou toda a humanidade em criaturas vampíricas passa os dias caçando os infectados e as noites se defendendo do cerco à sua casa fortificada — até encontrar sinais de que talvez não esteja tão sozinho quanto pensa. Baseado no romance "Eu Sou a Lenda", de Richard Matheson.',
    year: 1964,
    director: 'Ubaldo Ragona',
    cast: ['Vincent Price'],
    genres: ['Terror', 'Ficção Científica', 'Clássico'],
    runtimeMinutes: 86,
    backdropUrl: 'https://archive.org/services/img/lastmanonearth-1964',
    source: { provider: 'archive', id: 'lastmanonearth-1964' },
    featured: false,
  },
  {
    title: 'Fragment of an Empire',
    slug: 'fragment-of-an-empire-1929',
    synopsis:
      'Um soldado russo perde a memória durante a Primeira Guerra Mundial e desperta uma década depois, num mundo transformado pela Revolução — sua jornada para reencontrar a lembrança do passado se torna também um retrato da nova sociedade soviética.',
    year: 1929,
    director: 'Fridrikh Ermler',
    genres: ['Drama', 'Mudo', 'Clássico'],
    runtimeMinutes: 110,
    backdropUrl: 'https://archive.org/services/img/fragment-of-an-empire-1929',
    source: { provider: 'archive', id: 'fragment-of-an-empire-1929' },
    featured: false,
  },
];
