// Décima sexta leva — faroestes B de poverty row (Monogram, PRC, Republic,
// Supreme, Puritan e produções independentes dos anos 1930) encontrados via
// publicdomainmovie.net. Mesma lógica de domínio público das levas
// anteriores de faroeste: esses estúdios pequenos raramente renovavam o
// copyright depois dos 28 anos exigidos pela lei da época, o que deixou boa
// parte do gênero em domínio público bem documentado. source.id verificado
// manualmente na API do archive.org (duração real do vídeo). Sinopse
// escrita em português a partir dos fatos disponíveis de cada filme
// (elenco, estúdio, ano, elementos de enredo já documentados publicamente),
// sem reproduzir texto de terceiros.
module.exports = [
  {
    title: 'My Pal Trigger',
    slug: 'my-pal-trigger-1946',
    synopsis:
      'Um criador de cavalos é acusado injustamente de roubo depois que seu potro premiado é confundido com um cavalo assassino — e ele precisa provar a inocência do animal e a própria antes que a Justiça local decida pelo linchamento sumário.',
    year: 1946,
    director: 'Frank McDonald',
    cast: ['Roy Rogers', 'Trigger'],
    genres: ['Faroeste', 'Clássico'],
    runtimeMinutes: 79,
    backdropUrl: 'https://archive.org/services/img/my_pal_trigger',
    source: { provider: 'archive', id: 'my_pal_trigger' },
    featured: false,
  },
  {
    title: 'Raiders of Old California',
    slug: 'raiders-of-old-california-1957',
    synopsis:
      'Durante a corrida do ouro na Califórnia, um bando de golpistas usa documentos falsificados para expulsar famílias legítimas de suas próprias terras — até que um grupo de rancheiros decide reagir.',
    year: 1957,
    director: 'Albert C. Gannaway',
    cast: ['Jim Davis'],
    genres: ['Faroeste', 'Clássico'],
    runtimeMinutes: 72,
    backdropUrl: 'https://archive.org/services/img/raiders_of_old_california_ipod',
    source: { provider: 'archive', id: 'raiders_of_old_california_ipod' },
    featured: false,
  },
  {
    title: 'Aces and Eights',
    slug: 'aces-and-eights-1936',
    synopsis:
      'Um jogador de cartas profissional é expulso da cidade sob acusação de trapaça armada por rivais, e precisa provar que foi vítima de um esquema para incriminá-lo antes que a vingança dos verdadeiros trapaceiros o alcance.',
    year: 1936,
    director: 'Sam Newfield',
    cast: ['Tim McCoy'],
    genres: ['Faroeste', 'Clássico'],
    runtimeMinutes: 61,
    backdropUrl: 'https://archive.org/services/img/aces_and_eights',
    source: { provider: 'archive', id: 'aces_and_eights' },
    featured: false,
  },
  {
    title: 'Tombstone Canyon',
    slug: 'tombstone-canyon-1932',
    synopsis:
      'Um forasteiro chega a um cânion isolado à procura da própria origem e descobre que a região é assombrada por lendas de um "monstro" que, na verdade, esconde um esquema criminoso de longa data envolvendo sua própria família.',
    year: 1932,
    director: 'Alan James',
    cast: ['Ken Maynard'],
    genres: ['Faroeste', 'Clássico'],
    runtimeMinutes: 58,
    backdropUrl: 'https://archive.org/services/img/TombstoneCanyon',
    source: { provider: 'archive', id: 'TombstoneCanyon' },
    featured: false,
  },
  {
    title: 'Young Bill Hickok',
    slug: 'young-bill-hickok-1940',
    synopsis:
      'Antes de se tornar lenda, um jovem Wild Bill Hickok se infiltra numa trama de traidores que tentam entregar o território a uma potência estrangeira, unindo forças com um grupo de colonos para frustrar a conspiração.',
    year: 1940,
    director: 'Joseph Kane',
    cast: ['Roy Rogers'],
    genres: ['Faroeste', 'Clássico'],
    runtimeMinutes: 53,
    backdropUrl: 'https://archive.org/services/img/young_bill_hickok',
    source: { provider: 'archive', id: 'young_bill_hickok' },
    featured: false,
  },
  {
    title: 'Hard Hombre',
    slug: 'hard-hombre-1931',
    synopsis:
      'Um homem foge injustamente condenado por um crime que não cometeu e, escondido sob nova identidade no território selvagem, acaba se tornando o herói que a cidadela local precisa contra uma quadrilha de fora da lei.',
    year: 1931,
    director: 'Otto Brower',
    cast: ['Hoot Gibson'],
    genres: ['Faroeste', 'Clássico'],
    runtimeMinutes: 64,
    backdropUrl: 'https://archive.org/services/img/hard_hombre',
    source: { provider: 'archive', id: 'hard_hombre' },
    featured: false,
  },
  {
    title: 'Daniel Boone',
    slug: 'daniel-boone-1936',
    synopsis:
      'Dramatização livre da vida do pioneiro americano Daniel Boone, liderando colonos através da fronteira selvagem de Kentucky em meio a conflitos com tribos nativas manipuladas por agentes britânicos.',
    year: 1936,
    director: 'David Howard',
    cast: ['George O\'Brien'],
    genres: ['Faroeste', 'Aventura', 'Clássico'],
    runtimeMinutes: 75,
    backdropUrl: 'https://archive.org/services/img/daniel-boone-1936',
    source: { provider: 'archive', id: 'daniel-boone-1936' },
    featured: false,
  },
  {
    title: 'The Arizona Kid',
    slug: 'the-arizona-kid-1939',
    synopsis:
      'Durante a Guerra Civil, um pistoleiro do Arizona se envolve com uma quadrilha de guerrilheiros que usam o conflito como desculpa para saquear rancheiros neutros — e precisa decidir de que lado realmente está.',
    year: 1939,
    director: 'Joseph Kane',
    cast: ['Roy Rogers'],
    genres: ['Faroeste', 'Clássico'],
    runtimeMinutes: 53,
    backdropUrl: 'https://archive.org/services/img/Arizona_Kid_1939',
    source: { provider: 'archive', id: 'Arizona_Kid_1939' },
    featured: false,
  },
  {
    title: 'Rocky Mountain Mystery',
    slug: 'rocky-mountain-mystery-1935',
    synopsis:
      'A morte súbita do dono de uma mina de rádio reúne todos os possíveis herdeiros e sócios num rancho isolado nas montanhas — e um investigador precisa descobrir qual deles está disposto a matar de novo para ficar com a fortuna.',
    year: 1935,
    director: 'Charles Barton',
    cast: ['Randolph Scott'],
    genres: ['Faroeste', 'Suspense', 'Clássico'],
    runtimeMinutes: 66,
    backdropUrl: 'https://archive.org/services/img/Rocky_Mountain_Mystery_1935',
    source: { provider: 'archive', id: 'Rocky_Mountain_Mystery_1935' },
    featured: false,
  },
  {
    title: 'Guns of the Law',
    slug: 'guns-of-the-law-1944',
    synopsis:
      'Os Rangers do Texas se infiltram numa cidade dominada por um bando de falsários e contrabandistas, precisando descobrir quem entre os cidadãos respeitáveis está por trás do esquema antes que outro inocente seja acusado em seu lugar.',
    year: 1944,
    director: 'Robert Emmett Tansey',
    genres: ['Faroeste', 'Clássico'],
    runtimeMinutes: 53,
    backdropUrl: 'https://archive.org/services/img/GunsOfTheLaw44',
    source: { provider: 'archive', id: 'GunsOfTheLaw44' },
    featured: false,
  },
  {
    title: 'Desert Gold',
    slug: 'desert-gold-1936',
    synopsis:
      'Baseado no romance de Zane Grey: um homem se junta a uma expedição pelo deserto atrás de uma mina de ouro perdida, enquanto disputas de terra e ciúme ameaçam transformar a jornada numa tragédia.',
    year: 1936,
    director: 'James Hogan',
    cast: ['Larry Crabbe', 'Robert Cummings'],
    genres: ['Faroeste', 'Aventura', 'Clássico'],
    runtimeMinutes: 54,
    backdropUrl: 'https://archive.org/services/img/DesertGold',
    source: { provider: 'archive', id: 'DesertGold' },
    featured: false,
  },
  {
    title: 'Legion of Missing Men',
    slug: 'legion-of-missing-men-1937',
    synopsis:
      'Dois irmãos se alistam na Legião Estrangeira Francesa no norte da África, mas um mal-entendido sobre covardia em combate ameaça manchar a honra da família até que a verdade sobre o incidente venha à tona.',
    year: 1937,
    director: 'Elmer Clifton',
    cast: ['Ralph Forbes', 'Ben Alexander'],
    genres: ['Aventura', 'Clássico'],
    runtimeMinutes: 63,
    backdropUrl: 'https://archive.org/services/img/LegionOfMissingMen',
    source: { provider: 'archive', id: 'LegionOfMissingMen' },
    featured: false,
  },
  {
    title: 'Diamond Trail',
    slug: 'diamond-trail-1933',
    synopsis:
      'Um cowboy se infiltra sob identidade falsa numa cidadela controlada por contrabandistas de gado, tentando reunir provas suficientes para desmontar a quadrilha antes de ser descoberto.',
    year: 1933,
    director: 'John P. McCarthy',
    cast: ['Rex Bell'],
    genres: ['Faroeste', 'Clássico'],
    runtimeMinutes: 58,
    backdropUrl: 'https://archive.org/services/img/DiamondTrail',
    source: { provider: 'archive', id: 'DiamondTrail' },
    featured: false,
  },
  {
    title: 'Galloping Romeo',
    slug: 'galloping-romeo-1933',
    synopsis:
      'Um pistoleiro errante chega a uma cidadela dividida por uma disputa de terras entre dois rancheiros rivais e, ao se apaixonar pela filha de um deles, acaba se vendo obrigado a escolher um lado no conflito.',
    year: 1933,
    director: 'Robert North Bradbury',
    cast: ['Bob Steele'],
    genres: ['Faroeste', 'Clássico'],
    runtimeMinutes: 52,
    backdropUrl: 'https://archive.org/services/img/GallopingRomeo',
    source: { provider: 'archive', id: 'GallopingRomeo' },
    featured: false,
  },
  {
    title: 'The Montana Kid',
    slug: 'the-montana-kid-1931',
    synopsis:
      'Um pistoleiro conhecido como o "Kid de Montana" tenta abandonar a vida fora da lei e recomeçar honestamente, mas seu passado o alcança quando um antigo comparsa ameaça expor seus crimes à nova comunidade.',
    year: 1931,
    director: 'Harry S. Webb',
    cast: ['Bill Cody'],
    genres: ['Faroeste', 'Clássico'],
    runtimeMinutes: 58,
    backdropUrl: 'https://archive.org/services/img/TheMontanaKid',
    source: { provider: 'archive', id: 'TheMontanaKid' },
    featured: false,
  },
  {
    title: 'Cavalcade of the West',
    slug: 'cavalcade-of-the-west-1936',
    synopsis:
      'Um oficial da cavalaria é enviado para investigar ataques que estão sendo atribuídos a uma tribo nativa pacífica, e descobre que a verdadeira causa é uma quadrilha de renegados disfarçados tentando provocar uma guerra.',
    year: 1936,
    director: 'Harry L. Fraser',
    cast: ['Hoot Gibson'],
    genres: ['Faroeste', 'Clássico'],
    runtimeMinutes: 60,
    backdropUrl: 'https://archive.org/services/img/cavalcade_of_the_west',
    source: { provider: 'archive', id: 'cavalcade_of_the_west' },
    featured: false,
  },
  {
    title: 'The Trail Beyond',
    slug: 'the-trail-beyond-1934',
    synopsis:
      'A pedido de um tio, um homem viaja ao Canadá para ajudar uma jovem herdeira a encontrar uma mina de ouro perdida, mas descobre que outros pretendentes à fortuna estão dispostos a matar para chegar primeiro.',
    year: 1934,
    director: 'Robert N. Bradbury',
    cast: ['John Wayne'],
    genres: ['Faroeste', 'Aventura', 'Clássico'],
    runtimeMinutes: 55,
    backdropUrl: 'https://archive.org/services/img/the-trail-beyond-1934',
    source: { provider: 'archive', id: 'the-trail-beyond-1934' },
    featured: false,
  },
  {
    title: 'The Desert Trail',
    slug: 'the-desert-trail-1935',
    synopsis:
      'Um campeão de rodeio foge da cidade injustamente acusado de um roubo cometido pelo próprio parceiro, e precisa encontrar o verdadeiro ladrão antes que a fama de fora da lei o alcance de vez.',
    year: 1935,
    director: 'Cullen Lewis',
    cast: ['John Wayne'],
    genres: ['Faroeste', 'Clássico'],
    runtimeMinutes: 54,
    backdropUrl: 'https://archive.org/services/img/TheDesertTrail1935',
    source: { provider: 'archive', id: 'TheDesertTrail1935' },
    featured: false,
  },
  {
    title: 'Phantom of the Range',
    slug: 'phantom-of-the-range-1936',
    synopsis:
      'Rumores de um "fantasma" assombrando terras de rancho escondem, na verdade, um esquema para afugentar os donos legítimos e ficar com o petróleo descoberto sob o solo — cabe a um forasteiro desmascarar a farsa.',
    year: 1936,
    director: 'Robert F. Hill',
    cast: ['Tom Tyler'],
    genres: ['Faroeste', 'Clássico'],
    runtimeMinutes: 58,
    backdropUrl: 'https://archive.org/services/img/phantom_of_the_range',
    source: { provider: 'archive', id: 'phantom_of_the_range' },
    featured: false,
  },
  {
    title: 'Mason of the Mounted',
    slug: 'mason-of-the-mounted-1932',
    synopsis:
      'Um agente da polícia montada se disfarça de fora da lei para se infiltrar numa quadrilha de contrabandistas na fronteira, arriscando a própria vida para desmontar o esquema por dentro.',
    year: 1932,
    director: 'Harry Fraser',
    cast: ['Tom Tyler'],
    genres: ['Faroeste', 'Clássico'],
    runtimeMinutes: 53,
    backdropUrl: 'https://archive.org/services/img/MasonoftheMounted',
    source: { provider: 'archive', id: 'MasonoftheMounted' },
    featured: false,
  },
  {
    title: 'Danger Valley',
    slug: 'danger-valley-1937',
    synopsis:
      'Um pistoleiro solitário chega a um vale controlado por um bando de grileiros que forjam documentos para expulsar pequenos fazendeiros, e decide ajudar a comunidade a recuperar suas terras.',
    year: 1937,
    director: 'Robert Hill',
    cast: ['Bob Steele'],
    genres: ['Faroeste', 'Clássico'],
    runtimeMinutes: 51,
    backdropUrl: 'https://archive.org/services/img/DangerValley',
    source: { provider: 'archive', id: 'DangerValley' },
    featured: false,
  },
  {
    title: 'Broadway to Cheyenne',
    slug: 'broadway-to-cheyenne-1932',
    synopsis:
      'Um gângster de Nova York foge para o oeste depois de um golpe dar errado e, ao se esconder num rancho, precisa decidir se continua na vida do crime ou aproveita a chance de recomeçar honestamente.',
    year: 1932,
    director: 'Harry L. Fraser',
    cast: ['Rex Bell'],
    genres: ['Faroeste', 'Clássico'],
    runtimeMinutes: 52,
    backdropUrl: 'https://archive.org/services/img/BroadwayToCheyenne_564',
    source: { provider: 'archive', id: 'BroadwayToCheyenne_564' },
    featured: false,
  },
  {
    title: 'Where the Buffalo Roam',
    slug: 'where-the-buffalo-roam-1938',
    synopsis:
      'Um jovem cowboy retorna ao rancho da família para descobrir que caçadores inescrupulosos estão dizimando o rebanho de búfalos da região só pelo couro, e decide se opor a eles junto com os poucos que ainda respeitam a terra.',
    year: 1938,
    director: 'Raymond K. Johnson',
    cast: ['Tom Tyler'],
    genres: ['Faroeste', 'Clássico'],
    runtimeMinutes: 62,
    backdropUrl: 'https://archive.org/services/img/WheretheBuffaloRoam',
    source: { provider: 'archive', id: 'WheretheBuffaloRoam' },
    featured: false,
  },
];
