// Décima leva — mais três Sherlock Holmes da Universal, filme noir B,
// faroestes B e documentários de guerra/propaganda em domínio público.
// Encontrados via publicdomainmovie.net, archivewatch.org e emol.org.
// source.id verificado manualmente na API do archive.org (duração real do
// arquivo de vídeo comparada com a duração conhecida do filme) antes de
// entrar aqui. A sinopse foi escrita em português a partir dos fatos do
// filme, sem reproduzir texto de terceiros.
module.exports = [
  {
    title: 'The Pearl of Death',
    slug: 'the-pearl-of-death-1944',
    synopsis:
      'Uma pérola valiosíssima é escondida dentro de uma de seis estátuas de gesso idênticas, e Holmes precisa encontrá-la antes de um gigante desfigurado apelidado de "Creeper", que mata todo mundo que cruza seu caminho.',
    year: 1944,
    director: 'Roy William Neill',
    cast: ['Basil Rathbone', 'Nigel Bruce'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 66,
    backdropUrl: 'https://archive.org/services/img/sherlock-holmes-and-the-pearl-of-death',
    source: { provider: 'archive', id: 'sherlock-holmes-and-the-pearl-of-death' },
    featured: false,
  },
  {
    title: 'Terror by Night',
    slug: 'terror-by-night-1946',
    synopsis:
      'Holmes é contratado para proteger um diamante famoso e seus donos durante uma viagem de trem de Londres a Edimburgo, mas a pedra desaparece e um passageiro é encontrado morto ainda em movimento.',
    year: 1946,
    director: 'Roy William Neill',
    cast: ['Basil Rathbone', 'Nigel Bruce'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 60,
    backdropUrl: 'https://archive.org/services/img/TerrorByNight',
    source: { provider: 'archive', id: 'TerrorByNight' },
    featured: false,
  },
  {
    title: 'Dressed to Kill',
    slug: 'dressed-to-kill-1946',
    synopsis:
      'Último filme da série Universal: um código secreto está escondido na afinação de três caixinhas de música idênticas, e Holmes corre contra criminosos que também querem as chapas de impressão de dinheiro que o código revela.',
    year: 1946,
    director: 'Roy William Neill',
    cast: ['Basil Rathbone', 'Nigel Bruce'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 72,
    backdropUrl: 'https://archive.org/services/img/dressed_to_kill',
    source: { provider: 'archive', id: 'dressed_to_kill' },
    featured: false,
  },
  {
    title: 'Confessions of Boston Blackie',
    slug: 'confessions-of-boston-blackie-1941',
    synopsis:
      'Boston Blackie visita um leilão de antiguidades onde uma estátua é roubada e o leiloeiro é assassinado, e precisa provar sua própria inocência enquanto investiga quem realmente cometeu o crime.',
    year: 1941,
    director: 'Edward Dmytryk',
    cast: ['Chester Morris'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 65,
    backdropUrl: 'https://archive.org/services/img/confessions-of-boston-blackie',
    source: { provider: 'archive', id: 'confessions-of-boston-blackie' },
    featured: false,
  },
  {
    title: 'Impact',
    slug: 'impact-1949',
    synopsis:
      'Um empresário sobrevive por acaso a uma tentativa de assassinato arquitetada pela própria esposa e pelo amante dela, e aproveita para forjar a própria morte e recomeçar a vida sob outra identidade, até o passado alcançá-lo.',
    year: 1949,
    director: 'Arthur Lubin',
    cast: ['Brian Donlevy'],
    genres: ['Suspense', 'Drama', 'Clássico'],
    runtimeMinutes: 111,
    backdropUrl: 'https://archive.org/services/img/impact',
    source: { provider: 'archive', id: 'impact' },
    featured: false,
  },
  {
    title: 'Trapped',
    slug: 'trapped-1949',
    synopsis:
      'Um falsário liberado da prisão para ajudar o Serviço Secreto a localizar chapas de impressão escondidas foge para se reunir com a antiga quadrilha, sem saber que um agente federal disfarçado está infiltrado bem perto dele.',
    year: 1949,
    director: 'Richard Fleischer',
    cast: ['Lloyd Bridges'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 78,
    backdropUrl: 'https://archive.org/services/img/Trapped_',
    source: { provider: 'archive', id: 'Trapped_' },
    featured: false,
  },
  {
    title: 'Railroaded!',
    slug: 'railroaded-1947',
    synopsis:
      'Um detetive investiga um assalto seguido de assassinato numa salão de beleza e descobre que a dona do lugar comanda, nos bastidores, uma quadrilha inteira — enquanto um jovem inocente corre o risco de ser condenado no lugar dela.',
    year: 1947,
    director: 'Anthony Mann',
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 72,
    backdropUrl: 'https://archive.org/services/img/railroaded1947_202003',
    source: { provider: 'archive', id: 'railroaded1947_202003' },
    featured: false,
  },
  {
    title: 'Money Madness',
    slug: 'money-madness-1948',
    synopsis:
      'Um motorista de táxi esconde uma fortuna roubada e manipula uma mulher solitária para se casar com ele e lavar o dinheiro através dela, mas a sobrinha desconfiada da mulher começa a investigar o passado dele.',
    year: 1948,
    director: 'Sam Newfield',
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 73,
    backdropUrl: 'https://archive.org/services/img/MoneyMadness',
    source: { provider: 'archive', id: 'MoneyMadness' },
    featured: false,
  },
  {
    title: 'Blonde Ice',
    slug: 'blonde-ice-1948',
    synopsis:
      'Uma colunista social ambiciosa e sem escrúpulos vai se casando e se livrando de maridos ricos para financiar sua ascensão social, enquanto um repórter que ainda a ama começa a perceber o padrão por trás das mortes.',
    year: 1948,
    director: 'Jack Bernhard',
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 74,
    backdropUrl: 'https://archive.org/services/img/BlondeIce',
    source: { provider: 'archive', id: 'BlondeIce' },
    featured: false,
  },
  {
    title: 'Moonrise',
    slug: 'moonrise-1948',
    synopsis:
      'Atormentado desde criança pela lembrança do pai executado por assassinato, um jovem mata acidentalmente o homem que o atormenta e passa a viver dividido entre a culpa e o medo de repetir o destino do pai.',
    year: 1948,
    director: 'Frank Borzage',
    cast: ['Dane Clark', 'Gail Russell'],
    genres: ['Suspense', 'Drama', 'Clássico'],
    runtimeMinutes: 90,
    backdropUrl: 'https://archive.org/services/img/moonrise-1948',
    source: { provider: 'archive', id: 'moonrise-1948' },
    featured: false,
  },
  {
    title: 'Whistle Stop',
    slug: 'whistle-stop-1946',
    synopsis:
      'Uma mulher volta à cidadezinha natal e reencontra o ex-namorado, reacendendo uma rivalidade com o gerente de um bar local que vai desencadear ciúme, chantagem e um plano de assassinato.',
    year: 1946,
    director: 'Léonide Moguy',
    cast: ['Ava Gardner', 'George Raft'],
    genres: ['Suspense', 'Drama', 'Clássico'],
    runtimeMinutes: 84,
    backdropUrl: 'https://archive.org/services/img/Whistle_Stop',
    source: { provider: 'archive', id: 'Whistle_Stop' },
    featured: false,
  },
  {
    title: 'The Second Woman',
    slug: 'the-second-woman-1951',
    synopsis:
      'Um arquiteto atormentado por uma série de acidentes e sabotagens em sua propriedade começa a duvidar da própria sanidade, até que a mulher que se apaixona por ele resolve investigar o que está realmente acontecendo.',
    year: 1951,
    director: 'James V. Kern',
    cast: ['Robert Young'],
    genres: ['Suspense', 'Drama', 'Clássico'],
    runtimeMinutes: 90,
    backdropUrl: 'https://archive.org/services/img/The_Second_Woman_',
    source: { provider: 'archive', id: 'The_Second_Woman_' },
    featured: false,
  },
  {
    title: 'The Limping Man',
    slug: 'the-limping-man-1953',
    synopsis:
      'Um veterano de guerra americano volta a Londres para reencontrar um antigo amor e testemunha um assassinato no aeroporto, sendo então arrastado para uma trama de chantagem e espionagem que ele não esperava.',
    year: 1953,
    director: 'Charles de Latour',
    cast: ['Lloyd Bridges'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 76,
    backdropUrl: 'https://archive.org/services/img/TheLimpingMan',
    source: { provider: 'archive', id: 'TheLimpingMan' },
    featured: false,
  },
  {
    title: 'Cause for Alarm!',
    slug: 'cause-for-alarm-1951',
    synopsis:
      'Um marido doente e paranoico escreve uma carta acusando falsamente a própria esposa de tentar matá-lo antes de morrer de causas naturais, e ela tem poucas horas para recuperar a carta antes que ela chegue à polícia.',
    year: 1951,
    director: 'Tay Garnett',
    cast: ['Loretta Young'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 74,
    backdropUrl: 'https://archive.org/services/img/cause_for_alarm',
    source: { provider: 'archive', id: 'cause_for_alarm' },
    featured: false,
  },
  {
    title: 'Danger Ahead',
    slug: 'danger-ahead-1935',
    synopsis:
      'Um jovem casal em lua de mel se hospeda numa pousada isolada que serve de fachada para uma quadrilha de falsificadores, e acaba se envolvendo na investigação para desmontar o esquema.',
    year: 1935,
    director: 'Robert F. Hill',
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 59,
    backdropUrl: 'https://archive.org/services/img/danger_ahead',
    source: { provider: 'archive', id: 'danger_ahead' },
    featured: false,
  },
  {
    title: 'The Big Combo',
    slug: 'the-big-combo-1955',
    synopsis:
      'Um policial obcecado por derrubar um chefão do crime intocável pela lei também está apaixonado pela namorada do bandido, e usa a fragilidade emocional dela como a brecha que precisa para finalmente encurralar o criminoso.',
    year: 1955,
    director: 'Joseph H. Lewis',
    cast: ['Cornel Wilde', 'Richard Conte'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 84,
    backdropUrl: 'https://archive.org/services/img/Big_Combo_1955',
    source: { provider: 'archive', id: 'Big_Combo_1955' },
    featured: false,
  },
  {
    title: 'Lady of Burlesque',
    slug: 'lady-of-burlesque-1943',
    synopsis:
      'Um assassino começa a matar as dançarinas de uma casa de burlesco da Broadway uma a uma, e a estrela do show precisa descobrir quem é o culpado antes de se tornar a próxima vítima.',
    year: 1943,
    director: 'William A. Wellman',
    cast: ['Barbara Stanwyck'],
    genres: ['Suspense', 'Comédia', 'Clássico'],
    runtimeMinutes: 91,
    backdropUrl: 'https://archive.org/services/img/LadyofBurlesque',
    source: { provider: 'archive', id: 'LadyofBurlesque' },
    featured: false,
  },
  {
    title: 'Svengali',
    slug: 'svengali-1931',
    synopsis:
      'Um professor de música hipnotizador transforma uma jovem cantora medíocre numa estrela da ópera controlando sua mente e sua vontade, mas o poder que exerce sobre ela também o consome.',
    year: 1931,
    director: 'Archie Mayo',
    cast: ['John Barrymore'],
    genres: ['Drama', 'Terror', 'Clássico'],
    runtimeMinutes: 81,
    backdropUrl: 'https://archive.org/services/img/Svengali1931_201508',
    source: { provider: 'archive', id: 'Svengali1931_201508' },
    featured: false,
  },
  {
    title: 'The Man Who Cheated Himself',
    slug: 'the-man-who-cheated-himself-1951',
    synopsis:
      'Um detetive de homicídios encobre um crime cometido pela mulher que ama, mas o caso acaba sendo designado justamente ao próprio irmão dele, um policial novato decidido a resolvê-lo a qualquer custo.',
    year: 1951,
    director: 'Felix E. Feist',
    cast: ['Lee J. Cobb'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 99,
    backdropUrl: 'https://archive.org/services/img/Man_Who_Cheated_Himself',
    source: { provider: 'archive', id: 'Man_Who_Cheated_Himself' },
    featured: false,
  },
  {
    title: 'Mysterious Intruder',
    slug: 'mysterious-intruder-1946',
    synopsis:
      'Um detetive particular é contratado para localizar uma jovem desaparecida ligada a um conjunto de gravações raras e valiosas, e logo percebe que várias pessoas estão dispostas a matar para ficar com elas.',
    year: 1946,
    director: 'William Castle',
    cast: ['Richard Dix'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 62,
    backdropUrl: 'https://archive.org/services/img/mysterious-intruder-1946',
    source: { provider: 'archive', id: 'mysterious-intruder-1946' },
    featured: false,
  },
  {
    title: 'I Cover the Waterfront',
    slug: 'i-cover-the-waterfront-1933',
    synopsis:
      'Um repórter investigando um esquema de contrabando de imigrantes pelas docas se apaixona pela filha do capitão de barco que está tentando expor, complicando sua busca pela grande reportagem.',
    year: 1933,
    director: 'James Cruze',
    genres: ['Drama', 'Romance', 'Clássico'],
    runtimeMinutes: 72,
    backdropUrl: 'https://archive.org/services/img/I_Cover_the_Waterfront',
    source: { provider: 'archive', id: 'I_Cover_the_Waterfront' },
    featured: false,
  },
  {
    title: 'Waterfront Lady',
    slug: 'waterfront-lady-1935',
    synopsis:
      'Um trabalhador do cais é acusado injustamente de um crime ligado ao negócio de rebocadores do pai e precisa provar sua inocência para não perder tanto a liberdade quanto o amor de sua vida.',
    year: 1935,
    director: 'Joseph Santley',
    genres: ['Drama', 'Romance', 'Clássico'],
    runtimeMinutes: 68,
    backdropUrl: 'https://archive.org/services/img/waterfront_lady',
    source: { provider: 'archive', id: 'waterfront_lady' },
    featured: false,
  },
  {
    title: 'Gun Lords of Stirrup Basin',
    slug: 'gun-lords-of-stirrup-basin-1937',
    synopsis:
      'Um caubói justiceiro intervém quando um fazendeiro corrupto tenta tomar as terras de pequenos criadores da região usando intimidação e contratos fraudulentos.',
    year: 1937,
    director: 'Sam Newfield',
    cast: ['Bob Steele'],
    genres: ['Faroeste', 'Clássico'],
    runtimeMinutes: 55,
    backdropUrl: 'https://archive.org/services/img/gun-lords-of-stirrup-basin-1937',
    source: { provider: 'archive', id: 'gun-lords-of-stirrup-basin-1937' },
    featured: false,
  },
  {
    title: 'Last of the Warrens',
    slug: 'last-of-the-warrens-1936',
    synopsis:
      'O último sobrevivente de uma família de fazendeiros perseguida limpa o nome dos parentes e desmascara a quadrilha que os incriminou por roubo de gado.',
    year: 1936,
    director: 'Robert N. Bradbury',
    cast: ['Bob Steele'],
    genres: ['Faroeste', 'Clássico'],
    runtimeMinutes: 53,
    backdropUrl: 'https://archive.org/services/img/last_of_the_warrens',
    source: { provider: 'archive', id: 'last_of_the_warrens' },
    featured: false,
  },
  {
    title: 'Billy the Kid Trapped',
    slug: 'billy-the-kid-trapped-1942',
    synopsis:
      'Um impostor usa a identidade de Billy the Kid para cometer crimes em seu nome, obrigando o verdadeiro fora da lei a caçar o próprio sósia antes de ser responsabilizado por assassinatos que não cometeu.',
    year: 1942,
    director: 'Sam Newfield',
    cast: ['Buster Crabbe'],
    genres: ['Faroeste', 'Clássico'],
    runtimeMinutes: 55,
    backdropUrl: 'https://archive.org/services/img/Billy_the_Kid_-_Trapped',
    source: { provider: 'archive', id: 'Billy_the_Kid_-_Trapped' },
    featured: false,
  },
  {
    title: 'Billy the Kid in Santa Fe',
    slug: 'billy-the-kid-in-santa-fe-1941',
    synopsis:
      'Billy the Kid enfrenta uma quadrilha que contrabandeia ouro roubado disfarçando a operação de mineração legítima, numa aventura cheia de emboscadas e reviravoltas.',
    year: 1941,
    director: 'Sam Newfield',
    cast: ['Buster Crabbe'],
    genres: ['Faroeste', 'Clássico'],
    runtimeMinutes: 63,
    backdropUrl: 'https://archive.org/services/img/Billy_the_Kid_in_Santa_Fe_1941',
    source: { provider: 'archive', id: 'Billy_the_Kid_in_Santa_Fe_1941' },
    featured: false,
  },
  {
    title: 'Arizona Days',
    slug: 'arizona-days-1937',
    synopsis:
      'Um caubói cantor desmascara um esquema de corrupção que está prejudicando os fazendeiros da região, misturando números musicais com a ação típica dos faroestes B da época.',
    year: 1937,
    director: 'Ray Taylor',
    cast: ['Tex Ritter'],
    genres: ['Faroeste', 'Clássico'],
    runtimeMinutes: 42,
    backdropUrl: 'https://archive.org/services/img/Arizona_Days',
    source: { provider: 'archive', id: 'Arizona_Days' },
    featured: false,
  },
  {
    title: 'Law of the West',
    slug: 'law-of-the-west-1932',
    synopsis:
      'Um pistoleiro que largou a vida de fora da lei para virar xerife de uma pequena cidade precisa confrontar seu próprio passado quando a antiga quadrilha reaparece na região.',
    year: 1932,
    director: 'Robert N. Bradbury',
    genres: ['Faroeste', 'Clássico'],
    runtimeMinutes: 55,
    backdropUrl: 'https://archive.org/services/img/LawoftheWest',
    source: { provider: 'archive', id: 'LawoftheWest' },
    featured: false,
  },
  {
    title: 'Ride Ranger Ride',
    slug: 'ride-ranger-ride-1936',
    synopsis:
      'Um caubói cantor alistado na cavalaria dos EUA tenta evitar uma guerra desnecessária com uma tribo indígena que está sendo provocada por especuladores de terra interessados no conflito.',
    year: 1936,
    director: 'Joseph Kane',
    cast: ['Gene Autry'],
    genres: ['Faroeste', 'Clássico'],
    runtimeMinutes: 53,
    backdropUrl: 'https://archive.org/services/img/ride_ranger_ride',
    source: { provider: 'archive', id: 'ride_ranger_ride' },
    featured: false,
  },
  {
    title: 'The True Glory',
    slug: 'the-true-glory-1945',
    synopsis:
      'Documentário de guerra aliado montado a partir de imagens filmadas por centenas de cinegrafistas em combate, narrando a campanha na Europa desde o Dia D até a rendição da Alemanha.',
    year: 1945,
    director: 'Carol Reed, Garson Kanin',
    genres: ['Documentário', 'Clássico'],
    runtimeMinutes: 81,
    backdropUrl: 'https://archive.org/services/img/TrueGlory1945',
    source: { provider: 'archive', id: 'TrueGlory1945' },
    featured: false,
  },
  {
    title: 'The Battle of San Pietro',
    slug: 'the-battle-of-san-pietro-1945',
    synopsis:
      'Documentário de John Huston sobre a sangrenta batalha aliada para tomar o vilarejo italiano de San Pietro Infine das tropas alemãs entrincheiradas, filmado quase junto às linhas de combate.',
    year: 1945,
    director: 'John Huston',
    genres: ['Documentário', 'Clássico'],
    runtimeMinutes: 32,
    backdropUrl: 'https://archive.org/services/img/battle_of_san_pietro',
    source: { provider: 'archive', id: 'battle_of_san_pietro' },
    featured: false,
  },
  {
    title: 'Let There Be Light',
    slug: 'let-there-be-light-1946',
    synopsis:
      'Documentário de John Huston, censurado pelo Exército americano por décadas, acompanhando soldados da Segunda Guerra sendo tratados de traumas psicológicos num hospital militar.',
    year: 1946,
    director: 'John Huston',
    genres: ['Documentário', 'Clássico'],
    runtimeMinutes: 58,
    backdropUrl: 'https://archive.org/services/img/gov.ntis.ava04168vnb1',
    source: { provider: 'archive', id: 'gov.ntis.ava04168vnb1' },
    featured: false,
  },
  {
    title: 'Why We Fight: Prelude to War',
    slug: 'why-we-fight-prelude-to-war-1942',
    synopsis:
      'Primeiro episódio da série de propaganda de Frank Capra para o Departamento de Guerra dos EUA, contrastando nações democráticas e totalitárias para explicar aos soldados americanos por que o país entrou na Segunda Guerra.',
    year: 1942,
    director: 'Frank Capra',
    genres: ['Documentário', 'Clássico'],
    runtimeMinutes: 52,
    backdropUrl: 'https://archive.org/services/img/gov.fdr.44',
    source: { provider: 'archive', id: 'gov.fdr.44' },
    featured: false,
  },
  {
    title: 'Why We Fight: The Battle of Britain',
    slug: 'why-we-fight-the-battle-of-britain-1943',
    synopsis:
      'Parte da série "Why We Fight" de Frank Capra, narrando a resistência da força aérea britânica contra os bombardeios da Luftwaffe alemã em 1940.',
    year: 1943,
    director: 'Frank Capra, Anthony Veiller',
    genres: ['Documentário', 'Clássico'],
    runtimeMinutes: 52,
    backdropUrl: 'https://archive.org/services/img/wwf_the_battle_of_britain',
    source: { provider: 'archive', id: 'wwf_the_battle_of_britain' },
    featured: false,
  },
  {
    title: 'Know Your Enemy: Japan',
    slug: 'know-your-enemy-japan-1945',
    synopsis:
      'Documentário de propaganda produzido pelo Departamento de Guerra dos EUA para explicar aos soldados americanos a cultura e o militarismo japonês antes do combate no Pacífico.',
    year: 1945,
    genres: ['Documentário', 'Clássico'],
    runtimeMinutes: 63,
    backdropUrl: 'https://archive.org/services/img/KnowYourEnemyJapan',
    source: { provider: 'archive', id: 'KnowYourEnemyJapan' },
    featured: false,
  },
  {
    title: 'Target for Tonight',
    slug: 'target-for-tonight-1941',
    synopsis:
      'Docudrama britânico de guerra que acompanha, com militares reais no lugar de atores, uma tripulação de bombardeiro da RAF numa missão noturna sobre a Alemanha.',
    year: 1941,
    director: 'Harry Watt',
    genres: ['Documentário', 'Clássico'],
    runtimeMinutes: 48,
    backdropUrl: 'https://archive.org/services/img/TargetForTonight',
    source: { provider: 'archive', id: 'TargetForTonight' },
    featured: false,
  },
];
