// Décima primeira leva — drama, comédia e aventura em domínio público de
// estúdios independentes/poverty row (Monogram, PRC, Republic, produções
// da United Artists) e alguns clássicos mudos europeus. Encontrados via
// publicdomainmovie.net, freemoviescinema.com, emol.org e openculture.com
// (só os títulos que também existem no archive.org — títulos que só
// existiam no YouTube foram descartados, não embutimos vídeo do YouTube).
// source.id verificado manualmente na API do archive.org (duração real do
// arquivo de vídeo comparada com a duração conhecida do filme) antes de
// entrar aqui. A sinopse foi escrita em português a partir dos fatos do
// filme, sem reproduzir texto de terceiros.
module.exports = [
  {
    title: 'All Quiet on the Western Front',
    slug: 'all-quiet-on-the-western-front-1930',
    synopsis:
      'Um grupo de jovens estudantes alemães se alista com entusiasmo patriótico na Primeira Guerra Mundial e descobre, nas trincheiras, o horror real do combate. Vencedor do Oscar de melhor filme.',
    year: 1930,
    director: 'Lewis Milestone',
    genres: ['Drama', 'Clássico'],
    runtimeMinutes: 133,
    backdropUrl: 'https://archive.org/services/img/all-quiet-on-the-western-front-1930-film',
    source: { provider: 'archive', id: 'all-quiet-on-the-western-front-1930-film' },
    featured: false,
  },
  {
    title: 'Berlin: Symphony of a Great City',
    slug: 'berlin-symphony-of-a-great-city-1928',
    synopsis:
      'Documentário experimental alemão que retrata um dia inteiro na vida de Berlim, do amanhecer à noite, através de uma montagem rítmica de imagens do cotidiano da cidade, sem atores nem enredo tradicional.',
    year: 1928,
    director: 'Walther Ruttmann',
    genres: ['Documentário', 'Mudo', 'Clássico'],
    runtimeMinutes: 64,
    backdropUrl: 'https://archive.org/services/img/berlin-symphony-of-a-great-city_1928',
    source: { provider: 'archive', id: 'berlin-symphony-of-a-great-city_1928' },
    featured: false,
  },
  {
    title: 'The Passion of Joan of Arc',
    slug: 'the-passion-of-joan-of-arc-1928',
    synopsis:
      'Reconstituição do julgamento e execução de Joana d\'Arc, contada quase inteiramente em closes intensos do rosto da acusada, num dos marcos mais estudados da linguagem do cinema mudo.',
    year: 1928,
    director: 'Carl Theodor Dreyer',
    cast: ['Renée Jeanne Falconetti'],
    genres: ['Drama', 'Mudo', 'Clássico'],
    runtimeMinutes: 82,
    backdropUrl: 'https://archive.org/services/img/the-passion-of-joan-of-arc_202511',
    source: { provider: 'archive', id: 'the-passion-of-joan-of-arc_202511' },
    featured: false,
  },
  {
    title: 'My Man Godfrey',
    slug: 'my-man-godfrey-1936',
    synopsis:
      'Uma socialite excêntrica contrata, por capricho, um mendigo para ser o mordomo da família, sem saber que ele esconde um passado bem diferente do que aparenta, numa das comédias screwball mais celebradas da década de 1930.',
    year: 1936,
    director: 'Gregory La Cava',
    cast: ['William Powell', 'Carole Lombard'],
    genres: ['Comédia', 'Romance', 'Clássico'],
    runtimeMinutes: 95,
    backdropUrl: 'https://archive.org/services/img/MyManGodfrey1936',
    source: { provider: 'archive', id: 'MyManGodfrey1936' },
    featured: false,
  },
  {
    title: 'The Jungle Book',
    slug: 'the-jungle-book-1942',
    synopsis:
      'Adaptação em Technicolor dos contos de Rudyard Kipling sobre Mowgli, o menino criado por lobos na selva indiana, que precisa escolher entre a vida entre os animais e o retorno ao mundo dos homens.',
    year: 1942,
    director: 'Zoltan Korda',
    cast: ['Sabu'],
    genres: ['Aventura', 'Clássico'],
    runtimeMinutes: 105,
    backdropUrl: 'https://archive.org/services/img/JungleBook',
    source: { provider: 'archive', id: 'JungleBook' },
    featured: false,
  },
  {
    title: 'Jamaica Inn',
    slug: 'jamaica-inn-1939',
    synopsis:
      'Uma jovem órfã vai morar com a tia numa pousada isolada na costa da Cornualha e descobre que o local serve de esconderijo para uma quadrilha de saqueadores de navios naufragados. Último filme britânico de Alfred Hitchcock antes de ir para Hollywood.',
    year: 1939,
    director: 'Alfred Hitchcock',
    cast: ['Charles Laughton', 'Maureen O\'Hara'],
    genres: ['Suspense', 'Drama', 'Clássico'],
    runtimeMinutes: 99,
    backdropUrl: 'https://archive.org/services/img/Jamaica_Inn',
    source: { provider: 'archive', id: 'Jamaica_Inn' },
    featured: false,
  },
  {
    title: 'Little Lord Fauntleroy',
    slug: 'little-lord-fauntleroy-1936',
    synopsis:
      'Um garoto americano descobre que é herdeiro de um condado inglês e vai morar com o avô, um conde amargurado que aos poucos se abranda com a inocência e o carinho do neto.',
    year: 1936,
    director: 'John Cromwell',
    cast: ['Freddie Bartholomew', 'C. Aubrey Smith'],
    genres: ['Drama', 'Clássico'],
    runtimeMinutes: 101,
    backdropUrl: 'https://archive.org/services/img/little_lord_fauntleroy',
    source: { provider: 'archive', id: 'little_lord_fauntleroy' },
    featured: false,
  },
  {
    title: 'And Then There Were None',
    slug: 'and-then-there-were-none-1945',
    synopsis:
      'Adaptação do romance de Agatha Christie: dez desconhecidos são convidados para uma ilha isolada e começam a morrer, um a um, na ordem de uma cantiga infantil, revelando que o anfitrião oculto os está julgando por crimes do passado.',
    year: 1945,
    director: 'René Clair',
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 97,
    backdropUrl: 'https://archive.org/services/img/attwn994545112',
    source: { provider: 'archive', id: 'attwn994545112' },
    featured: false,
  },
  {
    title: 'Judge Priest',
    slug: 'judge-priest-1934',
    synopsis:
      'Num tribunal do interior do Kentucky, um juiz bondoso e cheio de manhas tenta absolver um jovem acusado injustamente enquanto lida com as tensões e tradições de sua pequena cidade sulista.',
    year: 1934,
    director: 'John Ford',
    cast: ['Will Rogers'],
    genres: ['Comédia', 'Drama', 'Clássico'],
    runtimeMinutes: 80,
    backdropUrl: 'https://archive.org/services/img/Judge_Priest',
    source: { provider: 'archive', id: 'Judge_Priest' },
    featured: false,
  },
  {
    title: 'A Farewell to Arms',
    slug: 'a-farewell-to-arms-1932-b',
    synopsis:
      'Adaptação do romance de Hemingway sobre o affair entre um ambulanciário americano e uma enfermeira inglesa durante a Primeira Guerra Mundial, separados repetidamente pelo caos do front italiano.',
    year: 1932,
    director: 'Frank Borzage',
    cast: ['Gary Cooper', 'Helen Hayes'],
    genres: ['Drama', 'Romance', 'Clássico'],
    runtimeMinutes: 78,
    backdropUrl: 'https://archive.org/services/img/farewell_to_arms_ipod',
    source: { provider: 'archive', id: 'farewell_to_arms_ipod' },
    featured: false,
  },
  {
    title: 'Angel on My Shoulder',
    slug: 'angel-on-my-shoulder-1946',
    synopsis:
      'Um gângster assassinado pelo próprio sócio é enviado ao inferno por engano e faz um trato com o Diabo para voltar à Terra no corpo de um juiz honesto, com a missão secreta de corromper sua reputação por dentro.',
    year: 1946,
    director: 'Archie Mayo',
    cast: ['Paul Muni'],
    genres: ['Comédia', 'Drama', 'Clássico'],
    runtimeMinutes: 101,
    backdropUrl: 'https://archive.org/services/img/angelOnMyShoulder',
    source: { provider: 'archive', id: 'angelOnMyShoulder' },
    featured: false,
  },
  {
    title: 'Beyond Tomorrow',
    slug: 'beyond-tomorrow-1940',
    synopsis:
      'Três sócios idosos e solitários morrem em um acidente na véspera de Natal, mas seus fantasmas ficam na Terra para ajudar o casal jovem que reuniram para jantar naquela noite a encontrar a felicidade.',
    year: 1940,
    director: 'A. Edward Sutherland',
    genres: ['Drama', 'Romance', 'Clássico'],
    runtimeMinutes: 84,
    backdropUrl: 'https://archive.org/services/img/Beyond_Tomorrow',
    source: { provider: 'archive', id: 'Beyond_Tomorrow' },
    featured: false,
  },
  {
    title: 'Mr. Robinson Crusoe',
    slug: 'mr-robinson-crusoe-1932',
    synopsis:
      'Um milionário aventureiro aposta que consegue viver sozinho numa ilha deserta do Pacífico sem nenhum equipamento moderno, numa versão livre e cheia de acrobacias do clássico de Daniel Defoe.',
    year: 1932,
    director: 'A. Edward Sutherland',
    cast: ['Douglas Fairbanks'],
    genres: ['Aventura', 'Comédia', 'Clássico'],
    runtimeMinutes: 71,
    backdropUrl: 'https://archive.org/services/img/MrRobinsonCrusoe',
    source: { provider: 'archive', id: 'MrRobinsonCrusoe' },
    featured: false,
  },
  {
    title: 'Speak Easily',
    slug: 'speak-easily-1932',
    synopsis:
      'Um professor universitário tímido e recluso é enganado por uma trupe de teatro decadente que o convence de que herdou uma fortuna, arrastando-o para uma sequência de confusões em cena e fora dela.',
    year: 1932,
    director: 'Edward Sedgwick',
    cast: ['Buster Keaton'],
    genres: ['Comédia', 'Clássico'],
    runtimeMinutes: 81,
    backdropUrl: 'https://archive.org/services/img/speak-easily-1932',
    source: { provider: 'archive', id: 'speak-easily-1932' },
    featured: false,
  },
  {
    title: 'College',
    slug: 'college-1927',
    synopsis:
      'Um estudante nerd que despreza esportes tenta se tornar um atleta da noite para o dia para impressionar a garota que gosta, numa sequência de tentativas desastradas em quase todas as modalidades do colégio.',
    year: 1927,
    director: 'James W. Horne',
    cast: ['Buster Keaton'],
    genres: ['Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 65,
    backdropUrl: 'https://archive.org/services/img/college',
    source: { provider: 'archive', id: 'college' },
    featured: false,
  },
  {
    title: 'The Time of Your Life',
    slug: 'the-time-of-your-life-1948',
    synopsis:
      'Adaptação da peça de William Saroyan: um bebedor filosófico observa e comenta a vida dos personagens que passam por um bar de San Francisco, entre eles um dono ameaçado por um chefão local.',
    year: 1948,
    director: 'H. C. Potter',
    cast: ['James Cagney'],
    genres: ['Drama', 'Comédia', 'Clássico'],
    runtimeMinutes: 101,
    backdropUrl: 'https://archive.org/services/img/TheTimeofyourLife',
    source: { provider: 'archive', id: 'TheTimeofyourLife' },
    featured: false,
  },
  {
    title: 'Three Broadway Girls',
    slug: 'three-broadway-girls-1932',
    synopsis:
      'Três golpistas se instalam num apartamento de luxo para caçar maridos ricos, mas os planos calculados de cada uma vão dando lugar a sentimentos reais mais complicados do que o previsto.',
    year: 1932,
    director: 'Lowell Sherman',
    cast: ['Joan Blondell'],
    genres: ['Comédia', 'Romance', 'Clássico'],
    runtimeMinutes: 79,
    backdropUrl: 'https://archive.org/services/img/Three_Broadway_Girls',
    source: { provider: 'archive', id: 'Three_Broadway_Girls' },
    featured: false,
  },
  {
    title: 'Eternally Yours',
    slug: 'eternally-yours-1939',
    synopsis:
      'A nova esposa de um mágico de sucesso tem dificuldade em aceitar a devoção obsessiva do marido pela carreira e pelas viagens constantes que ela exige, colocando o casamento à prova.',
    year: 1939,
    director: 'Tay Garnett',
    cast: ['Loretta Young', 'David Niven'],
    genres: ['Comédia', 'Romance', 'Clássico'],
    runtimeMinutes: 91,
    backdropUrl: 'https://archive.org/services/img/EternallyYours',
    source: { provider: 'archive', id: 'EternallyYours' },
    featured: false,
  },
  {
    title: 'Heartbeat',
    slug: 'heartbeat-1946',
    synopsis:
      'Uma jovem treinada por uma escola de batedores de carteira em Paris se apaixona por um diplomata durante um golpe e tenta esconder seu passado no submundo enquanto tenta deixá-lo para trás.',
    year: 1946,
    director: 'Sam Wood',
    cast: ['Ginger Rogers'],
    genres: ['Comédia', 'Romance', 'Clássico'],
    runtimeMinutes: 100,
    backdropUrl: 'https://archive.org/services/img/heartbeat',
    source: { provider: 'archive', id: 'heartbeat' },
    featured: false,
  },
  {
    title: 'Calendar Girl',
    slug: 'calendar-girl-1947',
    synopsis:
      'Na São Francisco do início do século 20, um grupo de amigos boêmios persegue romance e reconhecimento artístico na cena musical e teatral da cidade.',
    year: 1947,
    director: 'Allan Dwan',
    genres: ['Comédia', 'Romance', 'Clássico'],
    runtimeMinutes: 88,
    backdropUrl: 'https://archive.org/services/img/calendar_girl',
    source: { provider: 'archive', id: 'calendar_girl' },
    featured: false,
  },
  {
    title: 'Love Island',
    slug: 'love-island-1950',
    synopsis:
      'Um casal de turistas naufraga numa ilha tropical do Pacífico Sul e se envolve com os costumes e romances dos moradores locais, numa aventura filmada em Technicolor nos mares do sul.',
    year: 1950,
    director: 'Bud Pollard',
    genres: ['Aventura', 'Romance', 'Clássico'],
    runtimeMinutes: 62,
    backdropUrl: 'https://archive.org/services/img/love_island',
    source: { provider: 'archive', id: 'love_island' },
    featured: false,
  },
  {
    title: 'Sword of Lancelot',
    slug: 'sword-of-lancelot-1963',
    synopsis:
      'Recontando a lenda arturiana, narra o romance proibido entre Lancelot e a rainha Guinevere, e como essa traição contribui para a queda de Camelot.',
    year: 1963,
    director: 'Cornel Wilde',
    cast: ['Cornel Wilde'],
    genres: ['Aventura', 'Romance', 'Clássico'],
    runtimeMinutes: 117,
    backdropUrl: 'https://archive.org/services/img/cco_swordoflancelot',
    source: { provider: 'archive', id: 'cco_swordoflancelot' },
    featured: false,
  },
  {
    title: 'Hell Ship Mutiny',
    slug: 'hell-ship-mutiny-1957',
    synopsis:
      'Marinheiros contratados para entregar um carregamento de armas a uma ilha do Pacífico Sul se veem entre um comerciante trapaceiro e nativos hostis quando um motim se instala a bordo.',
    year: 1957,
    director: 'Lee Sholem, Elmo Williams',
    cast: ['Jon Hall', 'Peter Lorre'],
    genres: ['Aventura', 'Clássico'],
    runtimeMinutes: 65,
    backdropUrl: 'https://archive.org/services/img/HELLSHIPMUTINY1957JRJonHallPeterLorreSaltytheChimp2',
    source: { provider: 'archive', id: 'HELLSHIPMUTINY1957JRJonHallPeterLorreSaltytheChimp2' },
    featured: false,
  },
  {
    title: 'Dishonored Lady',
    slug: 'dishonored-lady-1947',
    synopsis:
      'Uma editora de revista de moda bem-sucedida, mas emocionalmente instável, tenta recomeçar a vida longe de antigos relacionamentos autodestrutivos, até ser acusada de um assassinato ligado ao seu passado.',
    year: 1947,
    director: 'Robert Stevenson',
    cast: ['Hedy Lamarr'],
    genres: ['Drama', 'Suspense', 'Clássico'],
    runtimeMinutes: 84,
    backdropUrl: 'https://archive.org/services/img/dishonored_lady',
    source: { provider: 'archive', id: 'dishonored_lady' },
    featured: false,
  },
  {
    title: 'The Green Glove',
    slug: 'the-green-glove-1952',
    synopsis:
      'Um ex-paraquedista americano volta à França para recuperar uma relíquia religiosa roubada durante a guerra, enfrentando um colaboracionista nazista que também quer o tesouro para si.',
    year: 1952,
    director: 'Rudolph Maté',
    cast: ['Glenn Ford'],
    genres: ['Aventura', 'Suspense', 'Clássico'],
    runtimeMinutes: 89,
    backdropUrl: 'https://archive.org/services/img/the_green_glove',
    source: { provider: 'archive', id: 'the_green_glove' },
    featured: false,
  },
  {
    title: 'Please Murder Me',
    slug: 'please-murder-me-1956',
    synopsis:
      'Um advogado consegue absolver a mulher que ama da acusação de matar o marido, só para descobrir depois provas de que ela era realmente culpada, e precisa lidar com as consequências de tê-la libertado.',
    year: 1956,
    director: 'Peter Godfrey',
    cast: ['Angela Lansbury', 'Raymond Burr'],
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 75,
    backdropUrl: 'https://archive.org/services/img/please-murder-me-1956',
    source: { provider: 'archive', id: 'please-murder-me-1956' },
    featured: false,
  },
  {
    title: 'The Big Cat',
    slug: 'the-big-cat-1949',
    synopsis:
      'Nas montanhas de Utah, dois criadores de ovelhas rivais precisam unir forças quando uma pantera selvagem passa a atacar os rebanhos de toda a região.',
    year: 1949,
    director: 'Phil Karlson',
    genres: ['Aventura', 'Drama', 'Clássico'],
    runtimeMinutes: 77,
    backdropUrl: 'https://archive.org/services/img/The_Big_Cat',
    source: { provider: 'archive', id: 'The_Big_Cat' },
    featured: false,
  },
  {
    title: 'Barefoot Boy',
    slug: 'barefoot-boy-1938',
    synopsis:
      'Um garoto do interior desenvolve uma amizade com um homem cego que mora sozinho na floresta, aprendendo lições sobre coragem e amizade ao longo de suas aventuras juntos.',
    year: 1938,
    director: 'Karl Brown',
    genres: ['Drama', 'Clássico'],
    runtimeMinutes: 60,
    backdropUrl: 'https://archive.org/services/img/barefoot_boy',
    source: { provider: 'archive', id: 'barefoot_boy' },
    featured: false,
  },
  {
    title: 'Paradise Isle',
    slug: 'paradise-isle-1937',
    synopsis:
      'Um pintor que está ficando cego viaja a uma ilha do Pacífico Sul para terminar sua última obra antes de perder a visão de vez, e se envolve com os moradores e as tensões locais.',
    year: 1937,
    director: 'Arthur Greville Collins',
    genres: ['Aventura', 'Romance', 'Clássico'],
    runtimeMinutes: 70,
    backdropUrl: 'https://archive.org/services/img/paradise_isle',
    source: { provider: 'archive', id: 'paradise_isle' },
    featured: false,
  },
  {
    title: 'Abe Lincoln of the Ninth Avenue',
    slug: 'abe-lincoln-of-the-ninth-avenue-1939',
    synopsis:
      'Um garoto pobre de Nova York apelidado de "Abe Lincoln" pelos colegas por sua honestidade precisa provar seu caráter quando é acusado injustamente de um roubo na vizinhança.',
    year: 1939,
    director: 'William Nigh',
    genres: ['Drama', 'Clássico'],
    runtimeMinutes: 64,
    backdropUrl: 'https://archive.org/services/img/abe_lincoln_of_the_4th_ave',
    source: { provider: 'archive', id: 'abe_lincoln_of_the_4th_ave' },
    featured: false,
  },
  {
    title: 'Africa Speaks',
    slug: 'africa-speaks-1930',
    synopsis:
      'Documentário de aventura acompanhando uma expedição de caça e exploração pela África Oriental, misturando registros de vida selvagem com encontros com povos e paisagens locais.',
    year: 1930,
    director: 'Walter Futter',
    genres: ['Documentário', 'Aventura', 'Clássico'],
    runtimeMinutes: 50,
    backdropUrl: 'https://archive.org/services/img/africa_speaks',
    source: { provider: 'archive', id: 'africa_speaks' },
    featured: false,
  },
  {
    title: 'A Romance of the Redwoods',
    slug: 'a-romance-of-the-redwoods-1917',
    synopsis:
      'Uma jovem do leste dos Estados Unidos viaja para se juntar ao tio nas florestas de sequoias da Califórnia e descobre, ao chegar, que ele morreu e sua identidade foi assumida por um fora da lei em fuga.',
    year: 1917,
    director: 'Cecil B. DeMille',
    cast: ['Mary Pickford'],
    genres: ['Drama', 'Romance', 'Mudo', 'Clássico'],
    runtimeMinutes: 91,
    backdropUrl: 'https://archive.org/services/img/ARomanceOfTheRedwoods',
    source: { provider: 'archive', id: 'ARomanceOfTheRedwoods' },
    featured: false,
  },
  {
    title: 'The Last of the Mohicans',
    slug: 'the-last-of-the-mohicans-1920',
    synopsis:
      'Adaptação muda do romance de James Fenimore Cooper: durante a Guerra Franco-Indígena, o batedor Olho de Falcão e seus aliados moicanos escoltam duas irmãs através da fronteira selvagem sob ameaça constante.',
    year: 1920,
    director: 'Maurice Tourneur, Clarence Brown',
    genres: ['Aventura', 'Mudo', 'Clássico'],
    runtimeMinutes: 71,
    backdropUrl: 'https://archive.org/services/img/last_of_the_mohicans_1920',
    source: { provider: 'archive', id: 'last_of_the_mohicans_1920' },
    featured: false,
  },
  {
    title: 'New Adventures of Tarzan',
    slug: 'new-adventures-of-tarzan-1935',
    synopsis:
      'Tarzan viaja à América Central para impedir que uma expedição inescrupulosa recupere um explosivo perdido escondido num templo maia, enfrentando traições dentro do próprio grupo.',
    year: 1935,
    director: 'Edward Kull',
    genres: ['Aventura', 'Clássico'],
    runtimeMinutes: 70,
    backdropUrl: 'https://archive.org/services/img/new_adventures_of_tarzan',
    source: { provider: 'archive', id: 'new_adventures_of_tarzan' },
    featured: false,
  },
  {
    title: 'Tarzan and the Green Goddess',
    slug: 'tarzan-and-the-green-goddess-1938',
    synopsis:
      'Recorte em longa do seriado "New Adventures of Tarzan": Tarzan protege um mapa gravado numa estátua sagrada que leva a um arsenal escondido, disputado por agentes internacionais.',
    year: 1938,
    director: 'Edward Kull',
    genres: ['Aventura', 'Clássico'],
    runtimeMinutes: 67,
    backdropUrl: 'https://archive.org/services/img/tarzan_and_the_green_goddess',
    source: { provider: 'archive', id: 'tarzan_and_the_green_goddess' },
    featured: false,
  },
  {
    title: 'The Amazing Quest of Ernest Bliss',
    slug: 'the-amazing-quest-of-ernest-bliss-1936',
    synopsis:
      'Um milionário entediado aposta com o médico que consegue viver um ano inteiro sustentando-se apenas do próprio trabalho, sem tocar em nenhum centavo da fortuna herdada.',
    year: 1936,
    director: 'Fred Zelnik',
    cast: ['Cary Grant'],
    genres: ['Comédia', 'Romance', 'Clássico'],
    runtimeMinutes: 62,
    backdropUrl: 'https://archive.org/services/img/amazing_adventure',
    source: { provider: 'archive', id: 'amazing_adventure' },
    featured: false,
  },
  {
    title: 'Marihuana',
    slug: 'marihuana-1936',
    synopsis:
      'Filme de exploração dos anos 30 que segue um grupo de jovens levados ao vício em maconha numa festa na praia, com consequências trágicas destinadas a servir de alerta moralista à época.',
    year: 1936,
    director: 'Dwain Esper',
    genres: ['Drama', 'Clássico'],
    runtimeMinutes: 57,
    backdropUrl: 'https://archive.org/services/img/Marihuana-the_Devils_Weed',
    source: { provider: 'archive', id: 'Marihuana-the_Devils_Weed' },
    featured: false,
  },
  {
    title: 'Lying Lips',
    slug: 'lying-lips-1939',
    synopsis:
      'Uma cantora de clube noturno é acusada injustamente de assassinar a própria tia e precisa provar sua inocência, num drama policial dirigido pelo pioneiro do cinema negro independente Oscar Micheaux.',
    year: 1939,
    director: 'Oscar Micheaux',
    genres: ['Drama', 'Suspense', 'Clássico'],
    runtimeMinutes: 68,
    backdropUrl: 'https://archive.org/services/img/lying_lips_ipod',
    source: { provider: 'archive', id: 'lying_lips_ipod' },
    featured: false,
  },
  {
    title: 'The Blood of Jesus',
    slug: 'the-blood-of-jesus-1941',
    synopsis:
      'Uma mulher ferida por acidente flutua entre a vida e a morte, e sua alma viaja por uma jornada simbólica entre o caminho da perdição e o da fé, num marco do cinema religioso afro-americano independente.',
    year: 1941,
    director: 'Spencer Williams',
    genres: ['Drama', 'Clássico'],
    runtimeMinutes: 57,
    backdropUrl: 'https://archive.org/services/img/blood_of_jesus',
    source: { provider: 'archive', id: 'blood_of_jesus' },
    featured: false,
  },
  {
    title: "Girl o' My Dreams",
    slug: 'girl-o-my-dreams-1934',
    synopsis:
      'Uma vidente de circo se apaixona por um repórter que investiga fraudes no mundo dos espetáculos itinerantes, e o romance precisa sobreviver à desconfiança gerada pelo ambiente em que ela trabalha.',
    year: 1934,
    director: 'Melville W. Brown',
    genres: ['Comédia', 'Romance', 'Clássico'],
    runtimeMinutes: 63,
    backdropUrl: 'https://archive.org/services/img/girl_o_my_dreams',
    source: { provider: 'archive', id: 'girl_o_my_dreams' },
    featured: false,
  },
  {
    title: 'Child Bride',
    slug: 'child-bride-1938',
    synopsis:
      'Filme de exploração ambientado nas montanhas dos Apalaches que denuncia, de forma sensacionalista, a prática de casamentos infantis na região, através da história de uma professora que tenta proteger uma aluna.',
    year: 1938,
    director: 'Harry Revier',
    genres: ['Drama', 'Clássico'],
    runtimeMinutes: 62,
    backdropUrl: 'https://archive.org/services/img/ChildBride',
    source: { provider: 'archive', id: 'ChildBride' },
    featured: false,
  },
  {
    title: 'A Man Betrayed',
    slug: 'a-man-betrayed-1936',
    synopsis:
      'Um homem condenado injustamente por um crime que não cometeu foge da prisão para provar sua inocência e desmascarar o verdadeiro culpado antes que a lei o alcance de novo.',
    year: 1936,
    director: 'Albert Herman',
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 53,
    backdropUrl: 'https://archive.org/services/img/ManBetrayed36',
    source: { provider: 'archive', id: 'ManBetrayed36' },
    featured: false,
  },
  {
    title: 'Call of the Yukon',
    slug: 'call-of-the-yukon-1938',
    synopsis:
      'Um escritor perdido na selva canadense é resgatado por um caçador solitário, e juntos enfrentam as adversidades do inverno ártico e um plano de sabotagem contra as reservas de caça da região.',
    year: 1938,
    director: 'B. Reeves Eason',
    genres: ['Aventura', 'Clássico'],
    runtimeMinutes: 67,
    backdropUrl: 'https://archive.org/services/img/call_of_the_yukon',
    source: { provider: 'archive', id: 'call_of_the_yukon' },
    featured: false,
  },
  {
    title: 'Atlantic Flight',
    slug: 'atlantic-flight-1937',
    synopsis:
      'Baseado em fatos reais: acompanha a organização e execução de um recorde de voo ao redor do mundo, celebrando o pioneirismo da aviação comercial americana nos anos 1930.',
    year: 1937,
    director: 'Arthur Lubin',
    genres: ['Drama', 'Aventura', 'Clássico'],
    runtimeMinutes: 59,
    backdropUrl: 'https://archive.org/services/img/AtlanticFlight',
    source: { provider: 'archive', id: 'AtlanticFlight' },
    featured: false,
  },
  {
    title: 'Aerial Gunner',
    slug: 'aerial-gunner-1943',
    synopsis:
      'Dois rivais de infância se reencontram no treinamento de artilheiros aéreos da força aérea americana durante a Segunda Guerra, precisando superar as diferenças antes de irem juntos para o combate.',
    year: 1943,
    director: 'William H. Pine',
    genres: ['Drama', 'Clássico'],
    runtimeMinutes: 79,
    backdropUrl: 'https://archive.org/services/img/aerial_gunner',
    source: { provider: 'archive', id: 'aerial_gunner' },
    featured: false,
  },
  {
    title: "Lil' Abner",
    slug: 'lil-abner-1940',
    synopsis:
      'Adaptação em live-action da tirinha de quadrinhos: os moradores caipiras do vilarejo fictício de Dogpatch se envolvem numa disputa cômica quando o governo ameaça transformar a cidade num campo de testes de bombas.',
    year: 1940,
    director: 'Albert S. Rogell',
    genres: ['Comédia', 'Clássico'],
    runtimeMinutes: 71,
    backdropUrl: 'https://archive.org/services/img/lil_abner',
    source: { provider: 'archive', id: 'lil_abner' },
    featured: false,
  },
  {
    title: 'Women in the Night',
    slug: 'women-in-the-night-1948',
    synopsis:
      'Durante a Segunda Guerra, um grupo de mulheres é forçado a trabalhar numa "casa de conforto" administrada por oficiais japoneses em Xangai, e planeja secretamente uma forma de resistência.',
    year: 1948,
    director: 'William Rowland',
    genres: ['Drama', 'Suspense', 'Clássico'],
    runtimeMinutes: 92,
    backdropUrl: 'https://archive.org/services/img/witn4477852',
    source: { provider: 'archive', id: 'witn4477852' },
    featured: false,
  },
  {
    title: 'Bluebeard',
    slug: 'bluebeard-1944',
    synopsis:
      'Em Paris, um pintor e mestre-marionetista carismático seduz mulheres para pintar seus retratos, mas todas as suas modelos acabam desaparecendo misteriosamente, num dos papéis mais aclamados de John Carradine.',
    year: 1944,
    director: 'Edgar G. Ulmer',
    cast: ['John Carradine'],
    genres: ['Terror', 'Suspense', 'Clássico'],
    runtimeMinutes: 71,
    backdropUrl: 'https://archive.org/services/img/Bluebeard',
    source: { provider: 'archive', id: 'Bluebeard' },
    featured: false,
  },
  {
    title: 'The North Star',
    slug: 'the-north-star-1943',
    synopsis:
      'Um vilarejo agrícola soviético perto da fronteira com a Ucrânia tem sua vida pacata interrompida pela invasão nazista de 1941, unindo os moradores numa resistência desesperada contra os invasores.',
    year: 1943,
    director: 'Lewis Milestone',
    cast: ['Anne Baxter', 'Dana Andrews'],
    genres: ['Drama', 'Clássico'],
    runtimeMinutes: 106,
    backdropUrl: 'https://archive.org/services/img/TheNorthStar',
    source: { provider: 'archive', id: 'TheNorthStar' },
    featured: false,
  },
  {
    title: 'International Crime',
    slug: 'international-crime-1938',
    synopsis:
      'Baseado no herói pulp "The Shadow": um comentarista de rádio que investiga crimes nas horas vagas precisa provar sua inocência depois de ser acusado de um assassinato que ele próprio estava investigando.',
    year: 1938,
    director: 'Charles Lamont',
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 64,
    backdropUrl: 'https://archive.org/services/img/international_crime',
    source: { provider: 'archive', id: 'international_crime' },
    featured: false,
  },
  {
    title: 'One Million B.C.',
    slug: 'one-million-b-c-1940',
    synopsis:
      'Um homem das cavernas de uma tribo rival da idade da pedra é aceito por outro clã depois de provar seu valor, e passa a lutar contra criaturas pré-históricas e forças da natureza para sobreviver e conquistar o amor de uma jovem da tribo.',
    year: 1940,
    director: 'Hal Roach, Hal Roach Jr.',
    cast: ['Victor Mature', 'Carole Landis'],
    genres: ['Aventura', 'Drama', 'Clássico'],
    runtimeMinutes: 80,
    backdropUrl: 'https://archive.org/services/img/one.million.b.c.1940',
    source: { provider: 'archive', id: 'one.million.b.c.1940' },
    featured: false,
  },
  {
    title: 'Night Tide',
    slug: 'night-tide-1961',
    synopsis:
      'Um marinheiro em licença se apaixona por uma mulher que trabalha como sereia numa atração de parque de diversões à beira-mar, e passa a suspeitar que ela pode acreditar ser, de fato, uma criatura sobrenatural.',
    year: 1961,
    director: 'Curtis Harrington',
    cast: ['Dennis Hopper'],
    genres: ['Suspense', 'Drama', 'Clássico'],
    runtimeMinutes: 85,
    backdropUrl: 'https://archive.org/services/img/NightTide1961',
    source: { provider: 'archive', id: 'NightTide1961' },
    featured: false,
  },
  {
    title: 'Star Wreck: In the Pirkinning',
    slug: 'star-wreck-in-the-pirkinning-2005',
    synopsis:
      'Produção amadora finlandesa distribuída gratuitamente pelos próprios criadores: os últimos sobreviventes de uma guerra futurista viajam ao passado numa paródia declarada de "Star Trek" e "Babylon 5".',
    year: 2005,
    director: 'Samuli Torssonen',
    genres: ['Ficção Científica', 'Comédia'],
    runtimeMinutes: 104,
    backdropUrl: 'https://archive.org/services/img/StarWreckInThePirkining',
    source: { provider: 'archive', id: 'StarWreckInThePirkining' },
    featured: false,
  },
];
