// Décima segunda leva — curtas de animação em domínio público (Betty Boop e
// Popeye da Fleischer/Paramount, Felix the Cat, Superman da Fleischer,
// Woody Woodpecker e Mighty Mouse), que complementam os curtas Disney/Warner
// já catalogados em bulkAnimations.js. Encontrados via publicdomainmovie.net
// e emol.org. source.id verificado manualmente na API do archive.org
// (duração real do arquivo de vídeo — nesse caso, curtas de fato têm
// poucos minutos, então o critério foi confirmar que o arquivo corresponde
// ao curta completo e não a um trecho cortado). A sinopse foi escrita em
// português a partir dos fatos de cada curta, sem reproduzir texto de
// terceiros.
module.exports = [
  {
    title: 'Betty Boop for President',
    slug: 'betty-boop-for-president-1932',
    synopsis: 'Betty Boop concorre à Presidência dos Estados Unidos com uma plataforma de campanha totalmente disparatada, numa sátira animada da eleição de 1932.',
    year: 1932,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/BettyBoopForPresident_629',
    source: { provider: 'archive', id: 'BettyBoopForPresident_629' },
    featured: false,
  },
  {
    title: 'Betty Boop: Chess Nuts',
    slug: 'betty-boop-chess-nuts-1932',
    synopsis: 'As peças de um tabuleiro de xadrez ganham vida numa batalha fantástica entre os reinos branco e preto, com Betty Boop no papel de rainha.',
    year: 1932,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/bb_chess_nuts',
    source: { provider: 'archive', id: 'bb_chess_nuts' },
    featured: false,
  },
  {
    title: "Betty Boop's Rise to Fame",
    slug: 'betty-boops-rise-to-fame-1934',
    synopsis: 'Um curta especial em formato de retrospectiva, celebrando a ascensão de Betty Boop ao estrelato com trechos e homenagens à trajetória da personagem.',
    year: 1934,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/bb_rise_to_fame',
    source: { provider: 'archive', id: 'bb_rise_to_fame' },
    featured: false,
  },
  {
    title: 'Betty Boop and Grampy',
    slug: 'betty-boop-and-grampy-1935',
    synopsis: 'Betty Boop pede ajuda ao inventivo Grampy para salvar uma festa que está prestes a ser um fracasso, usando geringonças malucas montadas com objetos do dia a dia.',
    year: 1935,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/bb_and_grampy',
    source: { provider: 'archive', id: 'bb_and_grampy' },
    featured: false,
  },
  {
    title: 'Betty Boop and the Little King',
    slug: 'betty-boop-and-the-little-king-1936',
    synopsis: 'Um encontro entre duas estrelas de tirinhas de jornal da Fleischer: Betty Boop cruza caminho com o desastrado personagem O Pequeno Rei numa aventura cômica.',
    year: 1936,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/bb_and_the_little_king',
    source: { provider: 'archive', id: 'bb_and_the_little_king' },
    featured: false,
  },
  {
    title: "Betty Boop's Big Boss",
    slug: 'betty-boops-big-boss-1933',
    synopsis: 'Betty Boop precisa lidar com o assédio de um chefe insistente no escritório onde trabalha, escapando dele em uma sequência de perseguições cômicas.',
    year: 1933,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/bb_big_boss',
    source: { provider: 'archive', id: 'bb_big_boss' },
    featured: false,
  },
  {
    title: 'Betty Boop: Bamboo Isle',
    slug: 'betty-boop-bamboo-isle-1932',
    synopsis: 'Betty Boop viaja a uma ilha havaiana e se junta aos moradores locais numa festa de dança e música tropical animada ao som de canções da época.',
    year: 1932,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/bb_bamboo_isle',
    source: { provider: 'archive', id: 'bb_bamboo_isle' },
    featured: false,
  },
  {
    title: 'Betty Boop: Betty in Blunderland',
    slug: 'betty-boop-betty-in-blunderland-1934',
    synopsis: 'Paródia animada de "Alice no País das Maravilhas": Betty Boop cai num mundo de fantasia repleto de personagens bizarros e situações sem lógica.',
    year: 1934,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/bb_betty_in_blunderland',
    source: { provider: 'archive', id: 'bb_betty_in_blunderland' },
    featured: false,
  },
  {
    title: 'Betty Boop: Happy You and Merry Me',
    slug: 'betty-boop-happy-you-and-merry-me-1936',
    synopsis: 'Betty Boop e seus amigos promovem uma festa animada para um grupo de brinquedos e objetos domésticos que ganham vida, embalada por músicas alegres.',
    year: 1936,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/bb_happy_you',
    source: { provider: 'archive', id: 'bb_happy_you' },
    featured: false,
  },
  {
    title: 'Betty Boop: House Cleaning Blues',
    slug: 'betty-boop-house-cleaning-blues-1937',
    synopsis: 'Betty Boop tenta convencer o namorado Freddie a ajudar na limpeza da casa, o que rende uma sequência de gags musicais sobre a resistência dele ao trabalho doméstico.',
    year: 1937,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/bb_house_cleaning_blues',
    source: { provider: 'archive', id: 'bb_house_cleaning_blues' },
    featured: false,
  },
  {
    title: "Betty Boop: I'll Be Glad When You're Dead, You Rascal You",
    slug: 'betty-boop-ill-be-glad-when-youre-dead-1932',
    synopsis: 'Betty Boop é perseguida por um leão faminto na selva, numa perseguição embalada pela música e pela performance rotoscopada do músico Louis Armstrong.',
    year: 1932,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/bb_ill_be_glad_when_youre_dead',
    source: { provider: 'archive', id: 'bb_ill_be_glad_when_youre_dead' },
    featured: false,
  },
  {
    title: 'Betty Boop: Minnie the Moocher',
    slug: 'betty-boop-minnie-the-moocher-1932-b',
    synopsis: 'Fugindo de casa depois de uma briga com os pais, Betty Boop se depara com um fantasma de morsa cuja voz e coreografia são baseadas na performance rotoscopada de Cab Calloway.',
    year: 1932,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/bb_minnie_the_moocher',
    source: { provider: 'archive', id: 'bb_minnie_the_moocher' },
    featured: false,
  },
  {
    title: 'Betty Boop: Musical Mountaineers',
    slug: 'betty-boop-musical-mountaineers-1939',
    synopsis: 'Betty Boop se apresenta com uma banda de música country nas montanhas, enfrentando a rivalidade cômica de outro grupo musical da região.',
    year: 1939,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/bb_musical_mountaineers',
    source: { provider: 'archive', id: 'bb_musical_mountaineers' },
    featured: false,
  },
  {
    title: 'Betty Boop: The Old Man of the Mountain',
    slug: 'betty-boop-the-old-man-of-the-mountain-1933',
    synopsis: 'Betty Boop se perde nas montanhas e encontra um eremita de voz grave e comportamento libidinoso, dublado pelo músico Cab Calloway.',
    year: 1933,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/bb_old_man_of_the_mountain',
    source: { provider: 'archive', id: 'bb_old_man_of_the_mountain' },
    featured: false,
  },
  {
    title: "Popeye's Pappy",
    slug: 'popeyes-pappy-1952',
    synopsis: 'Popeye sai à procura do pai que nunca conheceu, Poopdeck Pappy, e o encontra vivendo de trapaças, precisando resgatá-lo de suas próprias confusões.',
    year: 1952,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/PopeyeTheSailor-PopeyesPappy',
    source: { provider: 'archive', id: 'PopeyeTheSailor-PopeyesPappy' },
    featured: false,
  },
  {
    title: 'Patriotic Popeye',
    slug: 'patriotic-popeye-1957',
    synopsis: 'Popeye conta a Suzette histórias patrióticas da independência americana, reaproveitando trechos de curtas anteriores dentro de uma nova moldura narrativa.',
    year: 1957,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/popeye_patriotic_popeye',
    source: { provider: 'archive', id: 'popeye_patriotic_popeye' },
    featured: false,
  },
  {
    title: 'Popeye: Cooking with Gags',
    slug: 'popeye-cooking-with-gags-1954',
    synopsis: 'Popeye e Brutus disputam a atenção de Olívia Palito numa competição culinária cheia de gags visuais na cozinha.',
    year: 1954,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/Popeye_Cooking_With_Gags_1954',
    source: { provider: 'archive', id: 'Popeye_Cooking_With_Gags_1954' },
    featured: false,
  },
  {
    title: 'Popeye: Assault and Flattery',
    slug: 'popeye-assault-and-flattery-1956',
    synopsis: 'Brutus tenta conquistar Olívia Palito na base da bajulação exagerada, enquanto Popeye observa cético e acaba se metendo na disputa.',
    year: 1956,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/Popeye_Assault_and_Flattery_1956',
    source: { provider: 'archive', id: 'Popeye_Assault_and_Flattery_1956' },
    featured: false,
  },
  {
    title: 'Popeye: Taxi-Turvy',
    slug: 'popeye-taxi-turvy-1954',
    synopsis: 'Popeye e Brutus disputam corridas de táxi pela cidade tentando conquistar passageiros, numa sequência de perseguições e trapaças ao volante.',
    year: 1954,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/taxi-turvy',
    source: { provider: 'archive', id: 'taxi-turvy' },
    featured: false,
  },
  {
    title: 'Popeye: Greek Mirthology',
    slug: 'popeye-greek-mirthology-1954',
    synopsis: 'Popeye conta a Suzette uma versão cômica e distorcida de mitos da Grécia Antiga, se colocando como protagonista das aventuras heroicas.',
    year: 1954,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/GreekMirthology1954',
    source: { provider: 'archive', id: 'GreekMirthology1954' },
    featured: false,
  },
  {
    title: 'Popeye: Gopher Spinach',
    slug: 'popeye-gopher-spinach-1954',
    synopsis: 'Popeye e Brutus cavam em busca de um tesouro enterrado para impressionar Olívia Palito, mas um toupeira intrometido complica os planos dos dois.',
    year: 1954,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/Popeye_Gopher_Spinach_1954',
    source: { provider: 'archive', id: 'Popeye_Gopher_Spinach_1954' },
    featured: false,
  },
  {
    title: 'Popeye: Parlez Vous Woo',
    slug: 'popeye-parlez-vous-woo-1956',
    synopsis: 'Em Paris, Popeye e Brutus competem em francês pela atenção de Olívia Palito, misturando humor de idioma com a rivalidade de sempre entre os dois.',
    year: 1956,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/Popeye_Parlez_Vous_Woo_1956',
    source: { provider: 'archive', id: 'Popeye_Parlez_Vous_Woo_1956' },
    featured: false,
  },
  {
    title: 'Private Eye Popeye',
    slug: 'private-eye-popeye-1954',
    synopsis: 'Popeye trabalha como detetive particular contratado para proteger Olívia Palito, enquanto Brutus tenta atrapalhar a investigação por interesse próprio.',
    year: 1954,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/popeye_private_eye_popeye',
    source: { provider: 'archive', id: 'popeye_private_eye_popeye' },
    featured: false,
  },
  {
    title: 'Popeye the Sailor Man: Ancient Fistory',
    slug: 'popeye-ancient-fistory-1952',
    synopsis: 'Popeye conta uma versão cômica de sua própria história antiga para Suzette, reaproveitando gags clássicos numa narrativa de "era uma vez".',
    year: 1952,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/popeye_the_sailor_ancient_fantasy',
    source: { provider: 'archive', id: 'popeye_the_sailor_ancient_fantasy' },
    featured: false,
  },
  {
    title: 'Shuteye Popeye',
    slug: 'shuteye-popeye-1952',
    synopsis: 'Popeye tenta fazer Suzette dormir contando uma história de ninar, que se transforma na própria narrativa animada do curta.',
    year: 1952,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/shuteye_popeye',
    source: { provider: 'archive', id: 'shuteye_popeye' },
    featured: false,
  },
  {
    title: "Popeye: I Don't Scare",
    slug: 'popeye-i-dont-scare-1956',
    synopsis: 'Popeye enfrenta uma série de sustos numa casa mal-assombrada para provar a Brutus que nada é capaz de intimidá-lo.',
    year: 1956,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/popeye_i_dont_scare',
    source: { provider: 'archive', id: 'popeye_i_dont_scare' },
    featured: false,
  },
  {
    title: 'Popeye: The Paneless Window Washer',
    slug: 'popeye-the-paneless-window-washer-1937',
    synopsis: 'Popeye trabalha como limpador de janelas de arranha-céu e precisa lidar com Brutus tentando sabotar seu serviço a cada andar.',
    year: 1937,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/popeyepanelesswindowwasher',
    source: { provider: 'archive', id: 'popeyepanelesswindowwasher' },
    featured: false,
  },
  {
    title: 'Popeye: Bride and Gloom',
    slug: 'popeye-bride-and-gloom-1954',
    synopsis: 'Popeye e Brutus disputam a mão de Olívia Palito no altar, numa confusão de casamento que só termina depois de muita confusão física.',
    year: 1954,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/Popeye_BrideandGloom',
    source: { provider: 'archive', id: 'Popeye_BrideandGloom' },
    featured: false,
  },
  {
    title: 'Popeye the Sailor: Nearlyweds',
    slug: 'popeye-nearlyweds-1956',
    synopsis: 'Popeye e Olívia Palito quase chegam ao altar, mas Brutus intervém repetidamente para atrapalhar a cerimônia de casamento.',
    year: 1956,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/Popeye_Nearlyweds',
    source: { provider: 'archive', id: 'Popeye_Nearlyweds' },
    featured: false,
  },
  {
    title: 'Popeye: Fright to the Finish',
    slug: 'popeye-fright-to-the-finish-1954',
    synopsis: 'Popeye enfrenta um fantasma numa mansão assombrada para proteger Olívia Palito, descobrindo que o mistério pode ter uma explicação bem mais terrena.',
    year: 1954,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/popeye_fright_to_the_finish',
    source: { provider: 'archive', id: 'popeye_fright_to_the_finish' },
    featured: false,
  },
  {
    title: 'Popeye for President',
    slug: 'popeye-for-president-1956',
    synopsis: 'Popeye concorre à Presidência dos Estados Unidos contra Brutus, numa disputa eleitoral cheia de promessas exageradas e golpes baixos.',
    year: 1956,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/Popeye_forPresident',
    source: { provider: 'archive', id: 'Popeye_forPresident' },
    featured: false,
  },
  {
    title: 'Popeye the Sailor Meets Sindbad the Sailor',
    slug: 'popeye-meets-sindbad-the-sailor-1936',
    synopsis: 'Numa das produções mais ambiciosas da série, em cores e formato estendido, Popeye enfrenta o lendário Sinbad, o Marujo — na verdade Brutus disfarçado — numa ilha cheia de criaturas fantásticas.',
    year: 1936,
    genres: ['Animação', 'Comédia', 'Aventura', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/Popeye_meetsSinbadtheSailor',
    source: { provider: 'archive', id: 'Popeye_meetsSinbadtheSailor' },
    featured: false,
  },
  {
    title: 'Popeye: Floor Flusher',
    slug: 'popeye-floor-flusher-1954',
    synopsis: 'Popeye trabalha lavando pisos e precisa lidar com a bagunça constante causada por Brutus enquanto tenta terminar o serviço.',
    year: 1954,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/Popeye_Floor_Flusher_1954',
    source: { provider: 'archive', id: 'Popeye_Floor_Flusher_1954' },
    featured: false,
  },
  {
    title: 'Superman: The Mechanical Monsters',
    slug: 'superman-the-mechanical-monsters-1941',
    synopsis: 'Um cientista louco constrói robôs gigantes controlados a distância para roubar tesouros pela cidade, e cabe a Superman detê-los antes que o esquema avance ainda mais.',
    year: 1941,
    genres: ['Animação', 'Ficção Científica', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/the-mechanical-monsters-1941',
    source: { provider: 'archive', id: 'the-mechanical-monsters-1941' },
    featured: false,
  },
  {
    title: 'Superman: Electric Earthquake',
    slug: 'superman-electric-earthquake-1942',
    synopsis: 'Um vilão usa uma máquina capaz de provocar terremotos artificiais para chantagear a cidade, forçando Superman a impedir a destruição em massa.',
    year: 1942,
    genres: ['Animação', 'Ficção Científica', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/electric-earthquake-1942',
    source: { provider: 'archive', id: 'electric-earthquake-1942' },
    featured: false,
  },
  {
    title: 'Superman: Eleventh Hour',
    slug: 'superman-eleventh-hour-1942',
    synopsis: 'Superman precisa desvendar um plano de sabotagem envolvendo espiões estrangeiros a bordo de um navio, correndo contra o tempo para evitar um desastre.',
    year: 1942,
    genres: ['Animação', 'Ficção Científica', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/eleventh_hour',
    source: { provider: 'archive', id: 'eleventh_hour' },
    featured: false,
  },
  {
    title: 'Felix Doubles for Darwin',
    slug: 'felix-doubles-for-darwin-1924',
    synopsis: 'Felix, o Gato, é confundido com o elo perdido da evolução e passa a ser perseguido por cientistas ansiosos para provar a teoria de Darwin.',
    year: 1924,
    genres: ['Animação', 'Comédia', 'Mudo', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/Felix_DoublesforDarwin_NoAudio',
    source: { provider: 'archive', id: 'Felix_DoublesforDarwin_NoAudio' },
    featured: false,
  },
  {
    title: 'Felix Gets Broadcasted',
    slug: 'felix-gets-broadcasted-1923',
    synopsis: 'Felix, o Gato, se envolve numa aventura cômica em torno da então nova tecnologia do rádio, com direito a confusões de transmissão ao vivo.',
    year: 1923,
    genres: ['Animação', 'Comédia', 'Mudo', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/ptp_felix-gets-broadcast_otto-messmer_avi_xvid_768x576_179228',
    source: { provider: 'archive', id: 'ptp_felix-gets-broadcast_otto-messmer_avi_xvid_768x576_179228' },
    featured: false,
  },
  {
    title: 'Felix Lends a Hand',
    slug: 'felix-lends-a-hand-1922',
    synopsis: 'Felix, o Gato, tenta ajudar em casa e acaba causando uma sequência de pequenos desastres domésticos tipicamente cômicos da série muda.',
    year: 1922,
    genres: ['Animação', 'Comédia', 'Mudo', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/silent-felix-lends-a-hand',
    source: { provider: 'archive', id: 'silent-felix-lends-a-hand' },
    featured: false,
  },
  {
    title: 'Felix in Fairyland',
    slug: 'felix-in-fairyland-1923',
    synopsis: 'Felix, o Gato, entra num mundo de conto de fadas repleto de criaturas fantásticas, numa das aventuras mais imaginativas da série muda.',
    year: 1923,
    genres: ['Animação', 'Comédia', 'Mudo', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/ptp_felix-in-fairyland_otto-messmer_avi_xvid_768x576_179231',
    source: { provider: 'archive', id: 'ptp_felix-in-fairyland_otto-messmer_avi_xvid_768x576_179231' },
    featured: false,
  },
  {
    title: 'Felix in Hollywood',
    slug: 'felix-in-hollywood-1923',
    synopsis: 'Felix, o Gato, visita Hollywood e cruza caminho com caricaturas animadas de astros famosos do cinema mudo da época.',
    year: 1923,
    genres: ['Animação', 'Comédia', 'Mudo', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/Felix_inHollywood_NoAudio',
    source: { provider: 'archive', id: 'Felix_inHollywood_NoAudio' },
    featured: false,
  },
  {
    title: 'Felix the Ghost Breaker',
    slug: 'felix-the-ghost-breaker-1923',
    synopsis: 'Felix, o Gato, é contratado para investigar uma casa supostamente mal-assombrada e descobre que os "fantasmas" têm uma explicação bem mais terrena.',
    year: 1923,
    genres: ['Animação', 'Comédia', 'Mudo', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/FelixTheCat-FelixTheGhostBreaker1923',
    source: { provider: 'archive', id: 'FelixTheCat-FelixTheGhostBreaker1923' },
    featured: false,
  },
  {
    title: 'Felix the Cat: Two Lip Time',
    slug: 'felix-the-cat-two-lip-time-1926',
    synopsis: 'Felix, o Gato, viaja à Holanda e se envolve numa aventura cômica em meio a moinhos de vento e campos de tulipas.',
    year: 1926,
    genres: ['Animação', 'Comédia', 'Mudo', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/CartoonFelixTheCat1926TwoLipTime',
    source: { provider: 'archive', id: 'CartoonFelixTheCat1926TwoLipTime' },
    featured: false,
  },
  {
    title: 'Felix the Cat: April Maze',
    slug: 'felix-the-cat-april-maze-1930',
    synopsis: 'Felix, o Gato, é vítima de uma sequência de pegadinhas de Dia da Mentira armadas por seus vizinhos, e revida à sua própria maneira.',
    year: 1930,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/FelixAprilMaze',
    source: { provider: 'archive', id: 'FelixAprilMaze' },
    featured: false,
  },
  {
    title: 'Woody Woodpecker in Pantry Panic',
    slug: 'woody-woodpecker-in-pantry-panic-1941',
    synopsis: 'No auge do inverno, o Pica-Pau disputa com um gato faminto o controle da despensa de comida de uma cabana isolada.',
    year: 1941,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/woody_woodpecker_pantry_panic',
    source: { provider: 'archive', id: 'woody_woodpecker_pantry_panic' },
    featured: false,
  },
  {
    title: 'Mighty Mouse: Wolf! Wolf!',
    slug: 'mighty-mouse-wolf-wolf-1945',
    synopsis: 'As ovelhas de Mocinha Bo Peep são ameaçadas por lobos famintos, e cabe ao super-herói Mighty Mouse intervir para salvar o rebanho.',
    year: 1945,
    genres: ['Animação', 'Ficção Científica', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/mighty_mouse_wolf_wolf',
    source: { provider: 'archive', id: 'mighty_mouse_wolf_wolf' },
    featured: false,
  },
  {
    title: 'Little Swee’ Pea',
    slug: 'little-swee-pea-1936',
    synopsis: 'Popeye cuida do bebê Swee’Pea sozinho pela primeira vez e precisa dar um jeito nas travessuras da criança antes que a bagunça saia do controle.',
    year: 1936,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/little_sweepea',
    source: { provider: 'archive', id: 'little_sweepea' },
    featured: false,
  },
  {
    title: 'Now You’re Talking',
    slug: 'now-youre-talking-1927',
    synopsis: 'Curta de animação muda dos anos 1920 com uma sequência de gags visuais em torno de um dispositivo de comunicação improvisado.',
    year: 1927,
    genres: ['Animação', 'Comédia', 'Mudo', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/now_youre_talking_1927',
    source: { provider: 'archive', id: 'now_youre_talking_1927' },
    featured: false,
  },
  {
    title: "Santa's Surprise",
    slug: 'santas-surprise-1947',
    synopsis: 'Curta natalino de animação em que brinquedos ganham vida na oficina do Papai Noel na véspera de Natal.',
    year: 1947,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/SantasSuprise',
    source: { provider: 'archive', id: 'SantasSuprise' },
    featured: false,
  },
  {
    title: 'Destruction Inc.',
    slug: 'destruction-inc-1942',
    synopsis: 'Curta de animação de propaganda de guerra alertando trabalhadores da indústria americana sobre os perigos da sabotagem e do descuido durante a produção bélica.',
    year: 1942,
    genres: ['Animação', 'Documentário', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/destruction_inc',
    source: { provider: 'archive', id: 'destruction_inc' },
    featured: false,
  },
  {
    title: 'Showdown',
    slug: 'showdown-1942',
    synopsis: 'Curta de animação de propaganda da Segunda Guerra usando humor para incentivar a economia de recursos e o esforço de guerra na linha de frente doméstica.',
    year: 1942,
    genres: ['Animação', 'Documentário', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/showdown',
    source: { provider: 'archive', id: 'showdown' },
    featured: false,
  },
  {
    title: 'Secret Agent',
    slug: 'secret-agent-1943-animacao',
    synopsis: 'Curta de animação de propaganda de guerra usando humor para alertar sobre o risco de espiões inimigos disfarçados entre a população civil.',
    year: 1943,
    genres: ['Animação', 'Documentário', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/secret_agent',
    source: { provider: 'archive', id: 'secret_agent' },
    featured: false,
  },
  {
    title: 'Jack Frost',
    slug: 'jack-frost-1934',
    synopsis: 'Curta de animação sobre a chegada do inverno, personificado por Jack Frost, e seus efeitos sobre os animais da floresta se preparando para o frio.',
    year: 1934,
    genres: ['Animação', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/JackFrost_',
    source: { provider: 'archive', id: 'JackFrost_' },
    featured: false,
  },
  {
    title: 'Spree Lunch',
    slug: 'spree-lunch-1957',
    synopsis: 'Curta de animação cômico girando em torno de uma disputa por comida entre personagens famintos, no estilo clássico das produções de estúdio dos anos 1950.',
    year: 1957,
    genres: ['Animação', 'Comédia', 'Clássico'],
    backdropUrl: 'https://archive.org/services/img/spree_lunch',
    source: { provider: 'archive', id: 'spree_lunch' },
    featured: false,
  },
];
