// Décima terceira leva — curtas mudos de comédia (Chaplin, Keaton, Arbuckle,
// W.C. Fields e Stan Laurel) encontrados via publicdomainmovie.net,
// archivewatch.org e openculture.com. Boa parte desta leva corrige um bug do
// verificador automático (server/src/seed/tools/findCandidates.js): ele
// exigia 40 minutos de duração mínima pra qualquer item não marcado como
// "curta-metragem" — mas a maioria das fontes não preenche esse campo, então
// dezenas de curtas mudos legítimos (6 a 30 minutos, duração real da época)
// foram descartados por engano como "trailer/clipe". O limiar foi corrigido
// para 2 minutos flat (ver findCandidates.js) e esses curtas foram
// reavaliados manualmente contra o arquivo de vídeo real no archive.org
// antes de entrar aqui. Quando o mesmo curta aparecia sob dois identifiers
// diferentes (mais de uma fonte catalogou o mesmo filme separadamente), só
// um foi mantido. A sinopse foi escrita em português a partir dos fatos de
// cada curta, sem reproduzir texto de terceiros.
module.exports = [
  {
    title: 'A Film Johnnie',
    slug: 'a-film-johnnie-1914',
    synopsis:
      'Um fã obcecado por cinema invade um estúdio de filmagem para conhecer sua atriz favorita e acaba atrapalhando a produção de um filme, inclusive confundindo um incêndio de verdade com uma cena encenada.',
    year: 1914,
    director: 'George Nichols',
    cast: ['Charles Chaplin', 'Roscoe Arbuckle', 'Mabel Normand'],
    genres: ['Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 7,
    backdropUrl: 'https://archive.org/services/img/a-film-johnnie-1914',
    source: { provider: 'archive', id: 'a-film-johnnie-1914' },
    featured: false,
  },
  {
    title: 'Twenty Minutes of Love',
    slug: 'twenty-minutes-of-love-1914',
    synopsis:
      'Num parque público, um casal de namorados e um batedor de carteiras cruzam caminho com o Vagabundo, que se mete no meio da confusão tentando (sem sucesso) agir como herói. Considerado o primeiro filme dirigido pelo próprio Chaplin.',
    year: 1914,
    director: 'Charles Chaplin',
    cast: ['Charles Chaplin'],
    genres: ['Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 10,
    backdropUrl: 'https://archive.org/services/img/twenty-minutes-of-love-1914',
    source: { provider: 'archive', id: 'twenty-minutes-of-love-1914' },
    featured: false,
  },
  {
    title: 'Caught in a Cabaret',
    slug: 'caught-in-a-cabaret-1914',
    synopsis:
      'Um garçom se apaixona por uma moça rica e, pra impressioná-la, finge ser um diplomata estrangeiro — mentira que ameaça desmoronar quando ela e os amigos aparecem justamente no cabaré onde ele trabalha.',
    year: 1914,
    director: 'Mabel Normand',
    cast: ['Charles Chaplin', 'Mabel Normand'],
    genres: ['Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 16,
    backdropUrl: 'https://archive.org/services/img/caught-in-a-caberet-1914',
    source: { provider: 'archive', id: 'caught-in-a-caberet-1914' },
    featured: false,
  },
  {
    title: 'Cruel, Cruel Love',
    slug: 'cruel-cruel-love-1914',
    synopsis:
      'Rejeitado pela namorada após uma acusação injusta, um homem em desespero engana o próprio criado e bebe o que acredita ser veneno — só pra descobrir, tarde demais, que era apenas água misturada por engano.',
    year: 1914,
    director: 'George Nichols',
    cast: ['Charles Chaplin'],
    genres: ['Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 9,
    backdropUrl: 'https://archive.org/services/img/cruel-cruel-love-1914',
    source: { provider: 'archive', id: 'cruel-cruel-love-1914' },
    featured: false,
  },
  {
    title: 'A Busy Day',
    slug: 'a-busy-day-1914',
    synopsis:
      'Uma esposa ciumenta (Chaplin travestido) se mete no meio de um desfile ao flagrar o marido flertando com outra mulher, e a confusão vira uma perseguição caótica pelas ruas cheias de gente.',
    year: 1914,
    director: 'Mack Sennett',
    cast: ['Charles Chaplin', 'Mack Swain'],
    genres: ['Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 6,
    backdropUrl: 'https://archive.org/services/img/a-busy-day-1914',
    source: { provider: 'archive', id: 'a-busy-day-1914' },
    featured: false,
  },
  {
    title: "The Knockout",
    slug: 'the-knockout-1914',
    synopsis:
      'Um desajeitado se disfarça de pugilista profissional pra entrar num torneio de boxe e, contra todas as chances, precisa sobreviver a uma luta caótica cheia de golpes baixos e confusão no ringue.',
    year: 1914,
    director: 'Mack Sennett',
    cast: ['Roscoe Arbuckle', 'Charles Chaplin', 'Minta Durfee'],
    genres: ['Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 24,
    backdropUrl: 'https://archive.org/services/img/the-knockout-1914',
    source: { provider: 'archive', id: 'the-knockout-1914' },
    featured: false,
  },
  {
    title: "His Favorite Pastime",
    slug: 'his-favorite-pastime-1914',
    synopsis:
      'Depois de uma bebedeira num bar, o Vagabundo segue tropeçando atrás de uma mulher desconhecida até a casa dela, causando uma sequência de desastres domésticos diante do marido enfurecido.',
    year: 1914,
    director: 'George Nichols',
    cast: ['Charles Chaplin', 'Roscoe Arbuckle'],
    genres: ['Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 13,
    backdropUrl: 'https://archive.org/services/img/his-favorite-pasttime-1914',
    source: { provider: 'archive', id: 'his-favorite-pasttime-1914' },
    featured: false,
  },
  {
    title: 'His New Job',
    slug: 'his-new-job-1915',
    synopsis:
      'Primeiro filme de Chaplin já na Essanay: o Vagabundo consegue um emprego de faz-tudo num estúdio de cinema e transforma a filmagem de um drama em desastre atrás de desastre.',
    year: 1915,
    director: 'Charles Chaplin',
    cast: ['Charles Chaplin', 'Ben Turpin'],
    genres: ['Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 29,
    backdropUrl: 'https://archive.org/services/img/silent-his-new-job',
    source: { provider: 'archive', id: 'silent-his-new-job' },
    featured: false,
  },
  {
    title: 'A Night in the Show',
    slug: 'a-night-in-the-show-1915',
    synopsis:
      'Chaplin interpreta dois espectadores diferentes — um cavalheiro embriagado na plateia nobre e um desordeiro no galinheiro — que juntos transformam a apresentação de um teatro de variedades num caos completo.',
    year: 1915,
    director: 'Charles Chaplin',
    cast: ['Charles Chaplin'],
    genres: ['Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 18,
    backdropUrl: 'https://archive.org/services/img/ANightintheShow',
    source: { provider: 'archive', id: 'ANightintheShow' },
    featured: false,
  },
  {
    title: 'Charlie Shanghaied',
    slug: 'charlie-shanghaied-1915',
    synopsis:
      'A bordo de um navio, o cozinheiro Vagabundo descobre que o capitão planeja fazê-lo de bode expiatório e "sequestrá-lo" para o mar em troca de um seguro — e precisa escapar antes que o plano se concretize.',
    year: 1915,
    director: 'Charles Chaplin',
    cast: ['Charles Chaplin', 'Edna Purviance'],
    genres: ['Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 23,
    backdropUrl: 'https://archive.org/services/img/CC_1915_10_04_CharlieShanghaied',
    source: { provider: 'archive', id: 'CC_1915_10_04_CharlieShanghaied' },
    featured: false,
  },
  {
    title: 'Police',
    slug: 'police-1916',
    synopsis:
      'Recém-solto da prisão, o Vagabundo tenta recomeçar a vida, mas é atraído de volta ao crime por um ex-companheiro de cela que planeja assaltar uma casa — até que a consciência (e uma reviravolta) mudam o rumo da noite.',
    year: 1916,
    director: 'Charles Chaplin',
    cast: ['Charles Chaplin', 'Edna Purviance'],
    genres: ['Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 26,
    backdropUrl: 'https://archive.org/services/img/vidpol',
    source: { provider: 'archive', id: 'vidpol' },
    featured: false,
  },
  {
    title: 'The Champion',
    slug: 'the-champion-1915',
    synopsis:
      'Um vagabundo faminto encontra emprego como parceiro de treino de um boxeador e, com a ajuda de uma ferradura escondida na luva, acaba tendo a chance de disputar o título — se sobreviver ao ringue.',
    year: 1915,
    director: 'Charles Chaplin',
    cast: ['Charles Chaplin', 'Edna Purviance', 'Broncho Billy Anderson'],
    genres: ['Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 31,
    backdropUrl: 'https://archive.org/services/img/TheChampion',
    source: { provider: 'archive', id: 'TheChampion' },
    featured: false,
  },
  {
    title: 'The Bank',
    slug: 'the-bank-1915',
    synopsis:
      'Um faxineiro de banco sonha em ser o herói que impede um assalto e conquista o coração da secretária — mas a linha entre o sonho e a realidade só fica clara no fim, numa das comédias mais melancólicas do início de Chaplin.',
    year: 1915,
    director: 'Charles Chaplin',
    cast: ['Charles Chaplin', 'Edna Purviance'],
    genres: ['Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 25,
    backdropUrl: 'https://archive.org/services/img/1915bank',
    source: { provider: 'archive', id: '1915bank' },
    featured: false,
  },
  {
    title: 'A Jitney Elopement',
    slug: 'a-jitney-elopement-1915',
    synopsis:
      'Pra livrar a namorada de um casamento arranjado, o Vagabundo se passa por um conde estrangeiro diante do pai dela — disfarce que dura pouco quando o conde de verdade aparece, dando início a uma perseguição de carro pela cidade.',
    year: 1915,
    director: 'Charles Chaplin',
    cast: ['Charles Chaplin', 'Edna Purviance'],
    genres: ['Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 26,
    backdropUrl: 'https://archive.org/services/img/AJitneyElopement',
    source: { provider: 'archive', id: 'AJitneyElopement' },
    featured: false,
  },
  {
    title: 'Triple Trouble',
    slug: 'triple-trouble-1918',
    synopsis:
      'Montado anos depois a partir de sobras de filmagens inacabadas da Essanay, o curta junta o Vagabundo como zelador de uma pensão a uma trama de espiões estrangeiros e uma bomba escondida, resultando numa colcha de retalhos cômica.',
    year: 1918,
    director: 'Charles Chaplin',
    cast: ['Charles Chaplin', 'Edna Purviance'],
    genres: ['Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 27,
    backdropUrl: 'https://archive.org/services/img/CC_1918_xx_xx_TripleTrouble',
    source: { provider: 'archive', id: 'CC_1918_xx_xx_TripleTrouble' },
    featured: false,
  },
  {
    title: 'The Goat',
    slug: 'the-goat-1921',
    synopsis:
      'Depois de ser fotografado por engano no lugar de um assassino procurado, um jovem sem sorte vira alvo de toda a polícia da cidade, numa sucessão de perseguições e escapadas cada vez mais absurdas.',
    year: 1921,
    director: 'Buster Keaton',
    cast: ['Buster Keaton'],
    genres: ['Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 23,
    backdropUrl: 'https://archive.org/services/img/TheGoat',
    source: { provider: 'archive', id: 'TheGoat' },
    featured: false,
  },
  {
    title: "My Wife's Relations",
    slug: 'my-wifes-relations-1922',
    synopsis:
      'Um mal-entendido no tribunal deixa Keaton casado à força com uma mulher enorme e temperamental, obrigando-o a se mudar pra casa da família dela — uma casa cheia de parentes hostis que não falam sua língua.',
    year: 1922,
    director: 'Buster Keaton',
    cast: ['Buster Keaton'],
    genres: ['Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 24,
    backdropUrl: 'https://archive.org/services/img/MyWifesRelations1922',
    source: { provider: 'archive', id: 'MyWifesRelations1922' },
    featured: false,
  },
  {
    title: 'The Paleface',
    slug: 'the-paleface-1922',
    synopsis:
      'Capturado por uma tribo indígena que planeja queimá-lo no poste, um caçador de borboletas sobrevive graças a uma roupa íntima à prova de fogo e acaba se tornando aliado deles contra especuladores que querem roubar suas terras ricas em petróleo.',
    year: 1922,
    director: 'Buster Keaton',
    cast: ['Buster Keaton'],
    genres: ['Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 21,
    backdropUrl: 'https://archive.org/services/img/ThePaleface',
    source: { provider: 'archive', id: 'ThePaleface' },
    featured: false,
  },
  {
    title: 'The Electric House',
    slug: 'the-electric-house-1922',
    synopsis:
      'Após uma troca de diplomas na formatura, um estudante de botânica é contratado por engano para eletrificar a casa de uma família rica — e enche a mansão de invenções amadoras que dão terrivelmente errado.',
    year: 1922,
    director: 'Buster Keaton',
    cast: ['Buster Keaton'],
    genres: ['Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 20,
    backdropUrl: 'https://archive.org/services/img/TheElectricHouse',
    source: { provider: 'archive', id: 'TheElectricHouse' },
    featured: false,
  },
  {
    title: 'Daydreams',
    slug: 'daydreams-1922',
    synopsis:
      'Pra provar seu valor ao pai da namorada, um rapaz vai para a cidade grande em busca de sucesso e encadeia uma série de empregos desastrosos, escrevendo cartas cada vez mais exageradas sobre seu suposto progresso.',
    year: 1922,
    director: 'Buster Keaton',
    cast: ['Buster Keaton'],
    genres: ['Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 18,
    backdropUrl: 'https://archive.org/services/img/Daydreams',
    source: { provider: 'archive', id: 'Daydreams' },
    featured: false,
  },
  {
    title: 'Neighbors',
    slug: 'neighbors-1920',
    synopsis:
      'Dois vizinhos brigados dividem um quintal e uma cerca, mas isso não impede que seus filhos se apaixonem — o que leva a uma sequência de acrobacias pela janela e por cima do muro pra manter o romance em segredo.',
    year: 1920,
    director: 'Buster Keaton',
    cast: ['Buster Keaton'],
    genres: ['Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 18,
    backdropUrl: 'https://archive.org/services/img/Neighbors1920',
    source: { provider: 'archive', id: 'Neighbors1920' },
    featured: false,
  },
  {
    title: 'Three Ages',
    slug: 'three-ages-1923',
    synopsis:
      'Uma paródia direta de "Intolerância" de Griffith: três histórias paralelas do mesmo triângulo amoroso — na Idade da Pedra, na Roma Antiga e nos anos 1920 — mostram Keaton disputando a mesma garota através dos séculos.',
    year: 1923,
    director: 'Buster Keaton',
    cast: ['Buster Keaton', 'Wallace Beery'],
    genres: ['Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 64,
    backdropUrl: 'https://archive.org/services/img/Silent_ThreeAges_1923',
    source: { provider: 'archive', id: 'Silent_ThreeAges_1923' },
    featured: false,
  },
  {
    title: 'Love Nest',
    slug: 'love-nest-1923',
    synopsis:
      'À deriva no mar após um desgosto amoroso, Keaton é resgatado por um navio comandado por um capitão tirânico que despacha marinheiros pela amurada ao menor deslize — e ele precisa driblar a bordo pra sobreviver.',
    year: 1923,
    director: 'Buster Keaton',
    cast: ['Buster Keaton'],
    genres: ['Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 22,
    backdropUrl: 'https://archive.org/services/img/LoveNest',
    source: { provider: 'archive', id: 'LoveNest' },
    featured: false,
  },
  {
    title: 'Scarecrow',
    slug: 'scarecrow-1920',
    synopsis:
      'Dois colegas de casa numa fazenda disputam o coração da mesma vizinha, num curta cheio de engenhocas domésticas que transformam a cabana apertada dos dois numa máquina de morar multiuso.',
    year: 1920,
    director: 'Buster Keaton',
    cast: ['Buster Keaton', 'Sybil Seely'],
    genres: ['Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 20,
    backdropUrl: 'https://archive.org/services/img/BusterKeatonthescarecrow',
    source: { provider: 'archive', id: 'BusterKeatonthescarecrow' },
    featured: false,
  },
  {
    title: 'The Butcher Boy',
    slug: 'the-butcher-boy-1917',
    synopsis:
      'Numa mercearia general store, um rival provoca uma guerra de melado e farinha, e um jovem disfarçado de garota tenta se infiltrar num internato feminino nas cenas finais. Marca a estreia de Buster Keaton no cinema, contracenando com Arbuckle.',
    year: 1917,
    director: 'Roscoe Arbuckle',
    cast: ['Roscoe Arbuckle', 'Buster Keaton', 'Al St. John'],
    genres: ['Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 24,
    backdropUrl: 'https://archive.org/services/img/busterkeatonthebutcherboy',
    source: { provider: 'archive', id: 'busterkeatonthebutcherboy' },
    featured: false,
  },
  {
    title: 'The Bell Boy',
    slug: 'the-bell-boy-1918',
    synopsis:
      'Dois carregadores desastrados de um hotel de beira de estrada se envolvem numa sucessão de encrencas com hóspedes difíceis, um gigante barbeiro e uma tentativa de assalto ao banco vizinho.',
    year: 1918,
    director: 'Roscoe Arbuckle',
    cast: ['Roscoe Arbuckle', 'Buster Keaton', 'Al St. John'],
    genres: ['Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 29,
    backdropUrl: 'https://archive.org/services/img/bellboy',
    source: { provider: 'archive', id: 'bellboy' },
    featured: false,
  },
  {
    title: 'Coney Island',
    slug: 'coney-island-1917',
    synopsis:
      'Dois amigos escapam das esposas por um dia no parque de diversões de Coney Island, onde disputam a atenção da mesma moça em meio a piscinas, brigas de banho e uma confusão generalizada.',
    year: 1917,
    director: 'Roscoe Arbuckle',
    cast: ['Roscoe Arbuckle', 'Buster Keaton', 'Al St. John'],
    genres: ['Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 25,
    backdropUrl: 'https://archive.org/services/img/ConeyIsland_17',
    source: { provider: 'archive', id: 'ConeyIsland_17' },
    featured: false,
  },
  {
    title: 'Good Night, Nurse!',
    slug: 'good-night-nurse-1918',
    synopsis:
      'Pressionado pela esposa a parar de beber, um homem se interna num sanatório de tratamento contra o álcool que esconde um médico nada confiável — e ele precisa escapar antes de virar cobaia de uma cirurgia desnecessária.',
    year: 1918,
    director: 'Roscoe Arbuckle',
    cast: ['Roscoe Arbuckle', 'Buster Keaton'],
    genres: ['Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 24,
    backdropUrl: 'https://archive.org/services/img/silent-good-night-nurse',
    source: { provider: 'archive', id: 'silent-good-night-nurse' },
    featured: false,
  },
  {
    title: "His Wedding Night",
    slug: 'his-wedding-night-1917',
    synopsis:
      'Um balconista de farmácia prestes a se casar se envolve numa confusão de disfarces e trocas de identidade na noite anterior ao casamento, ameaçando arruinar a cerimônia do dia seguinte.',
    year: 1917,
    director: 'Roscoe Arbuckle',
    cast: ['Roscoe Arbuckle', 'Buster Keaton', 'Al St. John'],
    genres: ['Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 20,
    backdropUrl: 'https://archive.org/services/img/silent-his-wedding-night',
    source: { provider: 'archive', id: 'silent-his-wedding-night' },
    featured: false,
  },
  {
    title: 'The Rough House',
    slug: 'the-rough-house-1917',
    synopsis:
      'Um incêndio na cozinha causado por um cozinheiro desastrado é só o começo de um dia caótico numa casa de família, que ainda inclui um jardineiro trapalhão e um ladrão à espreita.',
    year: 1917,
    director: 'Roscoe Arbuckle',
    cast: ['Roscoe Arbuckle', 'Buster Keaton', 'Al St. John'],
    genres: ['Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 19,
    backdropUrl: 'https://archive.org/services/img/Silent_TheRoughHouse_1917',
    source: { provider: 'archive', id: 'Silent_TheRoughHouse_1917' },
    featured: false,
  },
  {
    title: 'Pool Sharks',
    slug: 'pool-sharks-1915',
    synopsis:
      'Dois pretendentes rivais da mesma moça acabam a disputa numa mesa de bilhar, com direito a uma sequência de trucagem em stop-motion nas bolas do jogo. Primeiro filme da carreira de W.C. Fields.',
    year: 1915,
    director: 'Edwin Middleton',
    cast: ['W.C. Fields'],
    genres: ['Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 10,
    backdropUrl: 'https://archive.org/services/img/pool_sharks',
    source: { provider: 'archive', id: 'pool_sharks' },
    featured: false,
  },
  {
    title: 'The Dentist',
    slug: 'the-dentist-1932',
    synopsis:
      'Um dentista mal-humorado descarrega a raiva de uma manhã ruim em cada paciente que senta em sua cadeira, numa sucessão de gags absurdamente violentos que se tornaram um clássico do humor cruel de W.C. Fields.',
    year: 1932,
    director: 'Leslie Pearce',
    cast: ['W.C. Fields'],
    genres: ['Comédia', 'Clássico'],
    runtimeMinutes: 21,
    backdropUrl: 'https://archive.org/services/img/W.c.Fields-TheDentist',
    source: { provider: 'archive', id: 'W.c.Fields-TheDentist' },
    featured: false,
  },
  {
    title: 'West of Hot Dog',
    slug: 'west-of-hot-dog-1924',
    synopsis:
      'Numa cidadela do velho oeste, um caubói desastrado se vê no meio de duelos, assaltos e um romance complicado, numa paródia dos faroestes da época estrelada por Stan Laurel antes de sua dupla com Oliver Hardy.',
    year: 1924,
    director: 'George Jeske',
    cast: ['Stan Laurel'],
    genres: ['Comédia', 'Mudo', 'Faroeste', 'Clássico'],
    runtimeMinutes: 31,
    backdropUrl: 'https://archive.org/services/img/westofhotdog',
    source: { provider: 'archive', id: 'westofhotdog' },
    featured: false,
  },
  {
    title: 'War Babies',
    slug: 'war-babies-1932',
    synopsis:
      'Crianças interpretando adultos numa saloon de fronteira durante uma guerra fictícia, numa das curtas-metragens "Baby Burlesks" que satirizavam dramas e romances de Hollywood com um elenco infantil — entre eles, uma Shirley Temple ainda bebê.',
    year: 1932,
    director: 'Charles Lamont',
    cast: ['Shirley Temple'],
    genres: ['Comédia', 'Clássico'],
    runtimeMinutes: 9,
    backdropUrl: 'https://archive.org/services/img/WarBabies',
    source: { provider: 'archive', id: 'WarBabies' },
    featured: false,
  },
];
