// Nona leva — terror e ficção científica B em domínio público (estúdios
// poverty row como Monogram, PRC e produções independentes dos anos 30 a
// 60), mais um punhado de terror mudo dos anos 1920. Encontrados via
// publicdomainmovie.net, freemoviescinema.com e archivewatch.org.
// source.id verificado manualmente na API do archive.org (duração real do
// arquivo de vídeo comparada com a duração conhecida do filme) antes de
// entrar aqui. A sinopse foi escrita em português a partir dos fatos do
// filme, sem reproduzir texto de terceiros.
module.exports = [
  {
    title: 'Robot Monster',
    slug: 'robot-monster-1953',
    synopsis:
      'Um alienígena vestido numa fantasia de gorila com capacete de mergulho, armado com um raio que faz bolhas de sabão, dizima quase toda a humanidade e agora caça a família sobrevivente. Ícone do cinema trash de baixíssimo orçamento dos anos 50.',
    year: 1953,
    director: 'Phil Tucker',
    genres: ['Ficção Científica', 'Clássico'],
    runtimeMinutes: 62,
    backdropUrl: 'https://archive.org/services/img/robot-monster-1953-colorized-movie-576p-sd',
    source: { provider: 'archive', id: 'robot-monster-1953-colorized-movie-576p-sd' },
    featured: false,
  },
  {
    title: 'Killers from Space',
    slug: 'killers-from-space-1954',
    synopsis:
      'Um cientista dado como morto num acidente aéreo reaparece com um comportamento estranho: na verdade foi capturado e hipnotizado por alienígenas que planejam uma invasão subterrânea e o usam para roubar segredos nucleares.',
    year: 1954,
    director: 'W. Lee Wilder',
    cast: ['Peter Graves'],
    genres: ['Ficção Científica', 'Clássico'],
    runtimeMinutes: 71,
    backdropUrl: 'https://archive.org/services/img/KillersFromSpace',
    source: { provider: 'archive', id: 'KillersFromSpace' },
    featured: false,
  },
  {
    title: 'Missile to the Moon',
    slug: 'missile-to-the-moon-1958',
    synopsis:
      'Dois presidiários fugitivos sequestram o foguete experimental de um cientista e, junto com outros passageiros acidentais, vão parar na Lua, onde encontram uma civilização subterrânea de mulheres governada por uma rainha.',
    year: 1958,
    director: 'Richard E. Cunha',
    genres: ['Ficção Científica', 'Clássico'],
    runtimeMinutes: 77,
    backdropUrl: 'https://archive.org/services/img/missile-to-the-moon-1958_202109',
    source: { provider: 'archive', id: 'missile-to-the-moon-1958_202109' },
    featured: false,
  },
  {
    title: 'Attack from Space',
    slug: 'attack-from-space-1965',
    synopsis:
      'Recorte de um seriado japonês de super-herói montado como longa para o público americano: um guerreiro do espaço enfrenta o Império Espial numa cruzada para proteger a Terra.',
    year: 1965,
    genres: ['Ficção Científica', 'Clássico'],
    runtimeMinutes: 76,
    backdropUrl: 'https://archive.org/services/img/AttackFromSpace_201510',
    source: { provider: 'archive', id: 'AttackFromSpace_201510' },
    featured: false,
  },
  {
    title: 'Assignment Outer Space',
    slug: 'assignment-outer-space-1960',
    synopsis:
      'Um jornalista em estágio numa estação espacial do futuro se vê no comando de uma missão de resgate quando a tripulação de uma nave com um reator instável entra em pânico, ameaçando destruir a Terra.',
    year: 1960,
    director: 'Antonio Margheriti',
    genres: ['Ficção Científica', 'Clássico'],
    runtimeMinutes: 73,
    backdropUrl: 'https://archive.org/services/img/AssignmentOuterSpace',
    source: { provider: 'archive', id: 'AssignmentOuterSpace' },
    featured: false,
  },
  {
    title: 'Atom Age Vampire',
    slug: 'atom-age-vampire-1960',
    synopsis:
      'Um cientista italiano desenvolve um soro capaz de regenerar tecido humano para salvar o rosto desfigurado de uma dançarina, mas precisa matar mulheres para extrair a substância necessária, transformando-se ele mesmo num monstro.',
    year: 1960,
    director: 'Anton Giulio Majano',
    genres: ['Ficção Científica', 'Terror', 'Clássico'],
    runtimeMinutes: 86,
    backdropUrl: 'https://archive.org/services/img/AtomAgeVampire',
    source: { provider: 'archive', id: 'AtomAgeVampire' },
    featured: false,
  },
  {
    title: 'The Incredible Petrified World',
    slug: 'the-incredible-petrified-world-1957',
    synopsis:
      'Quatro exploradores testando um novo sino de mergulho ficam presos no fundo do oceano após um acidente e descobrem um sistema de cavernas subterrâneas repleto de perigos, enquanto tentam encontrar uma saída.',
    year: 1957,
    director: 'Jerry Warren',
    cast: ['John Carradine'],
    genres: ['Ficção Científica', 'Clássico'],
    runtimeMinutes: 63,
    backdropUrl: 'https://archive.org/services/img/TheIncrediblePetrifiedWorld',
    source: { provider: 'archive', id: 'TheIncrediblePetrifiedWorld' },
    featured: false,
  },
  {
    title: 'The Yesterday Machine',
    slug: 'the-yesterday-machine-1963',
    synopsis:
      'Um repórter investiga o desaparecimento de uma jovem e descobre um cientista nazista que sobreviveu à guerra e agora constrói, em segredo, uma máquina capaz de viajar no tempo.',
    year: 1963,
    director: 'Russ Marker',
    genres: ['Ficção Científica', 'Clássico'],
    runtimeMinutes: 78,
    backdropUrl: 'https://archive.org/services/img/TheYesterdayMachine1963',
    source: { provider: 'archive', id: 'TheYesterdayMachine1963' },
    featured: false,
  },
  {
    title: 'This Is Not a Test',
    slug: 'this-is-not-a-test-1962',
    synopsis:
      'Um grupo de motoristas é detido num bloqueio policial na estrada durante a noite e aos poucos percebe que se trata de um alerta real de ataque nuclear iminente, testando os limites de cada um sob pressão.',
    year: 1962,
    director: 'Fredric Gadette',
    genres: ['Ficção Científica', 'Drama', 'Clássico'],
    runtimeMinutes: 72,
    backdropUrl: 'https://archive.org/services/img/ThisisNotaTest',
    source: { provider: 'archive', id: 'ThisisNotaTest' },
    featured: false,
  },
  {
    title: 'Horrors of Spider Island',
    slug: 'horrors-of-spider-island-1962',
    synopsis:
      'Um grupo de dançarinas a caminho de um contrato em Singapura sofre um acidente aéreo e vai parar numa ilha deserta, onde seu empresário é picado por uma aranha gigante e começa a se transformar num monstro.',
    year: 1962,
    director: 'Fritz Böttger',
    genres: ['Terror', 'Ficção Científica', 'Clássico'],
    runtimeMinutes: 75,
    backdropUrl: 'https://archive.org/services/img/Horrors_of_Spider_Island',
    source: { provider: 'archive', id: 'Horrors_of_Spider_Island' },
    featured: false,
  },
  {
    title: 'Evil Brain from Outer Space',
    slug: 'evil-brain-from-outer-space-1964',
    synopsis:
      'Continuação da montagem americana do seriado japonês "Super Giant": o herói do espaço Starman enfrenta um cérebro alienígena maligno que ameaça escravizar a Terra.',
    year: 1964,
    genres: ['Ficção Científica', 'Clássico'],
    runtimeMinutes: 78,
    backdropUrl: 'https://archive.org/services/img/EvilBrainFromOuterSpace',
    source: { provider: 'archive', id: 'EvilBrainFromOuterSpace' },
    featured: false,
  },
  {
    title: 'The Killer Shrews',
    slug: 'the-killer-shrews-1959',
    synopsis:
      'Um grupo preso numa ilha isolada por uma tempestade descobre que um cientista, tentando resolver a superpopulação mundial, criou musaranhos gigantes e famintos que agora cercam a casa onde todos se refugiam.',
    year: 1959,
    director: 'Ray Kellogg',
    genres: ['Ficção Científica', 'Terror', 'Clássico'],
    runtimeMinutes: 69,
    backdropUrl: 'https://archive.org/services/img/The_Killer_Shrews',
    source: { provider: 'archive', id: 'The_Killer_Shrews' },
    featured: false,
  },
  {
    title: 'Phantom from Space',
    slug: 'phantom-from-space-1953',
    synopsis:
      'Um objeto não identificado cai perto de Los Angeles e libera um ser invisível que só pode ser visto quando veste um traje espacial, espalhando pânico pela cidade enquanto as autoridades tentam capturá-lo.',
    year: 1953,
    director: 'W. Lee Wilder',
    genres: ['Ficção Científica', 'Clássico'],
    runtimeMinutes: 72,
    backdropUrl: 'https://archive.org/services/img/Phantom_From_Space',
    source: { provider: 'archive', id: 'Phantom_From_Space' },
    featured: false,
  },
  {
    title: 'The Phantom Creeps',
    slug: 'the-phantom-creeps-1939',
    synopsis:
      'Recorte em longa de um seriado da Universal: um cientista obcecado por poder usa um cinto que o torna invisível e um robô gigante controlado a distância para tentar dominar o mundo, sempre um passo à frente dos investigadores.',
    year: 1939,
    director: 'Ford Beebe, Saul A. Goodkind',
    cast: ['Bela Lugosi'],
    genres: ['Ficção Científica', 'Clássico'],
    runtimeMinutes: 78,
    backdropUrl: 'https://archive.org/services/img/ThePhantomCreeps',
    source: { provider: 'archive', id: 'ThePhantomCreeps' },
    featured: false,
  },
  {
    title: 'Monstrosity',
    slug: 'monstrosity-1964',
    synopsis:
      'Também conhecido como "The Atomic Brain": uma milionária idosa contrata um cientista para transplantar seu cérebro para o corpo de uma jovem, mas os experimentos com animais e humanos saem terrivelmente errados.',
    year: 1964,
    director: 'Joseph V. Mascelli',
    genres: ['Ficção Científica', 'Terror', 'Clássico'],
    runtimeMinutes: 65,
    backdropUrl: 'https://archive.org/services/img/atomic_brain_1964',
    source: { provider: 'archive', id: 'atomic_brain_1964' },
    featured: false,
  },
  {
    title: 'Bride of the Gorilla',
    slug: 'bride-of-the-gorilla-1951',
    synopsis:
      'Na selva sul-americana, um administrador de plantação que mata o patrão para ficar com a esposa dele é amaldiçoado por uma nativa e passa a se transformar numa fera à noite.',
    year: 1951,
    director: 'Curt Siodmak',
    cast: ['Raymond Burr'],
    genres: ['Terror', 'Clássico'],
    runtimeMinutes: 57,
    backdropUrl: 'https://archive.org/services/img/bride_of_a_gorilla',
    source: { provider: 'archive', id: 'bride_of_a_gorilla' },
    featured: false,
  },
  {
    title: 'Black Dragons',
    slug: 'black-dragons-1942',
    synopsis:
      'Uma série de mortes misteriosas atinge industriais americanos, e o FBI descobre que um médico usou cirurgia plástica para infiltrar agentes japoneses disfarçados de líderes empresariais dos EUA.',
    year: 1942,
    director: 'William Nigh',
    cast: ['Bela Lugosi'],
    genres: ['Suspense', 'Terror', 'Clássico'],
    runtimeMinutes: 62,
    backdropUrl: 'https://archive.org/services/img/BlackDragons',
    source: { provider: 'archive', id: 'BlackDragons' },
    featured: false,
  },
  {
    title: 'Dead Men Walk',
    slug: 'dead-men-walk-1943',
    synopsis:
      'Um médico respeitado é assassinado em segredo pelo próprio irmão gêmeo, que praticava ocultismo, e retorna do túmulo como um vampiro para se vingar da família que o condenou.',
    year: 1943,
    director: 'Sam Newfield',
    cast: ['George Zucco'],
    genres: ['Terror', 'Clássico'],
    runtimeMinutes: 64,
    backdropUrl: 'https://archive.org/services/img/DeadMenWalk',
    source: { provider: 'archive', id: 'DeadMenWalk' },
    featured: false,
  },
  {
    title: 'White Pongo',
    slug: 'white-pongo-1945',
    synopsis:
      'Uma expedição à selva africana parte em busca de um lendário gorila branco que pode ser o elo perdido entre o macaco e o homem, enfrentando rivais dispostos a tudo para capturar o animal primeiro.',
    year: 1945,
    director: 'Sam Newfield',
    genres: ['Aventura', 'Terror', 'Clássico'],
    runtimeMinutes: 72,
    backdropUrl: 'https://archive.org/services/img/WhitePongo',
    source: { provider: 'archive', id: 'WhitePongo' },
    featured: false,
  },
  {
    title: 'The Monster Maker',
    slug: 'the-monster-maker-1944',
    synopsis:
      'Um cientista louco infecta de propósito um pianista famoso com uma doença que causa deformações no rosto, na esperança de forçar a filha do músico a se casar com ele em troca da cura.',
    year: 1944,
    director: 'Sam Newfield',
    cast: ['J. Carrol Naish'],
    genres: ['Terror', 'Clássico'],
    runtimeMinutes: 62,
    backdropUrl: 'https://archive.org/services/img/The_Monster_Maker',
    source: { provider: 'archive', id: 'The_Monster_Maker' },
    featured: false,
  },
  {
    title: "The Mummy's Tomb",
    slug: 'the-mummys-tomb-1942',
    synopsis:
      'Décadas depois dos eventos de "A Mão da Múmia", a múmia Kharis é levada aos Estados Unidos e libertada por um sacerdote decidido a vingar a profanação do túmulo da princesa egípcia, perseguindo os descendentes dos arqueólogos responsáveis.',
    year: 1942,
    director: 'Harold Young',
    cast: ['Lon Chaney Jr.'],
    genres: ['Terror', 'Clássico'],
    runtimeMinutes: 61,
    backdropUrl: 'https://archive.org/services/img/the-mummy-s-tomb-1942',
    source: { provider: 'archive', id: 'the-mummy-s-tomb-1942' },
    featured: false,
  },
  {
    title: 'King of the Zombies',
    slug: 'king-of-the-zombies-1941',
    synopsis:
      'Náufragos que vão parar numa ilha caribenha descobrem que a mansão local esconde um médico usando vodu para controlar zumbis, numa trama envolvendo espionagem em plena Segunda Guerra.',
    year: 1941,
    director: 'Jean Yarbrough',
    genres: ['Terror', 'Comédia', 'Clássico'],
    runtimeMinutes: 67,
    backdropUrl: 'https://archive.org/services/img/KingOfTheZombies',
    source: { provider: 'archive', id: 'KingOfTheZombies' },
    featured: false,
  },
  {
    title: 'Voodoo Man',
    slug: 'voodoo-man-1944',
    synopsis:
      'O dono de um posto de gasolina sequestra jovens viajantes com a ajuda de dois comparsas, na tentativa desesperada de usar magia negra para tirar sua esposa catatônica do transe em que vive há anos.',
    year: 1944,
    director: 'William Beaudine',
    cast: ['Bela Lugosi', 'John Carradine'],
    genres: ['Terror', 'Clássico'],
    runtimeMinutes: 62,
    backdropUrl: 'https://archive.org/services/img/voodoo-man-1944',
    source: { provider: 'archive', id: 'voodoo-man-1944' },
    featured: false,
  },
  {
    title: 'Spooks Run Wild',
    slug: 'spooks-run-wild-1941',
    synopsis:
      'Os East Side Kids são mandados para um acampamento de férias perto de uma casa supostamente mal-assombrada, onde um mágico misterioso e um assassino de verdade em fuga se misturam para criar uma noite de confusão.',
    year: 1941,
    director: 'Phil Rosen',
    cast: ['Bela Lugosi'],
    genres: ['Terror', 'Comédia', 'Clássico'],
    runtimeMinutes: 64,
    backdropUrl: 'https://archive.org/services/img/spooks_run_wild',
    source: { provider: 'archive', id: 'spooks_run_wild' },
    featured: false,
  },
  {
    title: 'Ghosts on the Loose',
    slug: 'ghosts-on-the-loose-1943',
    synopsis:
      'A turma dos East Side Kids invade por engano uma casa que serve de esconderijo para espiões nazistas disfarçados de fantasmas, numa mistura de comédia pastelão com espionagem de guerra.',
    year: 1943,
    director: 'William Beaudine',
    cast: ['Bela Lugosi'],
    genres: ['Terror', 'Comédia', 'Clássico'],
    runtimeMinutes: 65,
    backdropUrl: 'https://archive.org/services/img/GhostsontheLoose',
    source: { provider: 'archive', id: 'GhostsontheLoose' },
    featured: false,
  },
  {
    title: 'The Great Gabbo',
    slug: 'the-great-gabbo-1929',
    synopsis:
      'Um ventríloquo egocêntrico e cada vez mais dependente do próprio boneco começa a perder a sanidade, deixando que o fantoche expresse os sentimentos que ele mesmo é incapaz de admitir.',
    year: 1929,
    director: 'James Cruze',
    cast: ['Erich von Stroheim'],
    genres: ['Drama', 'Clássico'],
    runtimeMinutes: 92,
    backdropUrl: 'https://archive.org/services/img/the-great-gabbo_1929',
    source: { provider: 'archive', id: 'the-great-gabbo_1929' },
    featured: false,
  },
  {
    title: 'The Phantom Broadcast',
    slug: 'the-phantom-broadcast-1933',
    synopsis:
      'O sucesso de um crooner de rádio na verdade é construído em cima da voz de outro homem, que canta escondido nos bastidores; quando o verdadeiro cantor é assassinado, a suspeita recai sobre todos ligados ao programa.',
    year: 1933,
    director: 'Phil Rosen',
    genres: ['Suspense', 'Clássico'],
    runtimeMinutes: 72,
    backdropUrl: 'https://archive.org/services/img/ThePhantomBroadcast',
    source: { provider: 'archive', id: 'ThePhantomBroadcast' },
    featured: false,
  },
  {
    title: 'Bela Lugosi Meets a Brooklyn Gorilla',
    slug: 'bela-lugosi-meets-a-brooklyn-gorilla-1952',
    synopsis:
      'Dois trapalhões descobrem, numa ilha tropical, o laboratório secreto de um cientista louco que tenta transformar homens em gorilas gigantes, numa comédia de terror com direito a perseguições e confusões em série.',
    year: 1952,
    director: 'William Beaudine',
    cast: ['Bela Lugosi'],
    genres: ['Comédia', 'Terror', 'Clássico'],
    runtimeMinutes: 74,
    backdropUrl: 'https://archive.org/services/img/BelaLugosiMeetsaBrooklynGorilla',
    source: { provider: 'archive', id: 'BelaLugosiMeetsaBrooklynGorilla' },
    featured: false,
  },
  {
    title: 'Eegah',
    slug: 'eegah-1962',
    synopsis:
      'Uma adolescente encontra um homem das cavernas gigante vagando pelo deserto e o leva para casa, para o desespero do namorado dela, numa comédia B que se tornou cult pela ingenuidade dos efeitos.',
    year: 1962,
    director: 'Arch Hall Sr.',
    genres: ['Ficção Científica', 'Comédia', 'Clássico'],
    runtimeMinutes: 90,
    backdropUrl: 'https://archive.org/services/img/Eegah',
    source: { provider: 'archive', id: 'Eegah' },
    featured: false,
  },
  {
    title: 'Horror Hotel',
    slug: 'horror-hotel-1960',
    synopsis:
      'Também conhecido como "City of the Dead": uma estudante viaja a uma cidadezinha de Massachusetts para pesquisar bruxaria e descobre que os moradores locais ainda praticam cultos satânicos secretos há séculos.',
    year: 1960,
    director: 'John Llewellyn Moxey',
    cast: ['Christopher Lee'],
    genres: ['Terror', 'Clássico'],
    runtimeMinutes: 76,
    backdropUrl: 'https://archive.org/services/img/HorrorHotel1960',
    source: { provider: 'archive', id: 'HorrorHotel1960' },
    featured: false,
  },
  {
    title: 'One Body Too Many',
    slug: 'one-body-too-many-1944',
    synopsis:
      'Um vendedor de seguros de vida chega à mansão de um milionário excêntrico bem a tempo do velório, e se vê no meio de uma disputa de herança onde os parentes começam a morrer um a um.',
    year: 1944,
    director: 'Frank McDonald',
    cast: ['Jack Haley', 'Bela Lugosi'],
    genres: ['Suspense', 'Comédia', 'Clássico'],
    runtimeMinutes: 75,
    backdropUrl: 'https://archive.org/services/img/One_Body_Too_Many',
    source: { provider: 'archive', id: 'One_Body_Too_Many' },
    featured: false,
  },
  {
    title: 'Isle of the Dead',
    slug: 'isle-of-the-dead-1945',
    synopsis:
      'Durante as Guerras dos Balcãs, um general grego fica em quarentena numa ilha atingida pela peste e, à medida que as mortes se acumulam, passa a acreditar que uma superstição local sobre um espírito vampírico é real.',
    year: 1945,
    director: 'Mark Robson',
    cast: ['Boris Karloff'],
    genres: ['Terror', 'Clássico'],
    runtimeMinutes: 72,
    backdropUrl: 'https://archive.org/services/img/isle-of-the-dead-1954',
    source: { provider: 'archive', id: 'isle-of-the-dead-1954' },
    featured: false,
  },
  {
    title: 'The Cat and the Canary',
    slug: 'the-cat-and-the-canary-1927',
    synopsis:
      'Vinte anos após a morte de um milionário excêntrico, seus parentes se reúnem numa mansão decadente para a leitura do testamento, e um misterioso assassino encapuzado começa a perseguir a herdeira designada como única beneficiária.',
    year: 1927,
    director: 'Paul Leni',
    genres: ['Terror', 'Mudo', 'Clássico'],
    runtimeMinutes: 82,
    backdropUrl: 'https://archive.org/services/img/catcanary-4-k',
    source: { provider: 'archive', id: 'catcanary-4-k' },
    featured: false,
  },
  {
    title: 'Waxworks',
    slug: 'waxworks-1924',
    synopsis:
      'Um jovem poeta contratado para escrever histórias sobre as figuras de cera de uma feira imagina três episódios sombrios estrelados por Harun al-Rashid, Ivan, o Terrível, e Jack, o Estripador.',
    year: 1924,
    director: 'Paul Leni, Leo Birinski',
    cast: ['Conrad Veidt', 'Emil Jannings'],
    genres: ['Terror', 'Mudo', 'Clássico'],
    runtimeMinutes: 85,
    backdropUrl: 'https://archive.org/services/img/abc_20231024',
    source: { provider: 'archive', id: 'abc_20231024' },
    featured: false,
  },
  {
    title: 'The Man Who Laughs',
    slug: 'the-man-who-laughs-1928',
    synopsis:
      'Desfigurado na infância por ordem de um rei cruel e condenado a exibir um sorriso permanente e grotesco, um homem vira atração de circo e se apaixona, enquanto uma trama de intrigas na nobreza ameaça revelar sua verdadeira origem.',
    year: 1928,
    director: 'Paul Leni',
    cast: ['Conrad Veidt', 'Mary Philbin'],
    genres: ['Drama', 'Terror', 'Mudo', 'Clássico'],
    runtimeMinutes: 110,
    backdropUrl: 'https://archive.org/services/img/the-man-who-laughs-1928-w-720p',
    source: { provider: 'archive', id: 'the-man-who-laughs-1928-w-720p' },
    featured: false,
  },
  {
    title: 'The Last Warning',
    slug: 'the-last-warning-1928',
    synopsis:
      'Anos depois de um ator morrer misteriosamente durante uma peça, um produtor reabre o mesmo teatro da Broadway com o elenco original, mas avisos anônimos insistem que o espetáculo não deveria continuar.',
    year: 1928,
    director: 'Paul Leni',
    genres: ['Suspense', 'Terror', 'Mudo', 'Clássico'],
    runtimeMinutes: 78,
    backdropUrl: 'https://archive.org/services/img/the.-last.-warning.-1928',
    source: { provider: 'archive', id: 'the.-last.-warning.-1928' },
    featured: false,
  },
  {
    title: 'Warning Shadows',
    slug: 'warning-shadows-1923',
    synopsis:
      'Durante um jantar, um artista de sombras ambulante usa seu teatro de silhuetas para revelar aos convidados de um nobre ciumento os desejos secretos escondidos por trás das aparências, quase levando a uma tragédia.',
    year: 1923,
    director: 'Arthur Robison',
    genres: ['Terror', 'Mudo', 'Clássico'],
    runtimeMinutes: 85,
    backdropUrl: 'https://archive.org/services/img/warning-shadows-1923-restored-720p-hd',
    source: { provider: 'archive', id: 'warning-shadows-1923-restored-720p-hd' },
    featured: false,
  },
  {
    title: 'Seven Footprints to Satan',
    slug: 'seven-footprints-to-satan-1929',
    synopsis:
      'Um jovem casal é sequestrado e levado a uma mansão comandada por uma figura misteriosa vestida de diabo, que os submete a uma série de provações aterrorizantes disfarçadas de ritual satânico.',
    year: 1929,
    director: 'Benjamin Christensen',
    genres: ['Terror', 'Comédia', 'Mudo', 'Clássico'],
    runtimeMinutes: 76,
    backdropUrl: 'https://archive.org/services/img/seven-footprints-to-satan_1929',
    source: { provider: 'archive', id: 'seven-footprints-to-satan_1929' },
    featured: false,
  },
  {
    title: 'The Fall of the House of Usher',
    slug: 'the-fall-of-the-house-of-usher-1928',
    synopsis:
      'Curta-metragem experimental americano baseado no conto de Edgar Allan Poe, usando efeitos visuais de vanguarda para narrar a decadência da família Usher e o enterro precipitado da irmã doente do protagonista.',
    year: 1928,
    director: 'James Sibley Watson, Melville Webber',
    genres: ['Terror', 'Mudo', 'Clássico'],
    runtimeMinutes: 13,
    backdropUrl: 'https://archive.org/services/img/TheFallOfTheHouseOfUsher1928',
    source: { provider: 'archive', id: 'TheFallOfTheHouseOfUsher1928' },
    featured: false,
  },
];
