/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'outline-variant': '#4d4354',
        'secondary-container': '#00b954',
        'tertiary-container': '#919191',
        'error-container': '#93000a',
        'on-surface-variant': '#cfc2d6',
        'inverse-primary': 'rgb(var(--color-inverse-primary) / <alpha-value>)',
        'primary-container': 'rgb(var(--color-primary-container) / <alpha-value>)',
        primary: 'rgb(var(--color-primary) / <alpha-value>)',
        'on-error': '#690005',
        'surface-container-highest': '#2b3544',
        'on-tertiary': '#303030',
        outline: '#988d9f',
        'on-primary-fixed': 'rgb(var(--color-on-primary-fixed) / <alpha-value>)',
        'on-surface': '#d9e3f6',
        'on-primary-fixed-variant': 'rgb(var(--color-on-primary-fixed-variant) / <alpha-value>)',
        'inverse-on-surface': '#27313f',
        'on-tertiary-container': '#2a2a2a',
        'secondary-fixed': '#6bff8f',
        'surface-container-lowest': '#050f1c',
        'on-error-container': '#ffdad6',
        'on-primary-container': 'rgb(var(--color-on-primary-container) / <alpha-value>)',
        secondary: '#4ae176',
        background: '#091421',
        'primary-fixed-dim': 'rgb(var(--color-primary-fixed-dim) / <alpha-value>)',
        'primary-fixed': 'rgb(var(--color-primary-fixed) / <alpha-value>)',
        'on-secondary-fixed-variant': '#005321',
        'inverse-surface': '#d9e3f6',
        error: '#ffb4ab',
        'on-tertiary-fixed': '#1b1b1b',
        'on-secondary-container': '#004119',
        'surface-variant': '#2b3544',
        'on-tertiary-fixed-variant': '#474747',
        'on-secondary': '#003915',
        'surface-bright': '#303a48',
        'tertiary-fixed-dim': '#c6c6c6',
        surface: '#091421',
        'surface-container': '#16202e',
        'on-background': '#d9e3f6',
        'surface-container-low': '#121c2a',
        'surface-dim': '#091421',
        'surface-container-high': '#212b39',
        tertiary: '#c6c6c6',
        'on-primary': 'rgb(var(--color-on-primary) / <alpha-value>)',
        'on-secondary-fixed': '#002109',
        'secondary-fixed-dim': '#4ae176',
        'surface-tint': 'rgb(var(--color-surface-tint) / <alpha-value>)',
        'tertiary-fixed': '#e2e2e2',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'sidebar-width': '280px',
        'container-margin': '24px',
        gutter: '16px',
        unit: '8px',
      },
      fontFamily: {
        display: ['Montserrat', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['64px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
